-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/client-rpc-surface.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- The SECURITY DEFINER functions clients can call through PostgREST RPC are exactly the reviewed
-- caller-bound helpers below. Clients hold no table privileges (anon since 20260930181000,
-- authenticated since 20260930182000), so RPC is their only direct path, and a DEFINER function
-- runs as its owner past row-level security. Adding a function here needs a review that it
-- answers only for the caller (check-migrations CALLER_BOUND_HELPERS). A parameter that defaults
-- to auth.uid() doesn't make it so: business_get_user_permissions answered for anyone until
-- 20260930183000. Trigger functions can't be called through RPC and are left out.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
DO $$
DECLARE
  expected text[] := ARRAY['gig_creator_has_current_authority','has_home_permission',
    'home_bill_has_finance_permission','home_can_see_visibility','home_get_user_permissions',
    'home_has_permission','home_has_role_at_least','home_is_active_member','home_member_can',
    'home_my_role','is_active_chat_participant','is_home_member'];
  actual text[];
BEGIN
  SELECT coalesce(array_agg(DISTINCT p.proname::text ORDER BY p.proname::text), '{}') INTO actual
  FROM pg_proc p
  WHERE p.pronamespace = 'public'::regnamespace AND p.prosecdef AND p.prokind = 'f'
    AND p.prorettype <> 'trigger'::regtype
    AND NOT EXISTS (SELECT 1 FROM pg_depend d
      WHERE d.classid = 'pg_proc'::regclass AND d.objid = p.oid AND d.deptype = 'e')
    AND (has_function_privilege('anon', p.oid, 'EXECUTE')
      OR has_function_privilege('authenticated', p.oid, 'EXECUTE'));
  IF actual IS DISTINCT FROM (SELECT array_agg(x ORDER BY x) FROM unnest(expected) x) THEN
    RAISE EXCEPTION 'Client RPC surface changed: callable SECURITY DEFINER functions are %, expected %',
      actual, expected;
  END IF;
  IF has_function_privilege('anon', 'public.business_get_user_permissions(uuid,uuid)', 'EXECUTE')
    OR has_function_privilege('authenticated', 'public.business_get_user_permissions(uuid,uuid)', 'EXECUTE')
    OR has_function_privilege('anon', 'public.apply_business_role_preset(uuid,uuid,text)', 'EXECUTE')
    OR has_function_privilege('authenticated', 'public.apply_business_role_preset(uuid,uuid,text)', 'EXECUTE')
    OR NOT has_function_privilege('service_role', 'public.business_get_user_permissions(uuid,uuid)', 'EXECUTE')
    OR NOT has_function_privilege('service_role', 'public.apply_business_role_preset(uuid,uuid,text)', 'EXECUTE') THEN
    RAISE EXCEPTION 'Business permission RPCs must be service-only';
  END IF;
END $$;
SET LOCAL ROLE anon;
DO $$ BEGIN
  BEGIN
    PERFORM public.business_get_user_permissions(gen_random_uuid(), gen_random_uuid());
    RAISE EXCEPTION 'Anonymous caller read business permissions';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', gen_random_uuid()::text, true);
DO $$ BEGIN
  BEGIN
    PERFORM public.business_get_user_permissions(gen_random_uuid(), gen_random_uuid());
    RAISE EXCEPTION 'Signed-in caller read another person''s business permissions';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  BEGIN
    PERFORM public.apply_business_role_preset(gen_random_uuid(), gen_random_uuid(), 'contract-probe');
    RAISE EXCEPTION 'Signed-in caller applied a business role preset directly';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SELECT 'PASS: client RPC surface is the reviewed caller-bound helpers; business permission RPCs are service-only' AS result;

$contract$, 'client-rpc-surface.sql');
SELECT * FROM finish();
ROLLBACK;
