-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/current-home-bill-comparisons.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Live, exact-currency monthly aggregates: no legacy cache or source mutation.
SET LOCAL statement_timeout='30s'; SET LOCAL lock_timeout='5s';
CREATE FUNCTION pg_temp.bc_id(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$
 SELECT ('ddc24800-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid;
$$;
INSERT INTO auth.users(id,email,email_confirmed_at)
 SELECT pg_temp.bc_id(n),'bill-current-'||n||'@example.invalid',now() FROM generate_series(1,12)n;
INSERT INTO public."User"(id,email,username)
 SELECT id,email,'bill_current_'||right(id::text,3) FROM auth.users WHERE id IN(SELECT pg_temp.bc_id(n) FROM generate_series(1,12)n);
INSERT INTO public."Home"(id,owner_id,address,city,state,zipcode,location)
 SELECT pg_temp.bc_id(100+n),pg_temp.bc_id(n),'Private comparison fixture','Test','WA','98607',ST_SetSRID(ST_MakePoint(0,0),4326)
 FROM generate_series(1,12)n;
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status,start_at)
 SELECT pg_temp.bc_id(100+n),pg_temp.bc_id(n),'owner','owner','adult','verified',now()-interval '1 day' FROM generate_series(1,12)n;
INSERT INTO public."HomePreference"(home_id,settings)
 SELECT pg_temp.bc_id(100+n),'{"bill_benchmark_opt_in":true}' FROM generate_series(1,10)n;
INSERT INTO public."HomeBill"(id,home_id,created_by,bill_type,amount,currency,status,period_start)
 SELECT pg_temp.bc_id(200+n),pg_temp.bc_id(100+n),pg_temp.bc_id(n),'electric',CASE WHEN n=1 THEN 71.25 ELSE 100.50 END,'USD','paid',
   (date_trunc('month',CURRENT_DATE)-interval '1 month')::date FROM generate_series(1,10)n;
INSERT INTO public."HomeBill"(id,home_id,created_by,bill_type,amount,currency,status,period_start) VALUES
 (pg_temp.bc_id(220),pg_temp.bc_id(101),pg_temp.bc_id(1),'electric',71.25,'USD','paid',(date_trunc('month',CURRENT_DATE)-interval '1 month')::date),
 (pg_temp.bc_id(221),pg_temp.bc_id(101),pg_temp.bc_id(1),'electric',999.99,'CAD','paid',(date_trunc('month',CURRENT_DATE)-interval '1 month')::date),
 (pg_temp.bc_id(222),pg_temp.bc_id(101),pg_temp.bc_id(1),'electric',999.99,'USD','due',(date_trunc('month',CURRENT_DATE)-interval '1 month')::date),
 (pg_temp.bc_id(223),pg_temp.bc_id(101),pg_temp.bc_id(1),'electric',999.99,'USD','paid',(CURRENT_DATE-interval '3 years')::date),
 (pg_temp.bc_id(224),pg_temp.bc_id(101),pg_temp.bc_id(1),'electric',999.99,'USD','paid',(CURRENT_DATE+interval '1 month')::date);
CREATE TEMP TABLE bc_original AS SELECT to_jsonb(b) AS value FROM public."HomeBill" b WHERE home_id IN(SELECT pg_temp.bc_id(100+n) FROM generate_series(1,12)n);
GRANT SELECT ON bc_original TO service_role;
SET LOCAL ROLE service_role;
DO $$ DECLARE r jsonb; peer jsonb; h uuid:=pg_temp.bc_id(101); a uuid:=pg_temp.bc_id(1); BEGIN
 IF has_function_privilege('authenticated','public.get_home_bill_comparison(uuid,uuid,text)','EXECUTE')
   OR has_function_privilege('anon','public.read_bill_peer_months(text,text)','EXECUTE') THEN RAISE EXCEPTION 'Unsafe financial RPC grants'; END IF;
 r:=public.get_home_bill_comparison(h,a,'USD');
 IF r->>'ok'<>'true' OR (r->'own_months'->0->>'amount')::numeric<>142.50 OR jsonb_array_length(r->'own_months')<>1
   OR r->'available_currencies'<>'["CAD","USD"]'::jsonb THEN RAISE EXCEPTION 'Own monthly/currency/date filter incorrect: %',r; END IF;
 peer:=r->'peer_months'->0;
 IF (peer->>'household_count')::integer<>10 OR (peer->>'avg_amount')::numeric<>104.70
   OR (peer->>'median_amount')::numeric<>100.50 THEN RAISE EXCEPTION 'Expected household-weighted major-unit aggregate: %',peer; END IF;
 IF r::text LIKE '%home_id%ddc24800-0000-4000-8000-000000000102%' THEN RAISE EXCEPTION 'Neighbor identifier leaked'; END IF;
 r:=public.get_home_bill_comparison(h,a,'CAD');
 IF (r->'own_months'->0->>'amount')::numeric<>999.99 OR r->'peer_months'<>'[]'::jsonb THEN RAISE EXCEPTION 'Mixed currencies'; END IF;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,a,'finance.view',false);
 r:=public.get_home_bill_comparison(h,a,'USD');
 IF r->>'can_view_finance'<>'false' OR r->'own_months'<>'[]'::jsonb OR r->'available_currencies'<>'[]'::jsonb
   OR (r->'peer_months'->0->>'avg_amount')::numeric<>104.70 THEN RAISE EXCEPTION 'Personal-finance restriction incorrect'; END IF;
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,a,'home.view',false);
 IF public.get_home_bill_comparison(h,a,'USD')->>'code'<>'HOME_BILLS_DENIED' THEN RAISE EXCEPTION 'Home view deny bypassed'; END IF;
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h;
 IF public.get_home_bill_comparison(h,pg_temp.bc_id(2),'USD')->>'code'<>'HOME_BILLS_DENIED'
   OR public.get_home_bill_comparison(h,a,'bad currency')->>'code'<>'HOME_BILLS_INVALID' THEN RAISE EXCEPTION 'Invalid request allowed'; END IF;
 UPDATE public."HomePreference" SET settings='{"bill_benchmark_opt_in":false}' WHERE home_id=pg_temp.bc_id(110);
 r:=public.get_home_bill_comparison(h,a,'USD');peer:=r->'peer_months'->0;
 IF (peer->>'household_count')::integer<>9 OR peer->'avg_amount'<>'null'::jsonb OR peer->'median_amount'<>'null'::jsonb THEN RAISE EXCEPTION 'Stale opt-out or sub-threshold amount'; END IF;
 UPDATE public."HomePreference" SET settings='{"bill_benchmark_opt_in":true}' WHERE home_id=pg_temp.bc_id(110);
 UPDATE public."HomeBill" SET status='due' WHERE id=pg_temp.bc_id(210);
 IF (public.get_home_bill_comparison(h,a,'USD')->'peer_months'->0->>'household_count')::integer<>9 THEN RAISE EXCEPTION 'Stale unpaid correction'; END IF;
 UPDATE public."HomeBill" SET status='paid' WHERE id=pg_temp.bc_id(210);
 UPDATE public."Home" SET location=ST_SetSRID(ST_MakePoint(10,10),4326) WHERE id=pg_temp.bc_id(110);
 IF (public.get_home_bill_comparison(h,a,'USD')->'peer_months'->0->>'household_count')::integer<>9 THEN RAISE EXCEPTION 'Stale moved Home'; END IF;
 UPDATE public."Home" SET location=ST_SetSRID(ST_MakePoint(0,0),4326) WHERE id=pg_temp.bc_id(110);
 -- A deleted contribution disappears immediately, and exact restoration is
 -- read afresh. Keep the source-row snapshot for the final preservation check.
 DELETE FROM public."HomeBill" WHERE id=pg_temp.bc_id(210);
 IF (public.get_home_bill_comparison(h,a,'USD')->'peer_months'->0->>'household_count')::integer<>9 THEN RAISE EXCEPTION 'Stale deleted contribution'; END IF;
 INSERT INTO public."HomeBill" SELECT (jsonb_populate_record(NULL::public."HomeBill",value)).* FROM bc_original WHERE value->>'id'=pg_temp.bc_id(210)::text;
 IF (public.get_home_bill_comparison(h,a,'USD')->'peer_months'->0->>'avg_amount')::numeric<>104.70 THEN RAISE EXCEPTION 'Restored contribution not read'; END IF;
 UPDATE public."HomePreference" SET settings='{"bill_benchmark_opt_in":false}' WHERE home_id IN(SELECT pg_temp.bc_id(100+n) FROM generate_series(4,10)n);
 r:=public.get_home_bill_comparison(h,a,'USD');peer:=r->'peer_months'->0;
 IF (peer->>'household_count')::integer<>3 OR peer->'avg_amount'<>'null'::jsonb OR peer->'median_amount'<>'null'::jsonb THEN RAISE EXCEPTION 'Three-household floor exposed values'; END IF;
 IF (public.get_home_bill_comparison(h,a,'USD')-'as_of')<>(r-'as_of') THEN RAISE EXCEPTION 'Repeated read changed current result'; END IF;
 UPDATE public."HomePreference" SET settings='{"bill_benchmark_opt_in":false}' WHERE home_id=pg_temp.bc_id(103);
 IF public.get_home_bill_comparison(h,a,'USD')->'peer_months'<>'[]'::jsonb THEN RAISE EXCEPTION 'Sub-three cohort leaked'; END IF;
 UPDATE public."HomePreference" SET settings='{"bill_benchmark_opt_in":false}' WHERE home_id IN(SELECT pg_temp.bc_id(100+n) FROM generate_series(1,10)n);
 IF public.get_home_bill_comparison(h,a,'USD')->'peer_months'<>'[]'::jsonb THEN RAISE EXCEPTION 'All opt-outs left a derived cohort'; END IF;
 IF public.home_bill_geohash(NULL,NULL,NULL) IS NOT NULL OR public.home_bill_geohash(NULL,0,0)<>'s00000'
   OR public.home_bill_geohash(NULL,91,0) IS NOT NULL THEN RAISE EXCEPTION 'Coordinate contract incorrect'; END IF;
END $$;
RESET ROLE;
DO $$ BEGIN
 IF EXISTS((SELECT value FROM bc_original) EXCEPT (SELECT to_jsonb(b) FROM public."HomeBill" b WHERE home_id IN(SELECT pg_temp.bc_id(100+n) FROM generate_series(1,12)n)))
 THEN RAISE EXCEPTION 'Read changed source bills'; END IF;
END $$;

$contract$, 'current-home-bill-comparisons.sql');
SELECT * FROM finish();
ROLLBACK;
