-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/gig-authorization-deadlines.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
INSERT INTO auth.users(id,email) VALUES
 ('aafe0000-0000-4000-8000-000000000001','deadline-payer@example.invalid'),
 ('aafe0000-0000-4000-8000-000000000002','deadline-worker@example.invalid');
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'deadline_'||right(id::text,1),'Deadline contract'
 FROM auth.users WHERE id::text LIKE 'aafe0000-%';
INSERT INTO public."Gig"(id,user_id,created_by,title,description,price,status,accepted_by,scheduled_start)
 VALUES('aafe0000-0000-4000-8000-000000000101','aafe0000-0000-4000-8000-000000000001',
 'aafe0000-0000-4000-8000-000000000001','Provider deadline','Synthetic',10,'assigned',
 'aafe0000-0000-4000-8000-000000000002',now()+interval '1 hour');
INSERT INTO public."Payment"(id,gig_id,payer_id,payee_id,amount_total,amount_subtotal,amount_platform_fee,amount_to_payee,
 stripe_customer_id,stripe_payment_intent_id,payment_status,authorization_expires_at)
 VALUES('aafe0000-0000-4000-8000-000000000301','aafe0000-0000-4000-8000-000000000101',
 'aafe0000-0000-4000-8000-000000000001','aafe0000-0000-4000-8000-000000000002',1000,1000,150,850,
 'cus_deadline','pi_deadline','authorized',now()+interval '7 days');
UPDATE public."Gig" SET payment_id='aafe0000-0000-4000-8000-000000000301',payment_status='authorized'
 WHERE id='aafe0000-0000-4000-8000-000000000101';
SET LOCAL ROLE service_role;
DO $$ DECLARE d jsonb; proof jsonb; result jsonb; seconds bigint; invalid jsonb; unchanged timestamptz; BEGIN
 seconds:=floor(extract(epoch FROM clock_timestamp()+interval '1 hour'))::bigint;
 d:=public.begin_legacy_gig_authorization('aafe0000-0000-4000-8000-000000000101','aafe0000-0000-4000-8000-000000000001');
 IF d ? 'error' THEN RAISE EXCEPTION 'Exact operation not admitted %',d; END IF;
 proof:=jsonb_build_object('id','pi_deadline','customer','cus_deadline','capture_method','manual','currency','usd','amount',1000,
  'payer_id','aafe0000-0000-4000-8000-000000000001','payee_id','aafe0000-0000-4000-8000-000000000002',
  'gig_id','aafe0000-0000-4000-8000-000000000101','status','requires_capture','amount_capturable',1000,
  'charge_id','ch_deadline','capture_before',seconds);
 result:=public.record_legacy_gig_authorization('aafe0000-0000-4000-8000-000000000101','aafe0000-0000-4000-8000-000000000001',
  (d->'attempt'->>'id')::uuid,(d->'attempt'->>'verified_at')::timestamptz,proof);
 IF result ? 'error' OR (result->'payment'->>'authorization_expires_at')::timestamptz IS DISTINCT FROM to_timestamp(seconds)
  OR result->'payment'->>'stripe_charge_id' IS DISTINCT FROM 'ch_deadline' THEN RAISE EXCEPTION 'Provider deadline not recorded exactly %',result; END IF;
 d:=result;
 result:=public.record_legacy_gig_authorization('aafe0000-0000-4000-8000-000000000101','aafe0000-0000-4000-8000-000000000001',
  (d->'attempt'->>'id')::uuid,(d->'attempt'->>'verified_at')::timestamptz,proof);
 IF result ? 'error' OR (result->'payment'->>'authorization_expires_at')::timestamptz IS DISTINCT FROM to_timestamp(seconds)
  THEN RAISE EXCEPTION 'Repeated read extended authorization'; END IF;
 d:=result; unchanged:=(d->'attempt'->>'verified_at')::timestamptz;
 FOREACH invalid IN ARRAY ARRAY[
  proof-'capture_before',proof||jsonb_build_object('capture_before',seconds::text),
  proof||'{"capture_before":253402300800}'::jsonb,proof||'{"charge_id":null}'::jsonb,
  proof||'{"capture_before":0}'::jsonb,proof||jsonb_build_object('capture_before',seconds-7200)
 ] LOOP
  result:=public.record_legacy_gig_authorization('aafe0000-0000-4000-8000-000000000101','aafe0000-0000-4000-8000-000000000001',
   (d->'attempt'->>'id')::uuid,unchanged,invalid);
  IF NOT (result ? 'error') THEN RAISE EXCEPTION 'Invalid deadline accepted %',invalid; END IF;
 END LOOP;
 IF (SELECT verified_at FROM public."GigLegacyAuthorization" WHERE id=(d->'attempt'->>'id')::uuid) IS DISTINCT FROM unchanged
  OR (SELECT authorization_expires_at FROM public."Payment" WHERE id='aafe0000-0000-4000-8000-000000000301') IS DISTINCT FROM to_timestamp(seconds)
  THEN RAISE EXCEPTION 'Rejected proof changed saved deadline'; END IF;
END $$;
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 BEGIN PERFORM public.record_legacy_gig_authorization(NULL,NULL,NULL,NULL,'{}');
  RAISE EXCEPTION 'Client could forge provider deadline'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;

$contract$, 'gig-authorization-deadlines.sql');
SELECT * FROM finish();
ROLLBACK;
