-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-member-task-defaults.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Ordinary shipped admission and deliberate Task defaults, without positive
-- permission overrides. Other contracts continue covering the general gateway.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
SET LOCAL search_path=public,extensions,pg_catalog;
CREATE TEMP TABLE member_task_roles_before AS SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) rows FROM public."HomeRolePermission"r;
GRANT SELECT ON member_task_roles_before TO service_role;
CREATE FUNCTION pg_temp.mt_id(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$
 SELECT ('ddc25100-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid;
$$;
CREATE FUNCTION pg_temp.mt_assert(v boolean,message text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF v IS DISTINCT FROM true THEN RAISE EXCEPTION '%',message; END IF; END $$;
CREATE FUNCTION pg_temp.mt_ok(r jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Unexpected result %',r; END IF; RETURN r; END $$;
CREATE FUNCTION pg_temp.mt_code(r jsonb,code text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'false' OR r->>'code' IS DISTINCT FROM code THEN RAISE EXCEPTION 'Expected %, got %',code,r; END IF; END $$;
CREATE FUNCTION pg_temp.mt_state(h uuid) RETURNS jsonb LANGUAGE sql AS $$
 SELECT jsonb_build_object('tasks',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]') FROM public."HomeTask"t WHERE home_id=h),
  'receipts',(SELECT coalesce(jsonb_agg(to_jsonb(r) ORDER BY request_id),'[]') FROM public."HomeTaskCreateReceipt"r WHERE home_id=h),
  'audit',(SELECT coalesce(jsonb_agg(to_jsonb(a) ORDER BY id),'[]') FROM public."HomeAuditLog"a WHERE home_id=h),
  'delivery',(SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY id),'[]') FROM public."HomeTaskAssignmentDelivery"d WHERE home_id=h));
$$;
INSERT INTO auth.users(id,email,email_confirmed_at)
 SELECT pg_temp.mt_id(n),'member-task-'||n||'@example.invalid',now() FROM generate_series(1,11)n;
INSERT INTO public."User"(id,email,username,name)
 SELECT id,email,'member_task_'||right(id::text,2),'Member Task fixture' FROM auth.users WHERE id::text LIKE 'ddc25100-0000-4000-8000-%';
INSERT INTO public."Home"(id,owner_id,created_by_user_id,address,city,state,zipcode) VALUES
 (pg_temp.mt_id(100),pg_temp.mt_id(1),pg_temp.mt_id(1),'Member Task fixture','Test','WA','98607'),
 (pg_temp.mt_id(200),NULL,pg_temp.mt_id(11),'Private setup fixture','Test','WA','98607');
INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status,is_primary_owner) VALUES(pg_temp.mt_id(100),pg_temp.mt_id(1),'verified',true);
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status) VALUES
 (pg_temp.mt_id(100),pg_temp.mt_id(1),'owner','owner','adult','verified'),
 (pg_temp.mt_id(100),pg_temp.mt_id(4),'member','member','child','verified'),
 (pg_temp.mt_id(100),pg_temp.mt_id(5),'member','member','teen','verified'),
 (pg_temp.mt_id(100),pg_temp.mt_id(6),'member','member','child','pending_doc'),
 (pg_temp.mt_id(200),pg_temp.mt_id(11),'admin','admin',NULL,'pending_doc');
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:=pg_temp.mt_id(100); o uuid:=pg_temp.mt_id(1); a uuid:=pg_temp.mt_id(2); b uuid:=pg_temp.mt_id(3);
 ph uuid:=pg_temp.mt_id(200); priv uuid:=pg_temp.mt_id(11); u uuid; i uuid; t uuid; other_task uuid; hidden uuid; mail uuid;
 request_id uuid:=pg_temp.mt_id(500); original jsonb; r jsonb; before_rows jsonb; n integer; state text; perm text;
 nonnull_id uuid; legacy_id uuid; reviewed jsonb; reviewed_legacy jsonb; stored_invites jsonb; policy_before jsonb;
BEGIN
 PERFORM pg_temp.mt_assert((SELECT count(*)=2 FROM public."HomeRolePermission" WHERE role_base='member'
  AND permission IN ('tasks.view','tasks.edit') AND allowed),'Missing deliberate member defaults');
 PERFORM pg_temp.mt_assert(NOT public.home_has_permission(h,'tasks.view',a),'An address or unissued invitation granted Tasks');
 -- Browser member+tenant and native bare-member both resolve the real policy.
 FOR n IN 2..3 LOOP
  u:=pg_temp.mt_id(n);
  r:=pg_temp.mt_ok(public.write_home_invitation(h,o,'create',jsonb_build_object('user_id',u,'relationship','member')
    ||CASE WHEN n=2 THEN '{"preset_key":"tenant"}'::jsonb ELSE '{}'::jsonb END,repeat(n::text,64)));
  i:=(r->'invitation'->>'id')::uuid;
  PERFORM pg_temp.mt_assert(NOT public.home_has_permission(h,'tasks.view',u),'Pending invitation granted Tasks');
  r:=pg_temp.mt_ok(public.act_on_home_invitation(i,NULL,u,'accept'));
  PERFORM pg_temp.mt_assert(r->'occupancy'->>'role_base'='member' AND r->'occupancy'->>'age_band' IS NULL
    AND r->'occupancy'->>'verification_status'='verified','Admission changed role, age or membership status');
  PERFORM pg_temp.mt_assert(public.home_get_user_permissions(h,u)=ARRAY['home.view','tasks.edit','tasks.view']::text[],
    'Ordinary admission granted permissions outside the intended defaults');
  PERFORM pg_temp.mt_assert(NOT EXISTS(SELECT FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=u),
    'Ordinary admission invented custom grants');
  PERFORM pg_temp.mt_assert(NOT EXISTS(SELECT FROM public."HomeResidencyClaim" WHERE home_id=h AND user_id=u)
    AND NOT EXISTS(SELECT FROM public."HomeOwnershipClaim" WHERE home_id=h AND claimant_user_id=u)
    AND NOT EXISTS(SELECT FROM public."HomeOwner" WHERE home_id=h AND subject_id=u),'Household admission invented residency or ownership proof');
 END LOOP;
 original:='{"title":"Ordinary household Task","description":"Members audience"}'::jsonb;
 r:=pg_temp.mt_ok(public.create_home_task_with_receipt(h,a,request_id,original));t:=(r->'record'->>'id')::uuid;
 PERFORM pg_temp.mt_assert(r->'record'->>'visibility'='members' AND r->'record'->>'created_by'=a::text,'Wrong default audience or author');
 before_rows:=pg_temp.mt_state(h);
 r:=pg_temp.mt_ok(public.create_home_task_with_receipt(h,a,request_id,original));
 PERFORM pg_temp.mt_assert(r->>'replayed'='true' AND r->'record'->>'id'=t::text AND pg_temp.mt_state(h)=before_rows,'Exact retry mutated Task history');
 PERFORM pg_temp.mt_code(public.create_home_task_with_receipt(h,a,request_id,'{"title":"Different original"}'),'HOME_TASK_CREATE_CONFLICT');
 r:=pg_temp.mt_ok(public.get_home_records(h,b,'task',t));
 PERFORM pg_temp.mt_assert(r->'records'->0->'capabilities'->>'can_edit'='false'
   AND r->'records'->0->'capabilities'->>'can_complete'='false','Member can edit another unassigned Task');
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,b,'task','update',t,'{"title":"Other author edit"}'),'HOME_RECORD_WRITE_DENIED');
 PERFORM pg_temp.mt_assert(pg_temp.mt_state(h)=before_rows,'Denied edit mutated Task or history');
 PERFORM pg_temp.mt_ok(public.mutate_home_record(h,a,'task','update',t,jsonb_build_object('description','Edited by creator','assigned_to',b)));
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,b,'task','update',t,'{"title":"Assignee content edit"}'),'HOME_RECORD_WRITE_DENIED');
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,b,'task','update',t,'{"status":"canceled"}'),'HOME_RECORD_WRITE_DENIED');
 r:=pg_temp.mt_ok(public.mutate_home_record(h,b,'task','update',t,'{"status":"done"}'));
 PERFORM pg_temp.mt_assert(r->'record'->>'status'='done' AND r->'record'->>'completed_at' IS NOT NULL,'Assigned member cannot complete Task');
 -- Added read defaults reveal permitted household records, never restricted
 -- manager/sensitive records or another person's source Mail.
 FOREACH state IN ARRAY ARRAY['managers','sensitive'] LOOP
  r:=pg_temp.mt_ok(public.mutate_home_record(h,o,'task','create',NULL,jsonb_build_object('title','Restricted existing Task','visibility',state)));
  hidden:=(r->'record'->>'id')::uuid;
  PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task',hidden),'HOME_RECORD_NOT_FOUND');
 END LOOP;
 INSERT INTO public."Mail"(recipient_user_id,type,content,subject) VALUES(o,'letter','Synthetic personal content','Personal source') RETURNING id INTO mail;
 r:=pg_temp.mt_ok(public.mutate_home_record(h,o,'task','create',NULL,'{"title":"Personal source Task"}',mail));hidden:=(r->'record'->>'id')::uuid;
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task',hidden),'HOME_RECORD_NOT_FOUND');
 PERFORM pg_temp.mt_code(public.get_home_records(h,pg_temp.mt_id(10),'task',t),'HOME_RECORD_DENIED');
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,a,'task','create',NULL,'{"title":"Manager audience","visibility":"managers"}'),'HOME_RECORD_DENIED');
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,a,'task','create',NULL,'{"title":"Sensitive audience","visibility":"sensitive"}'),'HOME_RECORD_DENIED');
 -- Each explicit deny independently preserves its actual access consequence.
 before_rows:=pg_temp.mt_state(h);
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,a,'tasks.view',false);
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 PERFORM pg_temp.mt_code(public.create_home_task_with_receipt(h,a,request_id,original),'HOME_RECORD_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=a AND permission='tasks.view';
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,a,'tasks.edit',false);
 r:=pg_temp.mt_ok(public.get_home_records(h,a,'task'));PERFORM pg_temp.mt_assert(r->>'can_create'='false','Edit deny leaves creation enabled');
 PERFORM pg_temp.mt_code(public.create_home_task_with_receipt(h,a,request_id,original),'HOME_RECORD_WRITE_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=a AND permission='tasks.edit';
 PERFORM pg_temp.mt_assert(pg_temp.mt_state(h)=before_rows,'Denied recovery rewrote original Task history');
 PERFORM pg_temp.mt_ok(public.create_home_task_with_receipt(h,a,request_id,original));
 -- home.view is an independent overview permission, not a master Tasks grant.
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,a,'home.view',false);
 PERFORM pg_temp.mt_assert(NOT public.home_has_permission(h,'home.view',a),'Overview deny lost');
 PERFORM pg_temp.mt_ok(public.get_home_records(h,a,'task',t));
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=a AND permission='home.view';
 FOREACH state IN ARRAY ARRAY['pending_doc','provisional_bootstrap','revoked','suspended','moved_out'] LOOP
  UPDATE public."HomeOccupancy" SET verification_status=state WHERE home_id=h AND user_id=a;
  PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 END LOOP;
 UPDATE public."HomeOccupancy" SET verification_status='verified',is_active=false WHERE home_id=h AND user_id=a;
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 UPDATE public."HomeOccupancy" SET is_active=true,access_start_at=now()+interval '1 day' WHERE home_id=h AND user_id=a;
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 UPDATE public."HomeOccupancy" SET access_start_at=NULL,access_end_at=now()-interval '1 second' WHERE home_id=h AND user_id=a;
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 UPDATE public."HomeOccupancy" SET access_end_at=NULL WHERE home_id=h AND user_id=a;
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 PERFORM pg_temp.mt_code(public.get_home_records(h,a,'task'),'HOME_RECORD_DENIED');
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 PERFORM pg_temp.mt_ok(public.get_home_records(h,a,'task',t));
 -- Historical recorded member+child uses member defaults then the age ceiling;
 -- new child admission must still request the allowed canonical child role.
 r:=public.home_effective_access(h,pg_temp.mt_id(4));
 PERFORM pg_temp.mt_assert(r->>'role_base'='member' AND r->>'effective_role_base'='restricted_member'
  AND r->'permissions' ? 'tasks.view' AND NOT r->'permissions' ? 'tasks.edit','Historical child lookup or hard ceiling changed');
 PERFORM pg_temp.mt_code(public.mutate_home_record(h,pg_temp.mt_id(4),'task','create',NULL,'{"title":"Child write"}'),'HOME_RECORD_WRITE_DENIED');
 PERFORM pg_temp.mt_assert(public.home_has_permission(h,'tasks.edit',pg_temp.mt_id(5)),'Existing teen lost allowed Task edit');
 PERFORM pg_temp.mt_code(public.write_home_invitation(h,o,'create',jsonb_build_object('user_id',pg_temp.mt_id(6),'relationship','member'),repeat('6',64)),'PROPOSED_ROLE_FORBIDDEN');
 r:=pg_temp.mt_ok(public.write_home_invitation(h,o,'create',jsonb_build_object('user_id',pg_temp.mt_id(6),'relationship','restricted_member'),repeat('6',64)));
 PERFORM pg_temp.mt_ok(public.act_on_home_invitation((r->'invitation'->>'id')::uuid,NULL,pg_temp.mt_id(6),'accept'));
 PERFORM pg_temp.mt_assert(public.home_get_user_permissions(h,pg_temp.mt_id(6))=ARRAY['home.view']::text[],'Canonical child admission gained member defaults');
 PERFORM pg_temp.mt_code(public.get_home_task_gig_publication(h,a,t),'HOME_RECORD_WRITE_DENIED');
 -- Prepared hashes bind saved invitation terms. Global role changes do not
 -- rewrite the original or hash; non-null policy rejects, null compatibility
 -- retains its existing behavior, and live accepted-member rights change.
 r:=pg_temp.mt_ok(public.write_home_invitation(h,o,'create',jsonb_build_object('user_id',pg_temp.mt_id(7),'relationship','member'),repeat('7',64)));
 nonnull_id:=(r->'invitation'->>'id')::uuid;reviewed:=pg_temp.mt_ok(public.prepare_home_invitation_decision(pg_temp.mt_id(7),repeat('7',64)));
 r:=pg_temp.mt_ok(public.write_home_invitation(h,o,'create',jsonb_build_object('user_id',pg_temp.mt_id(8),'relationship','member'),repeat('8',64)));
 legacy_id:=(r->'invitation'->>'id')::uuid;UPDATE public."HomeInvite" SET admission_policy=NULL WHERE id=legacy_id;
 reviewed_legacy:=pg_temp.mt_ok(public.prepare_home_invitation_decision(pg_temp.mt_id(8),repeat('8',64)));
 SELECT jsonb_agg(to_jsonb(invite_row) ORDER BY id) INTO stored_invites FROM public."HomeInvite"invite_row WHERE id IN(nonnull_id,legacy_id);
 policy_before:=public.home_invite_policy('member',NULL);
 UPDATE public."HomeRolePermission" SET allowed=false WHERE role_base='member' AND permission='tasks.edit';
 PERFORM pg_temp.mt_assert(public.home_invite_policy('member',NULL)<>policy_before AND NOT public.home_has_permission(h,'tasks.edit',a),'Global defaults failed to change live policy');
 PERFORM pg_temp.mt_assert((public.prepare_home_invitation_decision(pg_temp.mt_id(7),repeat('7',64)))->>'decision_token'=reviewed->>'decision_token'
  AND (public.prepare_home_invitation_decision(pg_temp.mt_id(8),repeat('8',64)))->>'decision_token'=reviewed_legacy->>'decision_token','Global default edit rewrote prepared original hash');
 PERFORM pg_temp.mt_assert((SELECT jsonb_agg(to_jsonb(invite_row) ORDER BY id) FROM public."HomeInvite"invite_row WHERE id IN(nonnull_id,legacy_id))=stored_invites,'Global default edit rewrote stored invitation terms');
 PERFORM pg_temp.mt_code(public.act_on_home_invitation(nonnull_id,NULL,pg_temp.mt_id(7),'accept'),'INVITE_POLICY_CHANGED');
 PERFORM pg_temp.mt_ok(public.act_on_home_invitation(legacy_id,NULL,pg_temp.mt_id(8),'accept'));
 PERFORM pg_temp.mt_assert(NOT public.home_has_permission(h,'tasks.edit',pg_temp.mt_id(8))
  AND (SELECT admission_policy IS NULL FROM public."HomeInvite" WHERE id=legacy_id),'Legacy null policy changed semantics or snapshot');
 UPDATE public."HomeRolePermission" SET allowed=true WHERE role_base='member' AND permission='tasks.edit';
 PERFORM pg_temp.mt_assert(public.home_has_permission(h,'tasks.edit',a) AND public.home_has_permission(h,'tasks.edit',pg_temp.mt_id(8)),'Live defaults failed to recover existing members');
 -- The former setup-only creator audience is not a permanent personal-private
 -- Task type. Existing members visibility becomes household-readable when
 -- that exact Home establishes current shared membership.
 r:=pg_temp.mt_ok(public.mutate_home_record(ph,priv,'task','create',NULL,'{"title":"Created in private setup"}'));other_task:=(r->'record'->>'id')::uuid;
 PERFORM pg_temp.mt_code(public.get_home_records(ph,a,'task',other_task),'HOME_RECORD_DENIED');
 UPDATE public."HomeOccupancy" SET role='member',role_base='member',verification_status='verified' WHERE home_id=ph AND user_id=priv;
 INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,verification_status) VALUES(ph,a,'member','member','verified');
 PERFORM pg_temp.mt_assert(public.home_record_context(ph,a)->>'private'='false','Established member stayed private setup');
 PERFORM pg_temp.mt_ok(public.get_home_records(ph,a,'task',other_task));
 PERFORM pg_temp.mt_assert((SELECT jsonb_agg(to_jsonb(rp) ORDER BY role_base,permission) FROM public."HomeRolePermission"rp)
  =(SELECT rows FROM member_task_roles_before),'Tests changed installed role defaults');
END $$;
RESET ROLE;
SELECT 'PASS: ordinary member Tasks, exact recovery, own/assigned authority, visibility/Mail privacy, denies, ages and immutable invitation policy' AS result;

$contract$, 'home-member-task-defaults.sql');
SELECT * FROM finish();
ROLLBACK;
