-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-external-sharing.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Real role/ACL, exact external DTO, quota, provenance and receipt contracts.
-- All accounts, grants and storage metadata below are synthetic and rolled back.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
CREATE TEMP TABLE sharing_roles_before AS SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) rows
  FROM public."HomeRolePermission" r;
INSERT INTO auth.users(id,email) SELECT ('ddf00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  'sharing-'||n||'@example.invalid' FROM generate_series(1,6)n;
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'sharing_fixture_'||right(id::text,1),'Sharing fixture'
  FROM auth.users WHERE id::text LIKE 'ddf00000-0000-4000-8000-%';
INSERT INTO public."Home"(id,owner_id,created_by_user_id,address,city,state,zipcode,name,parking_instructions) VALUES
 ('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000001','ddf00000-0000-4000-8000-000000000001','Sharing 100','Test','WA','98607','Shared Home','Driveway'),
 ('ddf00000-0000-4000-8000-000000000200','ddf00000-0000-4000-8000-000000000001','ddf00000-0000-4000-8000-000000000001','Sharing 200','Test','WA','98607','Other Home',NULL),
 ('ddf00000-0000-4000-8000-000000000300',NULL,'ddf00000-0000-4000-8000-000000000006','Sharing 300','Test','WA','98607','Private setup',NULL);
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status)
 SELECT 'ddf00000-0000-4000-8000-000000000100',('ddf00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  role,role::public.home_role_base,age::public.home_age_band,'verified'
 FROM (VALUES(1,'owner','adult'),(2,'admin','adult'),(4,'member','adult'),(5,'restricted_member','child')) f(n,role,age);
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,verification_status) VALUES
 ('ddf00000-0000-4000-8000-000000000200','ddf00000-0000-4000-8000-000000000001','owner','owner','verified'),
 ('ddf00000-0000-4000-8000-000000000300','ddf00000-0000-4000-8000-000000000006','admin','admin','pending_doc');
INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES
 ('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000002','members.manage',true),
 ('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000002','home.edit',true),
 ('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000002','home.view',true),
 ('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000002','access.view_wifi',false);
INSERT INTO public."HomeAccessSecret"(id,home_id,created_by,access_type,label,secret_value,visibility)
 SELECT ('ddf00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  'ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000001','wifi',label,'',visibility::public.home_record_visibility
 FROM (VALUES(401,'Shared network','members'),(402,'Sensitive network','sensitive'),(403,'Manager network','managers')) f(n,label,visibility);
INSERT INTO public."HomeAccessSecretValue"(access_secret_id,secret_value)
 SELECT id,'fixture-wifi-'||label FROM public."HomeAccessSecret" WHERE home_id='ddf00000-0000-4000-8000-000000000100';
INSERT INTO public."HomeTask"(id,home_id,created_by,title,task_type,visibility,details)
 SELECT ('ddf00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  ('ddf00000-0000-4000-8000-'||lpad(h::text,12,'0'))::uuid,'ddf00000-0000-4000-8000-000000000001',
  'Exact task '||n,'chore',v::public.home_record_visibility,'{"private_detail":"fixture-never-share"}'
 FROM (VALUES(501,100,'members'),(502,100,'sensitive'),(503,200,'members')) f(n,h,v);
INSERT INTO public."File"(id,home_id,user_id,filename,original_filename,file_path,file_url,file_size,mime_type,file_extension,file_type,metadata)
 VALUES('ddf00000-0000-4000-8000-000000000601','ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000001',
 'shared.pdf','shared.pdf','ddf00000-0000-4000-8000-000000000100/ddf00000-0000-4000-8000-000000000601/'||repeat('b',64),
 '/synthetic-private',4,'application/pdf','.pdf','home_document',jsonb_build_object('storage_contract','home_document_v1',
 'upload_fingerprint',repeat('a',64),'upload_sha256',repeat('b',64),'storage_bucket','sharing-private-fixture'));
INSERT INTO public."HomeDocument"(id,file_id,home_id,created_by,title,doc_type,storage_bucket,storage_path,mime_type,details)
 VALUES('ddf00000-0000-4000-8000-000000000601','ddf00000-0000-4000-8000-000000000601','ddf00000-0000-4000-8000-000000000100',
 'ddf00000-0000-4000-8000-000000000001','Exact document','manual','sharing-private-fixture','must-not-escape','application/pdf',
 jsonb_build_object('storage_contract','home_document_v1','upload_fingerprint',repeat('a',64),'upload_sha256',repeat('b',64)));
CREATE FUNCTION pg_temp.expect_share(r jsonb,c text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'false' OR r->>'code' IS DISTINCT FROM c THEN RAISE EXCEPTION 'Expected %, got %',c,r; END IF;
END $$;
CREATE TEMP TABLE share_fixture_ids(name text,id uuid);
GRANT ALL ON share_fixture_ids TO service_role;
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf00000-0000-4000-8000-000000000100'; o uuid:='ddf00000-0000-4000-8000-000000000001';
 a uuid:='ddf00000-0000-4000-8000-000000000002'; recipient uuid:='ddf00000-0000-4000-8000-000000000003';
 child_id uuid:='ddf00000-0000-4000-8000-000000000005'; r jsonb; p jsonb; sid uuid; before_count integer; state text;
BEGIN
 p:=jsonb_build_object('label','Guest test','included_sections',jsonb_build_array('wifi','parking'),'token_hash',repeat('1',64));
 PERFORM pg_temp.expect_share(public.mutate_home_external_share(h,a,'guest','create',NULL,p),'SHARE_RESOURCE_DENIED');
 PERFORM pg_temp.expect_share(public.mutate_home_external_share(h,recipient,'guest','create',NULL,p),'SHARE_DENIED');
 PERFORM pg_temp.expect_share(public.mutate_home_external_share('ddf00000-0000-4000-8000-000000000300',
  'ddf00000-0000-4000-8000-000000000006','guest','create',NULL,p),'SHARE_DENIED');
 r:=public.mutate_home_external_share(h,o,'guest','create',NULL,p);
 IF r->>'ok' IS DISTINCT FROM 'true' OR r->'record' ?| ARRAY['token_hash','passcode_hash','resource_bindings'] THEN RAISE EXCEPTION 'Guest creation DTO failed'; END IF;
 sid:=(r->'record'->>'id')::uuid; INSERT INTO share_fixture_ids VALUES('guest',sid);
 r:=public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64));
 IF r->'view'->'sections'->'wifi'->>'password' IS DISTINCT FROM 'fixture-wifi-Shared network'
   OR r->'view'->'sections'->>'parking' IS DISTINCT FROM 'Driveway' THEN RAISE EXCEPTION 'Exact guest WiFi read failed'; END IF;
 IF r::text LIKE '%Sensitive network%' OR r::text LIKE '%Manager network%' THEN RAISE EXCEPTION 'Restricted network escaped'; END IF;
 INSERT INTO public."HomeAccessSecret"(home_id,created_by,access_type,label,secret_value)
  VALUES(h,o,'wifi','Added after issuance','');
 r:=public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64));
 IF jsonb_typeof(r->'view'->'sections'->'wifi')<>'object' OR r::text LIKE '%Added after issuance%' THEN RAISE EXCEPTION 'Old guest grant silently expanded'; END IF;
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),child_id,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 SELECT view_count INTO before_count FROM public."HomeGuestPass" WHERE id=sid;
 FOREACH state IN ARRAY ARRAY['pending_doc','revoked','suspended'] LOOP
  UPDATE public."HomeOccupancy" SET verification_status=state WHERE home_id=h AND user_id=o;
  PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_DENIED');
 END LOOP;
 UPDATE public."HomeOccupancy" SET verification_status='verified',access_end_at=clock_timestamp()-interval '1 second' WHERE home_id=h AND user_id=o;
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_DENIED');
 UPDATE public."HomeOccupancy" SET access_end_at=NULL WHERE home_id=h AND user_id=o;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,o,'access.view_wifi',false);
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=o;
 UPDATE public."HomeAccessSecret" SET visibility='sensitive' WHERE id='ddf00000-0000-4000-8000-000000000401';
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 UPDATE public."HomeAccessSecret" SET visibility='members' WHERE id='ddf00000-0000-4000-8000-000000000401';
 UPDATE public."Home" SET lockdown_enabled=true WHERE id=h;
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_DENIED');
 UPDATE public."Home" SET lockdown_enabled=false WHERE id=h;
 IF (SELECT view_count FROM public."HomeGuestPass" WHERE id=sid)<>before_count THEN RAISE EXCEPTION 'Denied guest reads consumed views'; END IF;
 -- The exact exited issuer can revoke, without regaining read access or current metadata.
 UPDATE public."HomeOccupancy" SET is_active=false WHERE home_id=h AND user_id=o;
 r:=public.mutate_home_external_share(h,o,'guest','revoke',sid);
 IF r->>'ok' IS DISTINCT FROM 'true' OR r->'record'->>'label' IS DISTINCT FROM '' THEN RAISE EXCEPTION 'Exited issuer revoke failed or leaked metadata'; END IF;
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('1',64),NULL,NULL,repeat('f',64)),'SHARE_REVOKED');
 UPDATE public."HomeOccupancy" SET is_active=true WHERE home_id=h AND user_id=o;
 SELECT count(*) INTO before_count FROM public."HomeAuditLog" WHERE home_id=h;
 r:=public.mutate_home_external_share(h,o,'guest','revoke',sid);
 IF r->>'replayed' IS DISTINCT FROM 'true' OR (SELECT count(*) FROM public."HomeAuditLog" WHERE home_id=h)<>before_count THEN RAISE EXCEPTION 'Revoke retry duplicated audit'; END IF;
 -- Legacy grants cannot be silently adopted into a formerly unvalidated scope.
 INSERT INTO public."HomeGuestPass"(home_id,label,token_hash,created_by,end_at) VALUES(h,'Legacy',repeat('0',64),o,now()+interval '1 day');
 PERFORM pg_temp.expect_share(public.read_home_external_share('guest',repeat('0',64),NULL,NULL,repeat('f',64)),'SHARE_REISSUE_REQUIRED');
 FOR p IN SELECT value FROM jsonb_array_elements('[{"max_views":0},{"duration_hours":-1},{"duration_hours":9000},{"included_sections":["unknown"]},{"can_edit":true},{"can_upload":true},{"permissions":{"ownership.manage":true}}]'::jsonb) LOOP
  PERFORM pg_temp.expect_share(public.mutate_home_external_share(h,o,'guest','create',NULL,
    jsonb_build_object('label','Invalid','included_sections',jsonb_build_array('parking'),'token_hash',repeat('9',64))||p),'SHARE_INVALID');
 END LOOP;
END $$;

DO $$ DECLARE h uuid:='ddf00000-0000-4000-8000-000000000100'; o uuid:='ddf00000-0000-4000-8000-000000000001';
 recipient uuid:='ddf00000-0000-4000-8000-000000000003'; member_id uuid:='ddf00000-0000-4000-8000-000000000004';
 p jsonb; r jsonb; sid uuid; doc uuid:='ddf00000-0000-4000-8000-000000000601';
BEGIN
 p:=jsonb_build_object('resource_type','HomeTask','resource_id','ddf00000-0000-4000-8000-000000000501',
  'grantee_user_id',recipient,'token_hash',repeat('3',64));
 PERFORM pg_temp.expect_share(public.mutate_home_external_share(h,o,'scoped','create',NULL,
  p||'{"resource_id":"ddf00000-0000-4000-8000-000000000503"}'),'SHARE_RESOURCE_DENIED');
 PERFORM pg_temp.expect_share(public.mutate_home_external_share(h,o,'scoped','create',NULL,
  p||'{"resource_id":"ddf00000-0000-4000-8000-000000000502"}'),'SHARE_RESOURCE_DENIED');
 r:=public.mutate_home_external_share(h,o,'scoped','create',NULL,p); sid:=(r->'record'->>'id')::uuid;
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Named grant creation failed'; END IF;
 INSERT INTO share_fixture_ids VALUES('named',sid);
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),NULL,NULL,repeat('f',64)),'SHARE_DENIED');
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),member_id,NULL,repeat('f',64)),'SHARE_DENIED');
 r:=public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64));
 IF r->'view'->'resource'->>'title' IS DISTINCT FROM 'Exact task 501'
   OR r->'view'->'resource' ?| ARRAY['details','created_by','viewer_user_ids','home_id','mail_id','budget','linked_gig_id'] THEN RAISE EXCEPTION 'Exact named DTO failed'; END IF;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,recipient,'tasks.view',false);
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=recipient;
 INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,verification_status)
  VALUES(h,recipient,'member','member',NULL);
  PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 UPDATE public."HomeOccupancy" SET verification_status='verified',role=NULL,role_base=NULL
  WHERE home_id=h AND user_id=recipient;
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64)),'SHARE_RESOURCE_DENIED');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=recipient;
 UPDATE public."HomeScopedGrant" SET start_at=clock_timestamp()+interval '1 hour' WHERE id=sid;
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64)),'SHARE_NOT_STARTED');
 UPDATE public."HomeScopedGrant" SET start_at=clock_timestamp()-interval '1 hour',can_view=false WHERE id=sid;
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('3',64),recipient,NULL,repeat('f',64)),'SHARE_DENIED');
 UPDATE public."HomeScopedGrant" SET can_view=true WHERE id=sid;
 -- One page view admits an exact short-lived document receipt. Download
 -- authorization must remain usable when that one view exhausted the quota.
 p:=jsonb_build_object('resource_type','HomeDocument','resource_id',doc,'token_hash',repeat('4',64),
   'max_views',1,'passcode_hash',repeat('a',64));
 r:=public.mutate_home_external_share(h,o,'scoped','create',NULL,p);
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Document grant failed'; END IF;
 sid:=(r->'record'->>'id')::uuid; INSERT INTO share_fixture_ids VALUES('document',sid);
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('4',64),NULL,NULL,repeat('5',64)),'SHARE_PASSCODE_REQUIRED');
 r:=public.read_home_external_share('scoped',repeat('4',64),NULL,repeat('a',64),repeat('5',64));
 IF r->'view'->'resource'->>'id' IS DISTINCT FROM doc::text OR NOT r->'view'->'resource' ? '_document'
  OR r->'view'->'resource' ?| ARRAY['storage_path','storage_bucket','details'] THEN RAISE EXCEPTION 'Document receipt metadata failed'; END IF;
 r:=public.authorize_home_share_document(repeat('5',64),doc);
 IF r->>'ok' IS DISTINCT FROM 'true' OR r->'document'->'_document'->>'sha256' IS DISTINCT FROM repeat('b',64) THEN RAISE EXCEPTION 'One-view receipt unavailable'; END IF;
 PERFORM pg_temp.expect_share(public.read_home_external_share('scoped',repeat('4',64),NULL,repeat('a',64),repeat('6',64)),'SHARE_VIEW_LIMIT');
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('5',64),'ddf00000-0000-4000-8000-000000000699'),'SHARE_DENIED');
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('5',64),doc,recipient),'SHARE_DENIED');
 UPDATE public."HomeShareReadReceipt" SET expires_at=clock_timestamp()-interval '1 second' WHERE receipt_hash=repeat('5',64);
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('5',64),doc),'SHARE_DENIED');
 UPDATE public."HomeShareReadReceipt" SET expires_at=clock_timestamp()+interval '1 minute' WHERE receipt_hash=repeat('5',64);
 UPDATE public."HomeDocument" SET visibility='sensitive' WHERE id=doc;
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('5',64),doc),'SHARE_RESOURCE_DENIED');
 UPDATE public."HomeDocument" SET visibility='members' WHERE id=doc;
 PERFORM public.mutate_home_external_share(h,o,'scoped','revoke',sid);
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('5',64),doc),'SHARE_REVOKED');
 -- A receipt spends no extra page view, but each exact document can be
 -- delivered once only, at the final authorization after the byte fetch.
 r:=public.mutate_home_external_share(h,o,'scoped','create',NULL,p||jsonb_build_object('token_hash',repeat('8',64)));
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Single-use receipt fixture failed'; END IF;
 sid:=(r->'record'->>'id')::uuid;
 r:=public.read_home_external_share('scoped',repeat('8',64),NULL,repeat('a',64),repeat('8',64));
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Single-use receipt view failed'; END IF;
 r:=public.authorize_home_share_document(repeat('8',64),doc,NULL,true);
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'First final receipt authorization failed'; END IF;
 PERFORM pg_temp.expect_share(public.authorize_home_share_document(repeat('8',64),doc,NULL,true),'SHARE_DENIED');
 IF (SELECT view_count FROM public."HomeScopedGrant" WHERE id=sid)<>1 THEN RAISE EXCEPTION 'Download spent an extra view'; END IF;
END $$;
RESET ROLE;

-- An orphaned retained receipt must never turn an established setup into a
-- deletable private bootstrap after its original share has been removed.
DO $$ DECLARE h uuid:='ddf00000-0000-4000-8000-000000000300';
 u uuid:='ddf00000-0000-4000-8000-000000000006'; r jsonb;
BEGIN
 r:=public.home_delete_eligibility(h,u);
 IF r->>'allowed' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Private receipt fixture not eligible initially'; END IF;
 INSERT INTO public."HomeShareReadReceipt"(receipt_hash,home_id,share_kind,share_id,document_ids,expires_at)
  VALUES(repeat('c',64),h,'guest','ddf00000-0000-4000-8000-000000000999','{}',clock_timestamp()+interval '1 minute');
 r:=public.home_delete_eligibility(h,u);
 IF r->>'code' IS DISTINCT FROM 'HOME_DELETE_ESTABLISHED_HOUSEHOLD' OR r->>'allowed' IS DISTINCT FROM 'false' THEN
  RAISE EXCEPTION 'Private deletion ignored retained sharing history'; END IF;
 DELETE FROM public."HomeShareReadReceipt" WHERE receipt_hash=repeat('c',64);
END $$;

-- Downstream audit/view/receipt failures roll back the complete operation.
CREATE FUNCTION pg_temp.fail_external_share() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 RAISE EXCEPTION 'Synthetic sharing downstream failure' USING ERRCODE='P0994'; END $$;
CREATE TRIGGER sharing_audit_failure BEFORE INSERT ON public."HomeAuditLog"
 FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_external_share();
DO $$ DECLARE before_passes bigint; before_grants bigint; h uuid:='ddf00000-0000-4000-8000-000000000100';
 o uuid:='ddf00000-0000-4000-8000-000000000001'; kind text; p jsonb;
BEGIN
 SELECT count(*) INTO before_passes FROM public."HomeGuestPass" WHERE home_id=h;
 SELECT count(*) INTO before_grants FROM public."HomeScopedGrant" WHERE home_id=h;
 FOREACH kind IN ARRAY ARRAY['guest','scoped'] LOOP
  p:=CASE kind WHEN 'guest' THEN jsonb_build_object('label','Rollback','included_sections',jsonb_build_array('parking'),'token_hash',repeat('9',64))
    ELSE jsonb_build_object('resource_type','HomeTask','resource_id','ddf00000-0000-4000-8000-000000000501','token_hash',repeat('9',64)) END;
  BEGIN
   PERFORM public.mutate_home_external_share(h,o,kind,'create',NULL,p);
   RAISE EXCEPTION 'Missing sharing audit failure';
  EXCEPTION WHEN SQLSTATE 'P0994' THEN NULL; END;
 END LOOP;
 IF (SELECT count(*) FROM public."HomeGuestPass" WHERE home_id=h)<>before_passes
  OR (SELECT count(*) FROM public."HomeScopedGrant" WHERE home_id=h)<>before_grants THEN RAISE EXCEPTION 'Audit failure left a live share'; END IF;
END $$;
DROP TRIGGER sharing_audit_failure ON public."HomeAuditLog";
DO $$ DECLARE r jsonb; BEGIN
 r:=public.mutate_home_external_share('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000001','guest','create',NULL,
  jsonb_build_object('label','View rollback','included_sections',jsonb_build_array('parking'),'token_hash',repeat('9',64),'max_views',1));
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'View rollback fixture failed'; END IF;
 r:=public.mutate_home_external_share('ddf00000-0000-4000-8000-000000000100','ddf00000-0000-4000-8000-000000000001','scoped','create',NULL,
  jsonb_build_object('resource_type','HomeDocument','resource_id','ddf00000-0000-4000-8000-000000000601','token_hash',repeat('6',64),'max_views',1));
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Receipt rollback fixture failed'; END IF;
END $$;
CREATE TRIGGER sharing_view_failure BEFORE INSERT ON public."HomeGuestPassView"
 FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_external_share();
CREATE TRIGGER sharing_receipt_failure BEFORE INSERT ON public."HomeShareReadReceipt"
 FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_external_share();
DO $$ BEGIN
 BEGIN
  PERFORM public.read_home_external_share('guest',repeat('9',64),NULL,NULL,repeat('7',64));
  RAISE EXCEPTION 'Missing guest view failure';
 EXCEPTION WHEN SQLSTATE 'P0994' THEN NULL; END;
 BEGIN
  PERFORM public.read_home_external_share('scoped',repeat('6',64),NULL,NULL,repeat('7',64));
  RAISE EXCEPTION 'Missing receipt failure';
 EXCEPTION WHEN SQLSTATE 'P0994' THEN NULL; END;
 IF EXISTS(SELECT FROM public."HomeGuestPass" WHERE token_hash=repeat('9',64) AND view_count<>0)
  OR EXISTS(SELECT FROM public."HomeScopedGrant" WHERE token_hash=repeat('6',64) AND view_count<>0)
  OR EXISTS(SELECT FROM public."HomeShareReadReceipt" WHERE receipt_hash=repeat('7',64)) THEN RAISE EXCEPTION 'Downstream failure consumed a view/receipt'; END IF;
END $$;
DROP TRIGGER sharing_view_failure ON public."HomeGuestPassView";
DROP TRIGGER sharing_receipt_failure ON public."HomeShareReadReceipt";

SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ddf00000-0000-4000-8000-000000000003',true);
DO $$ BEGIN
 IF public.home_has_scoped_grant('ddf00000-0000-4000-8000-000000000100','HomeTask','ddf00000-0000-4000-8000-000000000501','view')
  OR EXISTS(SELECT FROM public."HomeTask" WHERE id='ddf00000-0000-4000-8000-000000000501') THEN
  RAISE EXCEPTION 'Named token grant exposed raw task rows through legacy RLS'; END IF;
END $$;
RESET ROLE;
DO $$ DECLARE t text; op text; BEGIN
 FOREACH t IN ARRAY ARRAY['HomeGuestPass','HomeGuestPassView','HomeScopedGrant','HomeShareReadReceipt'] LOOP
  FOREACH op IN ARRAY ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] LOOP
   IF has_table_privilege('authenticated',format('public.%I',t),op) OR has_table_privilege('anon',format('public.%I',t),op) THEN
    RAISE EXCEPTION 'Client retains % on %',op,t; END IF;
  END LOOP;
 END LOOP;
 IF has_function_privilege('authenticated','public.read_home_external_share(text,text,uuid,text,text)','EXECUTE')
  OR has_function_privilege('anon','public.authorize_home_share_document(text,uuid,uuid,boolean)','EXECUTE') THEN RAISE EXCEPTION 'Public can impersonate share recipient'; END IF;
 IF (SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) FROM public."HomeRolePermission" r)
  IS DISTINCT FROM (SELECT rows FROM sharing_roles_before) THEN RAISE EXCEPTION 'Sharing changed ordinary role defaults'; END IF;
END $$;
SELECT 'PASS: exact external DTOs, issuer/recipient ceilings, private setup denial, bounded receipts, revocation and direct ACL/RLS closure' AS result;

$contract$, 'home-external-sharing.sql');
SELECT * FROM finish();
ROLLBACK;
