-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-authority-transactions.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Member authority uses the shipped 29 role rows. Scoped fixture overrides and
-- presets exercise delegation without expanding any global role defaults.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
SET LOCAL search_path = public, extensions, pg_catalog;
CREATE TEMP TABLE authority_reference_before AS
  SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) rows FROM public."HomeRolePermission" r;
DO $$ BEGIN
  IF (SELECT count(*) FROM public."HomeRolePermission")<>29 THEN RAISE EXCEPTION 'Expected shipped role matrix'; END IF;
  IF has_function_privilege('authenticated','public.mutate_home_member(uuid,uuid,uuid,text,jsonb)','EXECUTE')
    OR has_function_privilege('anon','public.mutate_home_member(uuid,uuid,uuid,text,jsonb)','EXECUTE')
    OR NOT has_function_privilege('service_role','public.mutate_home_member(uuid,uuid,uuid,text,jsonb)','EXECUTE')
    OR has_function_privilege('service_role','public.apply_home_role_preset(uuid,uuid,text,timestamptz,timestamptz)','EXECUTE')
    OR has_function_privilege('authenticated','public.apply_home_role_preset(uuid,uuid,text,timestamptz,timestamptz)','EXECUTE') THEN
    RAISE EXCEPTION 'Authority RPC or closed legacy preset privileges are unsafe';
  END IF;
END $$;
INSERT INTO auth.users(id,email)
SELECT ('dda00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  'home-authority-'||n||'@example.invalid' FROM generate_series(1,7) n;
INSERT INTO public."User"(id,email,username,name)
SELECT id,email,'home_authority_'||right(id::text,2),'Home authority fixture'
FROM auth.users WHERE id::text LIKE 'dda00000-0000-4000-8000-%';
INSERT INTO public."Home"(id,owner_id,address,city,state,zipcode)
VALUES('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000001','100 Authority Test','Test','WA','98607');
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,is_active,verification_status,
  start_at,end_at,access_start_at,access_end_at)
SELECT 'dda00000-0000-4000-8000-000000000100',
  ('dda00000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,role,role::public.home_role_base,
  age::public.home_age_band,true,status,now()-interval '1 day',now()+interval '1 day',now()-interval '1 hour',now()+interval '1 hour'
FROM (VALUES (1,'owner','adult','verified'),(2,'admin','adult','verified'),(3,'member','adult','verified'),
  (4,'restricted_member','child','verified'),(5,'member','teen','verified'),(6,'member',NULL,'pending_doc'),
  (7,'admin','adult','verified')) f(n,role,age,status);
INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed)
VALUES('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000002','members.manage',true),
  ('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000002','home.edit',true),
  ('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000003','finance.manage',false),
  ('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000006','finance.manage',false);
INSERT INTO public."HomeRolePreset"(key,display_name,role_base,grant_perms,deny_perms) VALUES
  ('authority-fixture-member','Fixture member','member',ARRAY['home.edit','finance.manage']::public.home_permission[],ARRAY['docs.upload']::public.home_permission[]),
  ('authority-fixture-owner','Fixture owner','owner','{}','{}');
CREATE FUNCTION pg_temp.expect_authority(result jsonb, expected text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF result->>'code' IS DISTINCT FROM expected THEN RAISE EXCEPTION 'Expected %, got %',expected,result; END IF;
END $$;

SET LOCAL ROLE service_role;
DO $$
DECLARE h uuid:='dda00000-0000-4000-8000-000000000100'; owner_id uuid:='dda00000-0000-4000-8000-000000000001';
  admin_id uuid:='dda00000-0000-4000-8000-000000000002'; target uuid:='dda00000-0000-4000-8000-000000000003';
  child_id uuid:='dda00000-0000-4000-8000-000000000004'; teen_id uuid:='dda00000-0000-4000-8000-000000000005';
  pending_id uuid:='dda00000-0000-4000-8000-000000000006'; equal_id uuid:='dda00000-0000-4000-8000-000000000007';
  original public."HomeOccupancy"%ROWTYPE; current_row public."HomeOccupancy"%ROWTYPE; state text; r jsonb;
BEGIN
  SELECT * INTO original FROM public."HomeOccupancy" WHERE home_id=h AND user_id=pending_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,pending_id,'role','{"role_base":"lease_resident"}'),'MEMBER_UPDATED');
  SELECT * INTO current_row FROM public."HomeOccupancy" WHERE home_id=h AND user_id=pending_id;
  IF current_row.age_band IS DISTINCT FROM original.age_band OR current_row.verification_status<>original.verification_status
    OR current_row.is_active<>original.is_active OR current_row.start_at<>original.start_at OR current_row.end_at<>original.end_at
    OR current_row.access_start_at<>original.access_start_at OR current_row.access_end_at<>original.access_end_at
    OR current_row.can_manage_tasks OR public.home_is_active_member(h,pending_id) THEN
    RAISE EXCEPTION 'Role change rewrote pending state, age, windows or gave shared access';
  END IF;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"role_base":"lease_resident"}'),'MEMBER_UPDATED');
  IF NOT public.home_has_permission(h,'tasks.edit',target) OR public.home_has_permission(h,'finance.manage',target) THEN
    RAISE EXCEPTION 'Role default or explicit deny lost';
  END IF;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"preset_key":"authority-fixture-member"}'),'MEMBER_UPDATED');
  IF public.home_has_permission(h,'finance.manage',target) OR NOT public.home_has_permission(h,'home.edit',target)
    OR NOT EXISTS(SELECT FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=target AND permission='docs.upload' AND NOT allowed) THEN
    RAISE EXCEPTION 'Preset erased explicit restriction or did not apply bounded grants/denies';
  END IF;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"end_at":null,"role_base":"member"}'),'ACCESS_WINDOW_CHANGE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"age_band":"adult","role_base":"member"}'),'INVALID_AUTHORITY_REQUEST');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,owner_id,'role','{"role_base":"admin"}'),'OWNERSHIP_OR_SELF_ROLE_CHANGE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"role_base":"owner"}'),'OWNERSHIP_OR_SELF_ROLE_CHANGE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"preset_key":"authority-fixture-owner"}'),'OWNERSHIP_OR_SELF_ROLE_CHANGE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,equal_id,'role','{"role_base":"member"}'),'TARGET_RANK_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,owner_id,'remove'),'TARGET_RANK_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,target,'role','{"role_base":"admin"}'),'PROPOSED_ROLE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,equal_id,'role','{"role_base":"member"}'),'MEMBER_UPDATED');
  IF NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=equal_id AND role_base='member') THEN
    RAISE EXCEPTION 'Owner could not demote an ordinary verified admin';
  END IF;
  UPDATE public."HomeOccupancy" SET role_base='owner',role='owner' WHERE home_id=h AND user_id=child_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,child_id,'role','{"role_base":"guest"}'),'TARGET_RANK_FORBIDDEN');
  UPDATE public."HomeOccupancy" SET role_base=NULL,role=NULL WHERE home_id=h AND user_id=child_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,child_id,'role','{"role_base":"guest"}'),'MEMBER_ROLE_UNKNOWN');
  UPDATE public."HomeOccupancy" SET role_base='restricted_member',role='restricted_member' WHERE home_id=h AND user_id=child_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,child_id,'role','{"role_base":"member"}'),'PROPOSED_ROLE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,teen_id,'role','{"role_base":"lease_resident"}'),'PROPOSED_ROLE_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,child_id,'override','{"permission":"tasks.edit","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,teen_id,'override','{"permission":"finance.manage","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,admin_id,'override','{"permission":"home.edit","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,admin_id,'override','{"permission":"ownership.manage","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  UPDATE public."HomeOccupancy" SET role_base='manager',role='manager' WHERE home_id=h AND user_id=admin_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,admin_id,'override','{"permission":"ownership.transfer","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  UPDATE public."HomeOccupancy" SET role_base='admin',role='admin' WHERE home_id=h AND user_id=admin_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,target,'override','{"permission":"ownership.transfer","allowed":true}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,target,'override','{"permission":"home.edit","allowed":true}'),'MEMBER_UPDATED');
  -- Actor effective deny also fences preset grants even if target already has a
  -- restrictive override; role-only changes compare future potential rights.
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,target,'role','{"preset_key":"authority-fixture-member"}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,admin_id,pending_id,'role','{"role_base":"service_provider"}'),'PERMISSION_DELEGATION_FORBIDDEN');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,owner_id,'override','{"permission":"members.manage","allowed":false}'),'MEMBER_UPDATED');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"role_base":"member"}'),'MEMBERS_MANAGE_REQUIRED');
  DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=owner_id AND permission='members.manage';
  FOREACH state IN ARRAY ARRAY['revoked','disputed'] LOOP
    INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status) VALUES(h,owner_id,state::public.owner_status_type);
    PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'remove'),'MEMBERS_MANAGE_REQUIRED');
    DELETE FROM public."HomeOwner" WHERE home_id=h AND subject_id=owner_id;
  END LOOP;
  INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status) VALUES(h,owner_id,'revoked'),(h,owner_id,'verified');
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"role_base":"member"}'),'MEMBER_UPDATED');
  DELETE FROM public."HomeOwner" WHERE home_id=h AND subject_id=owner_id;
  FOREACH state IN ARRAY ARRAY['revoked','pending_doc','suspended','unknown',NULL] LOOP
    UPDATE public."HomeOccupancy" SET verification_status=state WHERE home_id=h AND user_id=owner_id;
    PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'override','{"permission":"home.edit","allowed":true}'),'MEMBERS_MANAGE_REQUIRED');
  END LOOP;
  UPDATE public."HomeOccupancy" SET verification_status='verified',age_band='child' WHERE home_id=h AND user_id=owner_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'remove'),'MEMBERS_MANAGE_REQUIRED');
  UPDATE public."HomeOccupancy" SET age_band='adult',access_end_at=now() WHERE home_id=h AND user_id=owner_id;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'role','{"role_base":"member"}'),'MEMBERS_MANAGE_REQUIRED');
  UPDATE public."HomeOccupancy" SET access_end_at=now()+interval '1 hour' WHERE home_id=h AND user_id=owner_id;
  UPDATE public."Home" SET security_state='frozen' WHERE id=h;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'remove'),'MEMBERS_MANAGE_REQUIRED');
  UPDATE public."Home" SET security_state='normal' WHERE id=h;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,owner_id,'remove'),'TRANSFER_REQUIRED');
  INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status,is_primary_owner) VALUES(h,owner_id,'verified',true);
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,owner_id,'remove'),'TRANSFER_REQUIRED');
  DELETE FROM public."HomeOwner" WHERE home_id=h AND subject_id=owner_id;
END $$;
RESET ROLE;

-- Failure after writes (the final audit) must roll back the membership,
-- restrictive overrides, scoped access and issued residency credential together.
INSERT INTO public."HomeScopedGrant"(home_id,grantee_user_id,resource_type,resource_id)
VALUES('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000003','HomeTask','dda00000-0000-4000-8000-000000000200');
INSERT INTO public."ResidencyLetter"(home_id,user_id,letter_code,resident_name,address_line1,pdf_sha256,pdf_base64)
VALUES('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000003','authority-fixture','Synthetic','Synthetic','fixture','fixture');
CREATE FUNCTION pg_temp.reject_authority_audit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Synthetic downstream failure' USING ERRCODE='P0991'; END $$;
CREATE TRIGGER authority_contract_failure BEFORE INSERT ON public."HomeAuditLog"
  FOR EACH ROW EXECUTE FUNCTION pg_temp.reject_authority_audit();
SET LOCAL ROLE service_role;
DO $$
DECLARE h uuid:='dda00000-0000-4000-8000-000000000100'; owner_id uuid:='dda00000-0000-4000-8000-000000000001';
  target uuid:='dda00000-0000-4000-8000-000000000003'; action text; payload jsonb; before_row jsonb; before_overrides jsonb;
BEGIN
  SELECT to_jsonb(o) INTO before_row FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=target;
  SELECT jsonb_agg(to_jsonb(o) ORDER BY permission) INTO before_overrides FROM public."HomePermissionOverride" o WHERE home_id=h AND user_id=target;
  FOREACH action IN ARRAY ARRAY['role','override','remove'] LOOP
    payload:=CASE action WHEN 'role' THEN '{"preset_key":"authority-fixture-member"}' WHEN 'override' THEN '{"permission":"finance.manage","allowed":true}' ELSE '{}' END::jsonb;
    BEGIN
      PERFORM public.mutate_home_member(h,owner_id,target,action,payload);
      RAISE EXCEPTION 'Mutation reported success despite injected audit failure';
    EXCEPTION WHEN SQLSTATE 'P0991' THEN NULL; END;
    IF (SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=target) IS DISTINCT FROM before_row
      OR (SELECT jsonb_agg(to_jsonb(o) ORDER BY permission) FROM public."HomePermissionOverride" o WHERE home_id=h AND user_id=target) IS DISTINCT FROM before_overrides
      OR EXISTS(SELECT FROM public."HomeScopedGrant" WHERE home_id=h AND grantee_user_id=target AND end_at IS NOT NULL)
      OR EXISTS(SELECT FROM public."ResidencyLetter" WHERE home_id=h AND user_id=target AND status<>'issued') THEN
      RAISE EXCEPTION 'Partial authority state survived failed % transaction',action;
    END IF;
  END LOOP;
  INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status,is_primary_owner) VALUES(h,owner_id,'revoked',true);
  BEGIN
    PERFORM public.mutate_home_member(h,owner_id,owner_id,'remove');
    RAISE EXCEPTION 'Stale-pointer move-out ignored synthetic audit failure';
  EXCEPTION WHEN SQLSTATE 'P0991' THEN NULL; END;
  IF NOT EXISTS(SELECT FROM public."Home" home_row WHERE home_row.id=h AND home_row.owner_id='dda00000-0000-4000-8000-000000000001'::uuid)
    OR NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=owner_id AND is_active AND verification_status='verified') THEN
    RAISE EXCEPTION 'Stale-pointer move-out failed without restoring pointer and membership';
  END IF;
  DELETE FROM public."HomeOwner" WHERE home_id=h AND subject_id=owner_id;
END $$;
RESET ROLE;
DROP TRIGGER authority_contract_failure ON public."HomeAuditLog";
SET LOCAL ROLE service_role;
DO $$
DECLARE h uuid:='dda00000-0000-4000-8000-000000000100'; owner_id uuid:='dda00000-0000-4000-8000-000000000001';
  target uuid:='dda00000-0000-4000-8000-000000000003';
BEGIN
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,target,'remove'),'MEMBER_UPDATED');
  IF EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=target AND (is_active OR verification_status<>'inactive' OR end_at>clock_timestamp()))
    OR EXISTS(SELECT FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=target)
    OR EXISTS(SELECT FROM public."HomeScopedGrant" WHERE home_id=h AND grantee_user_id=target AND (end_at IS NULL OR end_at>clock_timestamp()))
    OR EXISTS(SELECT FROM public."ResidencyLetter" WHERE home_id=h AND user_id=target AND status<>'revoked') THEN
    RAISE EXCEPTION 'Removal left active membership, overrides, grants or letters';
  END IF;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,target,target,'remove'),'MEMBER_UPDATED');
  IF NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=target AND verification_status='moved_out') THEN
    RAISE EXCEPTION 'Own inactive occupancy could not complete move-out';
  END IF;
  UPDATE public."HomeOccupancy" SET role_base=NULL,role=NULL,is_active=true,verification_status='unknown' WHERE home_id=h AND user_id=target;
  PERFORM pg_temp.expect_authority(public.mutate_home_member(h,target,target,'remove'),'MEMBER_UPDATED');
  IF EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=target AND (is_active OR verification_status<>'moved_out')) THEN
    RAISE EXCEPTION 'Exact user could not leave their malformed legacy occupancy';
  END IF;
END $$;
RESET ROLE;

-- A proven stale legacy pointer is not an obligation to transfer revoked
-- ownership. Its exact subject may leave; pointer and membership clear together.
-- The no-history and current-verified-primary transfer guards were tested above.
SET LOCAL ROLE service_role;
DO $$
DECLARE h uuid:='dda00000-0000-4000-8000-000000000100'; owner_id uuid:='dda00000-0000-4000-8000-000000000001'; state text;
BEGIN
  FOREACH state IN ARRAY ARRAY['revoked','disputed'] LOOP
    INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status,is_primary_owner) VALUES(h,owner_id,state::public.owner_status_type,true);
    PERFORM pg_temp.expect_authority(public.mutate_home_member(h,owner_id,owner_id,'remove'),'MEMBER_UPDATED');
    IF EXISTS(SELECT FROM public."Home" home_row WHERE home_row.id=h AND home_row.owner_id IS NOT NULL)
      OR EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=owner_id AND (is_active OR verification_status<>'moved_out')) THEN
      RAISE EXCEPTION 'Proven stale owner pointer prevented exact selfleave or survived it';
    END IF;
    DELETE FROM public."HomeOwner" WHERE home_id=h AND subject_id=owner_id;
    UPDATE public."Home" SET owner_id='dda00000-0000-4000-8000-000000000001' WHERE id=h;
    UPDATE public."HomeOccupancy" SET is_active=true,verification_status='verified',end_at=now()+interval '1 day' WHERE home_id=h AND user_id=owner_id;
  END LOOP;
END $$;
RESET ROLE;

-- Authenticated direct DML and legacy preset execution cannot bypass the service
-- transaction even for the real primary owner. SELECT remains independently RLS.
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','dda00000-0000-4000-8000-000000000001',true);
DO $$
DECLARE tab text; operation text;
BEGIN
  FOREACH tab IN ARRAY ARRAY['HomeOccupancy','HomeOwner','HomePermissionOverride','HomeScopedGrant','HomeRolePermission','HomeRolePreset'] LOOP
    FOREACH operation IN ARRAY ARRAY['INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] LOOP
      IF has_table_privilege(current_user,format('public.%I',tab),operation) THEN RAISE EXCEPTION 'Direct % remains on %',operation,tab; END IF;
    END LOOP;
    BEGIN EXECUTE format('DELETE FROM public.%I WHERE false',tab);
      RAISE EXCEPTION 'Direct authenticated deletion succeeded on %',tab;
    EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  END LOOP;
  BEGIN UPDATE public."Home" SET owner_id='dda00000-0000-4000-8000-000000000002' WHERE id='dda00000-0000-4000-8000-000000000100';
    RAISE EXCEPTION 'Direct Home owner pointer mutation succeeded';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  BEGIN PERFORM public.apply_home_role_preset('dda00000-0000-4000-8000-000000000100','dda00000-0000-4000-8000-000000000003','authority-fixture-owner');
    RAISE EXCEPTION 'Legacy preset RPC bypassed authority boundary';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
DO $$ BEGIN
  IF (SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) FROM public."HomeRolePermission" r)
    IS DISTINCT FROM (SELECT rows FROM authority_reference_before) THEN RAISE EXCEPTION 'Contract altered shipped role defaults'; END IF;
END $$;
SELECT 'PASS: transactional Home authority, current actor/target ceilings, restrictive preset preservation and rollback' AS result;

$contract$, 'home-authority-transactions.sql');
SELECT * FROM finish();
ROLLBACK;
