-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-lease-decisions.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Exercise the real lease/membership transaction, including failures that the
-- old in-memory occupancy mock could not represent. Fixtures always roll back.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
INSERT INTO auth.users(id,email) SELECT ('f3190000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
  'lease-contract-'||n||'@example.invalid' FROM generate_series(1,6) n;
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'lease_contract_'||right(id::text,2),'Lease contract'
  FROM auth.users WHERE id::text LIKE 'f3190000-0000-4000-8000-%';
INSERT INTO public."Home"(id,address,city,state,zipcode) VALUES
  ('f3190000-0000-4000-8000-000000000010','Lease contract','Test','CA','00000'),
  ('f3190000-0000-4000-8000-000000000011','Other lease contract','Test','CA','00000');
INSERT INTO public."HomeAuthority"(id,home_id,subject_type,subject_id,role,status,added_via) VALUES
  ('f3190000-0000-4000-8000-000000000020','f3190000-0000-4000-8000-000000000010','user','f3190000-0000-4000-8000-000000000001','owner','verified','landlord_portal'),
  ('f3190000-0000-4000-8000-000000000021','f3190000-0000-4000-8000-000000000011','user','f3190000-0000-4000-8000-000000000001','owner','verified','landlord_portal'),
  ('f3190000-0000-4000-8000-000000000022','f3190000-0000-4000-8000-000000000010','business','f3190000-0000-4000-8000-000000000004','manager','verified','landlord_portal'),
  ('f3190000-0000-4000-8000-000000000023','f3190000-0000-4000-8000-000000000010','trust','f3190000-0000-4000-8000-000000000004','manager','verified','landlord_portal');
CREATE FUNCTION pg_temp.check_lease(p_ok boolean,p_label text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN IF p_ok IS DISTINCT FROM true THEN RAISE EXCEPTION '%',p_label; END IF; END $$;
CREATE FUNCTION pg_temp.pending_lease(p_home uuid DEFAULT 'f3190000-0000-4000-8000-000000000010') RETURNS uuid LANGUAGE plpgsql AS $$
DECLARE v_id uuid;
BEGIN
 INSERT INTO public."HomeLease"(home_id,primary_resident_user_id,start_at,end_at,state,source,metadata)
 VALUES(p_home,'f3190000-0000-4000-8000-000000000002',
   now()-interval '1 day',now()+interval '1 year','pending','tenant_request','{"preserved":"yes"}') RETURNING id INTO v_id;
 RETURN v_id;
END $$;
DO $$ BEGIN
 PERFORM pg_temp.check_lease(NOT has_function_privilege('authenticated',
  'public.decide_home_lease(text,uuid,uuid,uuid,text,text,jsonb,text,integer,uuid,text,jsonb)','execute')
  AND NOT has_function_privilege('anon','public.decide_home_lease(text,uuid,uuid,uuid,text,text,jsonb,text,integer,uuid,text,jsonb)','execute')
  AND has_function_privilege('service_role','public.decide_home_lease(text,uuid,uuid,uuid,text,text,jsonb,text,integer,uuid,text,jsonb)','execute'),
  'Only the service may decide a lease');
END $$;
-- Creation uses the existing invite row as its retry identity, with the same
-- current authority/Home lock and atomic audit as admission decisions.
INSERT INTO public."Home"(id,address,city,state,zipcode,home_type) VALUES
 ('f3190000-0000-4000-8000-000000000019','Invite creation contract','Test','CA','00000','apartment');
INSERT INTO public."HomeAuthority"(id,home_id,subject_type,subject_id,role,status) VALUES
 ('f3190000-0000-4000-8000-000000000029','f3190000-0000-4000-8000-000000000019','user','f3190000-0000-4000-8000-000000000001','owner','verified');
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000019';a uuid:='f3190000-0000-4000-8000-000000000001';
 au uuid:='f3190000-0000-4000-8000-000000000029';r jsonb;again jsonb;proof text:=md5('invite-create-proof')||md5('invite-create-proof');
 dates jsonb:=jsonb_build_object('start_at',now()+interval '1 day','end_at',now()+interval '1 year');
BEGIN
 r:=public.decide_home_lease('invite','f3190000-0000-4000-8000-000000000003',p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='false','Invite creation requires the current authority actor');
 r:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:='{"start_at":"2026-02-31"}',p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='false','Invite creation rejects impossible calendar dates');
 r:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=jsonb_build_object('start_at',now()+interval '2 years','end_at',now()+interval '1 year'),p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='false','Invite creation rejects reversed dates');
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 r:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='false','Frozen Home cannot issue an invitation');
 UPDATE public."Home" SET security_state='normal',home_type='multi_unit' WHERE id=h;
 r:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='false' AND NOT EXISTS(SELECT FROM public."HomeLeaseInvite" WHERE home_id=h),'Parent building cannot issue an invitation; invalid attempts write nothing');
 UPDATE public."Home" SET home_type='apartment' WHERE id=h;
 r:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:=' LEASE-CONTRACT-2@EXAMPLE.INVALID ',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->>'replayed'='false' AND r->'invite'->>'token_hash'=proof
   AND r->'invite'->>'invitee_user_id'='f3190000-0000-4000-8000-000000000002'
   AND r->'invite'->>'invitee_email'='lease-contract-2@example.invalid'
   AND (r->'invite'->>'expires_at')::timestamptz BETWEEN now()+interval '14 days' AND clock_timestamp()+interval '14 days'
   AND NOT EXISTS(SELECT FROM public."HomeLease" WHERE home_id=h),'Creation binds recipient/dates and14-day expiry without granting membership');
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'replayed'='true' AND again->'invite'=r->'invite'
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE home_id=h AND action='TENANT_INVITED'),'Lost creation reply recovers the same row and audit');
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='different@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'status'='409','A retained proof cannot silently change invitation details');
 again:=public.decide_home_lease('invite',a,p_authority_id:='f3190000-0000-4000-8000-000000000020',p_home_id:='f3190000-0000-4000-8000-000000000010',p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'status'='409','An invitation proof cannot be reused for a different Home');
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=md5('second-proof')||md5('second-proof'),p_user_email:='LEASE-CONTRACT-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'status'='409' AND (SELECT count(*)=1 FROM public."HomeLeaseInvite" WHERE home_id=h),'Another proof cannot create a duplicate live pending invite');
 UPDATE public."HomeAuthority" SET status='revoked' WHERE id=au;
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'status'='403','Revoked authority cannot issue or recover invitation data');
 UPDATE public."HomeAuthority" SET status='verified' WHERE id=au;
 UPDATE public."HomeLeaseInvite" SET expires_at=now()-interval '1 second' WHERE home_id=h;
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=proof,p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'status'='410','An expired proof cannot create a replacement silently');
 again:=public.decide_home_lease('invite',a,p_authority_id:=au,p_home_id:=h,p_token_hash:=md5('second-proof')||md5('second-proof'),p_user_email:='lease-contract-2@example.invalid',p_dates:=dates,p_validity_days:=14);
 PERFORM pg_temp.check_lease(again->>'success'='true' AND again->>'replayed'='false'
   AND (SELECT count(*)=2 FROM public."HomeLeaseInvite" WHERE home_id=h),'Expired pending history does not block an explicit fresh invitation');
END $$;
RESET ROLE;

SET LOCAL ROLE service_role;
DO $$
DECLARE
 a uuid:='f3190000-0000-4000-8000-000000000001'; t uuid:='f3190000-0000-4000-8000-000000000002';
 intruder uuid:='f3190000-0000-4000-8000-000000000003'; business uuid:='f3190000-0000-4000-8000-000000000004';
 h uuid:='f3190000-0000-4000-8000-000000000010'; au uuid:='f3190000-0000-4000-8000-000000000020';
 l uuid; r jsonb; replay jsonb; before_occ jsonb; saved_start timestamptz; dates jsonb; i integer;
BEGIN
 -- Fresh landlord approval is the proof; no circular AddressClaim prerequisite.
 l:=pg_temp.pending_lease();
 SELECT start_at INTO saved_start FROM public."HomeLease" WHERE id=l;
 r:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='active'
   AND r->'occupancy'->>'role_base'='lease_resident' AND r->'occupancy'->>'verification_status'='verified'
   AND (r->'lease'->>'start_at')::timestamptz=saved_start
   AND r->'lease'->'metadata'->>'preserved'='yes','Approval must commit lease and verified occupancy without a claim');
 PERFORM pg_temp.check_lease(EXISTS(SELECT FROM public."HomeLeaseResident" WHERE lease_id=l AND user_id=t)
   AND public.home_effective_access(h,t)->>'has_access'='true','Approval must persist resident and usable access');
 before_occ:=r->'occupancy';
 replay:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(replay->>'replayed'='true' AND replay->'occupancy'=before_occ
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE target_id=l AND action='LEASE_APPROVED'),
   'Lost-reply retry must return the same result without another audit/write');
 PERFORM pg_temp.check_lease(public.decide_home_lease('deny',a,l,au)->>'success'='false',
   'Denial must not overwrite a committed approval');
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au,p_dates:='{"end_at":null}')->>'success'='false',
   'Different retry intent must not silently change completed dates');
 UPDATE public."HomeOccupancy" SET is_active=false WHERE home_id=h AND user_id=t;
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au)->>'success'='false'
   AND NOT (SELECT is_active FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t),
   'Old completed approval must not resurrect removed access');

 -- A fresh lease replaces expired access bounds, retaining the same row and age.
 UPDATE public."HomeOccupancy" SET is_active=true,access_end_at=now()-interval '1 day',age_band='teen'
   WHERE home_id=h AND user_id=t;
 l:=pg_temp.pending_lease(); dates:=jsonb_build_object('start_at',now()+interval '7 days','end_at',NULL);
 r:=public.decide_home_lease('approve',a,l,au,p_dates:=dates);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'occupancy'->>'id'=before_occ->>'id'
   AND r->'occupancy'->>'role_base'='member' AND r->'occupancy'->>'age_band'='teen'
   AND r->'occupancy'->>'can_manage_home'='false' AND r->'occupancy'->>'can_view_sensitive'='false'
   AND r->'occupancy'->>'access_end_at' IS NULL AND r->'lease'->>'end_at' IS NULL
   AND r->'occupancy'->>'access_start_at'=r->'lease'->>'start_at'
   AND public.home_effective_access(h,t)->>'has_access'='false','Future renewal must replace expired bounds without granting early access');
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au,p_dates:=dates)->>'replayed'='true',
   'Future-start completed approval must be replayable');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;

 -- Authorization, date errors and denial must leave membership untouched.
 l:=pg_temp.pending_lease();
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',intruder,l,au)->>'success'='false','Actor binding');
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,'f3190000-0000-4000-8000-000000000021')->>'success'='false','Other home authority');
 UPDATE public."HomeAuthority" SET status='revoked' WHERE id=au;
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au)->>'success'='false','Revoked authority');
 UPDATE public."HomeAuthority" SET status='pending' WHERE id=au;
 PERFORM pg_temp.check_lease(public.decide_home_lease('deny',a,l,au)->>'success'='false','Pending authority');
 UPDATE public."HomeAuthority" SET status='verified' WHERE id=au;
 FOR dates IN SELECT value FROM jsonb_array_elements('[{"start_at":null},{"start_at":"bad"},
   {"start_at":"infinity"},{"start_at":"2027-01-01","end_at":"2027-01-01"},
   {"start_at":"2027-02-01","end_at":"2027-01-01"},{"end_at":"bad"}]') LOOP
   PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au,p_dates:=dates)->>'success'='false','Invalid dates must fail');
 END LOOP;
 PERFORM pg_temp.check_lease((SELECT state='pending' FROM public."HomeLease" WHERE id=l)
   AND NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t),'Rejected decisions must make no partial writes');
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au)->>'success'='false','Frozen home must deny admission');
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 r:=public.decide_home_lease('deny',a,l,au,p_reason:='Contract denial');
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='canceled'
   AND r->'lease'->'metadata'->>'denial_reason'='Contract denial'
   AND public.decide_home_lease('deny',a,l,au,p_reason:='Contract denial')->>'replayed'='true'
   AND public.decide_home_lease('approve',a,l,au)->>'success'='false','Denial reason, retry and competing approval');

 -- Existing current membership is independent: never downgrade or shorten it.
 INSERT INTO public."HomeOccupancy"(home_id,user_id,is_active,role,role_base,verification_status,start_at,can_manage_home)
 VALUES(h,t,true,'admin','admin','verified',now()-interval '1 day',true) RETURNING to_jsonb("HomeOccupancy".*) INTO before_occ;
 l:=pg_temp.pending_lease();
 r:=public.decide_home_lease('approve',a,l,au,p_dates:=jsonb_build_object('start_at',now()+interval '7 days'));
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'occupancy'=before_occ
   AND public.home_effective_access(h,t)->>'has_access'='true','Preserve independent current role, flags and access window');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;

 -- Both pre-existing business authority paths remain valid; inactive proofs fail.
 INSERT INTO public."BusinessTeam"(business_user_id,user_id,is_active) VALUES(business,a,true);
 l:=pg_temp.pending_lease();
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,'f3190000-0000-4000-8000-000000000022')->>'success'='true','Business team authority');
 UPDATE public."BusinessTeam" SET is_active=false WHERE business_user_id=business AND user_id=a;
 l:=pg_temp.pending_lease();
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,'f3190000-0000-4000-8000-000000000022')->>'success'='false','Inactive team cannot approve');
 INSERT INTO public."BusinessSeat"(id,business_user_id,display_name,is_active)
 VALUES('f3190000-0000-4000-8000-000000000050',business,'Contract seat',true);
 INSERT INTO public."SeatBinding"(seat_id,user_id,binding_method)
 VALUES('f3190000-0000-4000-8000-000000000050',a,'invite_accept');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,'f3190000-0000-4000-8000-000000000022')->>'success'='true','Business seat authority');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;

 -- Actual invite -> acceptance -> membership, identity and issuer checks.
 INSERT INTO public."HomeLeaseInvite"(id,home_id,landlord_subject_type,landlord_subject_id,invitee_email,token_hash,expires_at,proposed_start)
 VALUES('f3190000-0000-4000-8000-000000000040',h,'user',a,'lease-contract-2@example.invalid',repeat('a',64),now()+interval '1 day',now()-interval '1 hour');
 PERFORM pg_temp.check_lease(public.decide_home_lease('accept',intruder,p_token_hash:=repeat('a',64),p_user_email:='wrong@example.invalid')->>'success'='false','Invite email binding');
 UPDATE public."HomeAuthority" SET status='revoked' WHERE id=au;
 PERFORM pg_temp.check_lease(public.decide_home_lease('accept',t,p_token_hash:=repeat('a',64),p_user_email:='lease-contract-2@example.invalid')->>'success'='false'
   AND (SELECT status='pending' FROM public."HomeLeaseInvite" WHERE token_hash=repeat('a',64)),'Revoked issuer cannot consume invitation');
 UPDATE public."HomeAuthority" SET status='verified' WHERE id=au;
 r:=public.decide_home_lease('accept',t,p_token_hash:=repeat('a',64),p_user_email:=' LEASE-CONTRACT-2@EXAMPLE.INVALID ');
 replay:=public.decide_home_lease('accept',t,p_token_hash:=repeat('a',64),p_user_email:='lease-contract-2@example.invalid');
 PERFORM pg_temp.check_lease(r->>'success'='true' AND replay->>'replayed'='true' AND r->'lease'=replay->'lease'
   AND (SELECT count(*)=1 FROM public."HomeLease" WHERE metadata->>'invite_id'='f3190000-0000-4000-8000-000000000040')
   AND (SELECT status='accepted' AND invitee_user_id=t FROM public."HomeLeaseInvite" WHERE token_hash=repeat('a',64)),
   'Invite acceptance and retry must create exactly one lease');
 UPDATE public."HomeLeaseInvite" SET status='revoked' WHERE token_hash=repeat('a',64);
 PERFORM pg_temp.check_lease(public.decide_home_lease('accept',t,p_token_hash:=repeat('a',64),p_user_email:='lease-contract-2@example.invalid')->>'success'='false',
   'Revoked completed invitation must not replay success');
 UPDATE public."HomeLeaseInvite" SET status='accepted' WHERE token_hash=repeat('a',64);
 UPDATE public."HomeOccupancy" SET is_active=false WHERE home_id=h AND user_id=t;
 PERFORM pg_temp.check_lease(public.decide_home_lease('accept',t,p_token_hash:=repeat('a',64),p_user_email:='lease-contract-2@example.invalid')->>'success'='false','Old invite must not reactivate removed membership');

 -- Fresh invitations from existing business/trust issuers are still accepted.
 FOR i IN 1..2 LOOP
   DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;
   INSERT INTO public."HomeLeaseInvite"(home_id,landlord_subject_type,landlord_subject_id,invitee_user_id,token_hash,expires_at)
   VALUES(h,CASE WHEN i=1 THEN 'business' ELSE 'trust' END::public.subject_type,business,t,repeat(i::text,64),now()+interval '1 day');
   PERFORM pg_temp.check_lease(public.decide_home_lease('accept',t,p_token_hash:=repeat(i::text,64))->>'success'='true','Verified business/trust invite issuer');
 END LOOP;
 INSERT INTO public."HomeLeaseInvite"(home_id,landlord_subject_type,landlord_subject_id,token_hash,expires_at)
 VALUES(h,'user',a,repeat('e',64),now()-interval '1 second');
 PERFORM pg_temp.check_lease(public.decide_home_lease('accept',t,p_token_hash:=repeat('e',64))->>'error'='Invite has expired','Expired invite');
 RAISE NOTICE 'Lease decision lifecycle, dates, authority, membership and replay assertions passed';
END $$;
RESET ROLE;

-- A verified landlord still cannot admit a building-only, unresolved unit.
INSERT INTO public."HomeAddress"(id,address_line1_norm,city_norm,state,postal_code,address_hash,building_type,missing_secondary_flag)
 VALUES('f3190000-0000-4000-8000-000000000014','lease unit contract','test','CA','00000','lease-unit-contract','multi_unit',true);
UPDATE public."Home" SET address_id='f3190000-0000-4000-8000-000000000014' WHERE id='f3190000-0000-4000-8000-000000000010';
SET LOCAL ROLE service_role;
DO $$ DECLARE l uuid;r jsonb;
BEGIN
 l:=pg_temp.pending_lease();r:=public.decide_home_lease('approve','f3190000-0000-4000-8000-000000000001',l,'f3190000-0000-4000-8000-000000000020');
 PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE '%unit number%'
   AND (SELECT state='pending' FROM public."HomeLease" WHERE id=l),'Approval must preserve unresolved-unit boundary');
 INSERT INTO public."HomeLeaseInvite"(home_id,landlord_subject_type,landlord_subject_id,token_hash,expires_at)
 VALUES('f3190000-0000-4000-8000-000000000010','user','f3190000-0000-4000-8000-000000000001',repeat('d',64),now()+interval '1 day');
 r:=public.decide_home_lease('accept','f3190000-0000-4000-8000-000000000002',p_token_hash:=repeat('d',64));
 PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE '%unit number%'
   AND (SELECT status='pending' FROM public."HomeLeaseInvite" WHERE token_hash=repeat('d',64)),'Invite must preserve unresolved-unit boundary');
 UPDATE public."HomeAddress" SET missing_secondary_flag=false WHERE id='f3190000-0000-4000-8000-000000000014';
 DELETE FROM public."HomeOccupancy" WHERE home_id='f3190000-0000-4000-8000-000000000010';
 r:=public.decide_home_lease('approve','f3190000-0000-4000-8000-000000000001',l,'f3190000-0000-4000-8000-000000000020');
 PERFORM pg_temp.check_lease(r->>'success'='true','Resolved unit address must remain admissible');

END $$;
RESET ROLE;
UPDATE public."Home" SET address_id=NULL WHERE id='f3190000-0000-4000-8000-000000000010';

-- Home's real multi_unit enum must also block parent-building admission, even
-- when address data is absent or its unit flag appears resolved.
UPDATE public."Home" SET home_type='multi_unit' WHERE id='f3190000-0000-4000-8000-000000000010';
SET LOCAL ROLE service_role;
DO $$ DECLARE l uuid;r jsonb;i integer;before_count integer;before_occ jsonb;
 h uuid:='f3190000-0000-4000-8000-000000000010';a uuid:='f3190000-0000-4000-8000-000000000001';
 t uuid:='f3190000-0000-4000-8000-000000000002';au uuid:='f3190000-0000-4000-8000-000000000020';
BEGIN
 FOR i IN 8..9 LOOP
   UPDATE public."Home" SET address_id=CASE WHEN i=8 THEN NULL ELSE 'f3190000-0000-4000-8000-000000000014'::uuid END WHERE id=h;
   l:=pg_temp.pending_lease();
   SELECT count(*) INTO before_count FROM public."HomeLease" WHERE home_id=h;
   SELECT jsonb_agg(to_jsonb(o) ORDER BY id) INTO before_occ FROM public."HomeOccupancy" o WHERE home_id=h;
   r:=public.decide_home_lease('approve',a,l,au);
   PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE '%unit number%'
     AND (SELECT state='pending' FROM public."HomeLease" WHERE id=l),'Parent multi_unit Home cannot approve a lease');
   INSERT INTO public."HomeLeaseInvite"(home_id,landlord_subject_type,landlord_subject_id,token_hash,expires_at)
     VALUES(h,'user',a,repeat(i::text,64),now()+interval '1 day');
   r:=public.decide_home_lease('accept',t,p_token_hash:=repeat(i::text,64));
   PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE '%unit number%'
     AND (SELECT status='pending' FROM public."HomeLeaseInvite" WHERE token_hash=repeat(i::text,64)),
     'Parent multi_unit Home cannot consume an invitation');
   r:=public.decide_home_lease('request',t,p_home_id:=h);
   PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE '%unit number%'
     AND (SELECT count(*)=before_count FROM public."HomeLease" WHERE home_id=h)
     AND before_occ IS NOT DISTINCT FROM (SELECT jsonb_agg(to_jsonb(o) ORDER BY id) FROM public."HomeOccupancy" o WHERE home_id=h),
     'Parent multi_unit Home cannot create a tenant request or change occupancy');
 END LOOP;
 UPDATE public."Home" SET home_type='apartment',address_id=NULL WHERE id=h;
 -- Retire the earlier contract's membership so its active-lease conflict does
 -- not replace the Home-type compatibility check.
 DELETE FROM public."HomeOccupancy" WHERE home_id=h;
 r:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true','An apartment remains admissible after enforcing the actual building enum');
END $$;
RESET ROLE;

-- End/retry proofs use a separate Home so earlier admission cases are independent.
INSERT INTO public."Home"(id,address,city,state,zipcode) VALUES
 ('f3190000-0000-4000-8000-000000000012','Lease end contract','Test','CA','00000');
INSERT INTO public."HomeAuthority"(id,home_id,subject_type,subject_id,role,status) VALUES
 ('f3190000-0000-4000-8000-000000000024','f3190000-0000-4000-8000-000000000012','user','f3190000-0000-4000-8000-000000000001','owner','verified');
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000012';a uuid:='f3190000-0000-4000-8000-000000000001';
 t uuid:='f3190000-0000-4000-8000-000000000002';au uuid:='f3190000-0000-4000-8000-000000000024';
 l uuid; second_lease uuid; r jsonb; saved jsonb;
BEGIN
 l:=pg_temp.pending_lease(h);r:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->'metadata'->'landlord_decision'->>'owns_membership'='true','Fresh lease must bind the membership it admits');
 second_lease:=pg_temp.pending_lease(h);
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,second_lease,au)->>'success'='false'
   AND (SELECT state='pending' FROM public."HomeLease" WHERE id=second_lease),'Duplicate lease must not take over current lease access');
 PERFORM pg_temp.check_lease(public.decide_home_lease('end','f3190000-0000-4000-8000-000000000003',l,au)->>'success'='false','Unrelated actor cannot end a lease');
 UPDATE public."HomeAuthority" SET status='revoked' WHERE id=au;
 PERFORM pg_temp.check_lease(public.decide_home_lease('end',a,l,au)->>'success'='false','Revoked landlord cannot end a lease');
 UPDATE public."HomeAuthority" SET status='verified' WHERE id=au;
 r:=public.decide_home_lease('end',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='ended'
   AND public.home_effective_access(h,t)->>'has_access'='false'
   AND EXISTS(SELECT FROM public."HomeLeaseResident" WHERE lease_id=l AND user_id=t),'End must withdraw bound access while preserving historical resident records');
 PERFORM pg_temp.check_lease(public.decide_home_lease('end',a,l,au)->>'replayed'='true'
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE target_id=l AND action='LEASE_ENDED'),'Completed end retry must not duplicate effects');
 r:=public.decide_home_lease('approve',a,second_lease,au);saved:=r->'occupancy';
 PERFORM pg_temp.check_lease(r->>'success'='true' AND public.home_effective_access(h,t)->>'has_access'='true','Fresh admission after completed end');
 PERFORM public.decide_home_lease('end',a,l,au);
 PERFORM pg_temp.check_lease(saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t),'Old end replay must not touch later membership');
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 r:=public.decide_home_lease('move_out',t,second_lease,p_reason:='Contract move');
 PERFORM pg_temp.check_lease(r->>'success'='true' AND public.home_effective_access(h,t)->>'has_access'='false'
   AND public.decide_home_lease('move_out',t,second_lease,p_reason:='Contract move')->>'replayed'='true'
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE target_id=second_lease AND action='TENANT_MOVE_OUT'),
   'Tenant move-out and reason audit must complete once');
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 UPDATE public."HomeOccupancy" SET role='admin',role_base='admin',is_active=true,verification_status='verified',
   start_at=now()-interval '1 day',end_at=NULL,access_start_at=NULL,access_end_at=NULL WHERE home_id=h AND user_id=t;
 SELECT to_jsonb(o) INTO saved FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t;
 l:=pg_temp.pending_lease(h);r:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(r->'lease'->'metadata'->'landlord_decision'->>'owns_membership'='false','Independent membership must not be attributed to this lease');
 r:=public.decide_home_lease('end',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t)
   AND public.home_effective_access(h,t)->>'has_access'='true','Ending the lease must preserve independent admin membership');
 -- An ambiguous historical link is never permission to sweep current access.
 l:=pg_temp.pending_lease(h);UPDATE public."HomeLease" SET state='active' WHERE id=l;
 UPDATE public."HomeOccupancy" SET role='lease_resident',role_base='lease_resident' WHERE home_id=h AND user_id=t;
 SELECT to_jsonb(o) INTO saved FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t;
 r:=public.decide_home_lease('end',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='false' AND r->>'error' LIKE 'Historical lease membership%'
   AND (SELECT state='active' FROM public."HomeLease" WHERE id=l)
   AND saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t),
   'Historical ambiguity requires review and must make no partial writes');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h AND user_id=t;
 r:=public.decide_home_lease('end',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true','Historical lease without any remaining membership can end');
 RAISE NOTICE 'Lease end, move-out, independent membership and replay assertions passed';
END $$;
RESET ROLE;

-- A co-resident leaves only their own membership. The accepted self-removal
-- helper also enforces ownership transfer; no lease proof can bypass it.
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000012';a uuid:='f3190000-0000-4000-8000-000000000001';
 t uuid:='f3190000-0000-4000-8000-000000000002';co uuid:='f3190000-0000-4000-8000-000000000003';
 au uuid:='f3190000-0000-4000-8000-000000000024';l uuid;r jsonb;saved jsonb;
BEGIN
 l:=pg_temp.pending_lease(h);r:=public.decide_home_lease('approve',a,l,au);saved:=r->'occupancy';
 INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,is_active,verification_status)
   VALUES(h,co,'member','member',true,'verified');
 INSERT INTO public."HomeLeaseResident"(lease_id,user_id) VALUES(l,co);
 PERFORM pg_temp.check_lease(public.decide_home_lease('end',co,l)->>'success'='false','Co-residency does not authorize ending the entire lease');
 UPDATE public."Home" SET owner_id=co WHERE id=h;
 r:=public.decide_home_lease('move_out',co,l);
 PERFORM pg_temp.check_lease(r->>'status'='409' AND r->>'error' LIKE 'Transfer home ownership%'
   AND EXISTS(SELECT FROM public."HomeLeaseResident" WHERE lease_id=l AND user_id=co)
   AND NOT EXISTS(SELECT FROM public."HomeAuditLog" WHERE target_id=l AND action='TENANT_MOVE_OUT'),
   'Owner transfer failure leaves lease and resident edge unchanged');
 UPDATE public."Home" SET owner_id=NULL WHERE id=h;
 r:=public.decide_home_lease('move_out',co,l,p_reason:='Co-resident departure');
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='active'
   AND saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id=h AND user_id=t)
   AND public.home_effective_access(h,co)->>'has_access'='false'
   AND NOT EXISTS(SELECT FROM public."HomeLeaseResident" WHERE lease_id=l AND user_id=co)
   AND EXISTS(SELECT FROM public."HomeAuditLog" WHERE target_id=l AND action='TENANT_MOVE_OUT'
     AND before_data->>'user_id'=co::text),'Co-resident departure preserves primary membership and retains its removed edge in audit history');
 PERFORM pg_temp.check_lease(public.decide_home_lease('move_out',co,l)->>'replayed'='true'
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE target_id=l AND action='TENANT_MOVE_OUT'),'Lost co-resident departure reply is replayable after edge removal');
 UPDATE public."HomeOccupancy" SET is_active=true,verification_status='verified',end_at=NULL,access_end_at=NULL WHERE home_id=h AND user_id=co;
 r:=public.decide_home_lease('move_out',co,l);
 PERFORM pg_temp.check_lease(r->>'status'='409' AND public.home_effective_access(h,co)->>'has_access'='true','Old self-departure must not remove restored membership');
 -- Landlord end preserves independent access, but an explicit tenant departure
 -- removes that person's household membership even after the lease is ended.
 PERFORM public.decide_home_lease('end',a,l,au);
 UPDATE public."HomeOccupancy" SET role='admin',role_base='admin',is_active=true,verification_status='verified',
   end_at=NULL,access_end_at=NULL WHERE home_id=h AND user_id=t;
 r:=public.decide_home_lease('move_out',t,l);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND public.home_effective_access(h,t)->>'has_access'='false'
   AND public.decide_home_lease('move_out',t,l)->>'replayed'='true','Self departure after landlord end must remove independent own membership');
 DELETE FROM public."HomeOccupancy" WHERE home_id=h;
 RAISE NOTICE 'Co-resident departure, ownership, saved history and restored membership assertions passed';
END $$;
RESET ROLE;

-- Request creation uses existing records and the same serialized Home scope.
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000012';a uuid:='f3190000-0000-4000-8000-000000000001';
 t uuid:='f3190000-0000-4000-8000-000000000002';au uuid:='f3190000-0000-4000-8000-000000000024';r jsonb;l uuid;dates jsonb;
BEGIN
 UPDATE public."HomeAuthority" SET status='revoked' WHERE id=au;
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h)->>'success'='false','Revoked landlord cannot receive new tenant request');
 UPDATE public."HomeAuthority" SET status='verified' WHERE id=au;
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h)->>'success'='false','Frozen home cannot accept new tenant request');
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 FOR dates IN SELECT value FROM jsonb_array_elements('[{"start_at":"infinity"},{"start_at":"bad"},{"start_at":"2027-10-02","end_at":"2027-10-01"}]') LOOP
   PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h,p_dates:=dates)->>'success'='false','Invalid request date must not create a pending lease');
 END LOOP;
 r:=public.decide_home_lease('request',t,p_home_id:=h,p_dates:='{"start_at":"2027-10-01","end_at":null}',p_message:=' Request message ');
 l:=(r->'lease'->>'id')::uuid;
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='pending'
   AND r->'lease'->'metadata'->>'message'='Request message'
   AND NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h)
   AND EXISTS(SELECT FROM public."HomeAuditLog" WHERE target_id=l AND action='TENANT_REQUEST_SUBMITTED'),
   'Request commits pending record and audit without admitting membership');
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h)->>'status'='409',
   'Existing pending request prevents another insert');
 PERFORM public.decide_home_lease('cancel',t,l);
 r:=public.decide_home_lease('request',t,p_home_id:=h);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'id'<>l::text,'A new request after completed cancellation has a distinct lease');
 l:=(r->'lease'->>'id')::uuid;PERFORM public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h)->>'status'='409','Existing active lease prevents another pending request');
 PERFORM public.decide_home_lease('end',a,l,au);DELETE FROM public."HomeOccupancy" WHERE home_id=h;
END $$;
RESET ROLE;

-- The observed existing lease prevents a queued original from recreating a
-- request after another attempt is saved and canceled. No new command records.
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000012';t uuid:='f3190000-0000-4000-8000-000000000003';
 observed jsonb; latest jsonb; r jsonb; l uuid; audit_count bigint;
BEGIN
 observed:=jsonb_build_object('home_id',h,'actor_id',t,'lease_id',NULL,'lease_state',NULL);
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h,
   p_request_context:=observed||jsonb_build_object('actor_id',h))->>'status'='409','Observed context belongs to the authenticated actor');
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h,
   p_request_context:=observed||jsonb_build_object('home_id',t))->>'status'='409','Observed context belongs to this Home');
 r:=public.decide_home_lease('request',t,p_home_id:=h,p_request_context:=observed);
 l:=(r->'lease'->>'id')::uuid;
 PERFORM pg_temp.check_lease(r->>'success'='true','First observed request can be saved');
 PERFORM public.decide_home_lease('cancel',t,l);
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h,
   p_request_context:=observed||jsonb_build_object('lease_id',l,'lease_state','pending'))->>'status'='409',
   'A context read while pending also retires after cancellation of that same lease');
 SELECT count(*) INTO audit_count FROM public."HomeAuditLog" WHERE home_id=h;
 PERFORM pg_temp.check_lease(public.decide_home_lease('request',t,p_home_id:=h,p_request_context:=observed)->>'status'='409'
   AND (SELECT count(*)=1 FROM public."HomeLease" WHERE home_id=h AND primary_resident_user_id=t)
   AND (SELECT state='canceled' FROM public."HomeLease" WHERE id=l)
   AND (SELECT count(*)=audit_count FROM public."HomeAuditLog" WHERE home_id=h),
   'Queued original after retry cancellation cannot add lease, audit or membership');
 latest:=observed||jsonb_build_object('lease_id',l,'lease_state','canceled');
 r:=public.decide_home_lease('request',t,p_home_id:=h,p_request_context:=latest);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'id'<>l::text,
   'Explicit submission after observing cancellation can create a fresh request');
 PERFORM public.decide_home_lease('cancel',t,(r->'lease'->>'id')::uuid);
END $$;
RESET ROLE;

-- Withdrawal is a decision on the same existing pending request. It grants no
-- membership, and its completed receipt survives a lost response.
SET LOCAL ROLE service_role;
DO $$ DECLARE
 h uuid:='f3190000-0000-4000-8000-000000000012';a uuid:='f3190000-0000-4000-8000-000000000001';
 t uuid:='f3190000-0000-4000-8000-000000000002';au uuid:='f3190000-0000-4000-8000-000000000024';l uuid;r jsonb;
BEGIN
 l:=pg_temp.pending_lease(h);
 PERFORM pg_temp.check_lease(public.decide_home_lease('cancel',a,l,au)->>'status'='403','Landlord cannot impersonate the requesting tenant to withdraw');
 UPDATE public."Home" SET security_state='frozen' WHERE id=h;
 r:=public.decide_home_lease('cancel',t,l);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->'lease'->>'state'='canceled'
   AND public.decide_home_lease('cancel',t,l)->>'replayed'='true'
   AND (SELECT count(*)=1 FROM public."HomeAuditLog" WHERE target_id=l AND action='LEASE_REQUEST_CANCELED')
   AND NOT EXISTS(SELECT FROM public."HomeOccupancy" WHERE home_id=h),'Self withdrawal in frozen Home commits once without admission');
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 PERFORM pg_temp.check_lease(public.decide_home_lease('approve',a,l,au)->>'success'='false','Approval cannot revive a withdrawn request');
 l:=pg_temp.pending_lease(h);PERFORM public.decide_home_lease('deny',a,l,au,p_reason:='Denied');
 PERFORM pg_temp.check_lease(public.decide_home_lease('cancel',t,l)->>'status'='409','Cancellation cannot erase a landlord denial');
 l:=pg_temp.pending_lease(h);r:=public.decide_home_lease('approve',a,l,au);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND public.decide_home_lease('cancel',t,l)->>'status'='409'
   AND public.home_effective_access(h,t)->>'has_access'='true','Cancellation cannot undo approved membership');
 PERFORM public.decide_home_lease('end',a,l,au);DELETE FROM public."HomeOccupancy" WHERE home_id=h;
END $$;
RESET ROLE;

-- Failure after every deactivation still rolls the entire end operation back.
CREATE FUNCTION pg_temp.fail_lease_end_audit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF NEW.action='LEASE_ENDED' THEN RAISE EXCEPTION 'contract end audit failure'; END IF; RETURN NEW; END $$;
CREATE TRIGGER contract_lease_end_fault BEFORE INSERT ON public."HomeAuditLog"
 FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_lease_end_audit();
SET LOCAL ROLE service_role;
DO $$ DECLARE l uuid;r jsonb;saved jsonb;
 h uuid:='f3190000-0000-4000-8000-000000000012';a uuid:='f3190000-0000-4000-8000-000000000001';au uuid:='f3190000-0000-4000-8000-000000000024';
BEGIN
 l:=pg_temp.pending_lease(h);r:=public.decide_home_lease('approve',a,l,au);saved:=r->'occupancy';
 BEGIN
  PERFORM public.decide_home_lease('end',a,l,au);RAISE EXCEPTION 'Expected end audit failure was not reached';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'contract end audit failure' THEN RAISE; END IF; END;
 PERFORM pg_temp.check_lease((SELECT state='active' FROM public."HomeLease" WHERE id=l)
   AND saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE id=(saved->>'id')::uuid)
   AND NOT EXISTS(SELECT FROM public."HomeAuditLog" WHERE target_id=l AND action='LEASE_ENDED'),'End audit fault must restore lease and membership');
 BEGIN
  PERFORM public.decide_home_lease('move_out',(saved->>'user_id')::uuid,l);
  RAISE EXCEPTION 'Expected move-out audit failure was not reached';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'contract end audit failure' THEN RAISE; END IF; END;
 PERFORM pg_temp.check_lease(saved=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE id=(saved->>'id')::uuid)
   AND (SELECT metadata->'resident_departures' IS NULL FROM public."HomeLease" WHERE id=l)
   AND NOT EXISTS(SELECT FROM public."HomeAuditLog" WHERE target_id=l AND action='TENANT_MOVE_OUT'),
   'Final end audit failure must also roll back canonical self-removal and its departure receipt');
END $$;
RESET ROLE;
DROP TRIGGER contract_lease_end_fault ON public."HomeAuditLog";

-- Fail the final audit write. Every preceding lease/resident/occupancy/invite
-- mutation must roll back, and the same request must work after recovery.
CREATE FUNCTION pg_temp.fail_lease_audit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN IF NEW.action IN ('LEASE_APPROVED','LEASE_INVITE_ACCEPTED','LEASE_REQUEST_CANCELED','TENANT_REQUEST_SUBMITTED','TENANT_INVITED') THEN RAISE EXCEPTION 'contract audit failure'; END IF; RETURN NEW; END $$;
CREATE TRIGGER contract_lease_audit_failure BEFORE INSERT ON public."HomeAuditLog"
 FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_lease_audit();
SET LOCAL ROLE service_role;
DO $$ DECLARE l uuid; before_occ jsonb; after_occ jsonb; r jsonb;
BEGIN
 BEGIN
   PERFORM public.decide_home_lease('invite','f3190000-0000-4000-8000-000000000001',p_authority_id:='f3190000-0000-4000-8000-000000000029',p_home_id:='f3190000-0000-4000-8000-000000000019',p_token_hash:=md5('rollback-create')||md5('rollback-create'),p_user_email:='rollback@example.invalid',p_dates:=jsonb_build_object('start_at',now()+interval '1 day'),p_validity_days:=14);
   RAISE EXCEPTION 'Expected invite creation audit fault was not reached';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'contract audit failure' THEN RAISE; END IF; END;
 PERFORM pg_temp.check_lease(NOT EXISTS(SELECT FROM public."HomeLeaseInvite" WHERE token_hash=md5('rollback-create')||md5('rollback-create')),'Invite audit failure rolls back the invitation and retry identity');
 BEGIN
   PERFORM public.decide_home_lease('request','f3190000-0000-4000-8000-000000000002',p_home_id:='f3190000-0000-4000-8000-000000000011');
   RAISE EXCEPTION 'Expected request audit fault was not reached';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'contract audit failure' THEN RAISE; END IF; END;
 PERFORM pg_temp.check_lease(NOT EXISTS(SELECT FROM public."HomeLease" WHERE home_id='f3190000-0000-4000-8000-000000000011' AND state='pending'),
   'Request audit fault rolls back the new pending lease');
 l:=pg_temp.pending_lease();
 UPDATE public."HomeOccupancy" SET is_active=false WHERE home_id='f3190000-0000-4000-8000-000000000010';
 SELECT to_jsonb(o) INTO before_occ FROM public."HomeOccupancy" o WHERE home_id='f3190000-0000-4000-8000-000000000010';
 BEGIN
   PERFORM public.decide_home_lease('approve','f3190000-0000-4000-8000-000000000001',l,'f3190000-0000-4000-8000-000000000020');
   RAISE EXCEPTION 'Expected audit fault was not reached';
 EXCEPTION WHEN raise_exception THEN
   IF SQLERRM<>'contract audit failure' THEN RAISE; END IF;
 END;
 SELECT to_jsonb(o) INTO after_occ FROM public."HomeOccupancy" o WHERE home_id='f3190000-0000-4000-8000-000000000010';
 BEGIN
   PERFORM public.decide_home_lease('cancel','f3190000-0000-4000-8000-000000000002',l);
   RAISE EXCEPTION 'Expected cancellation audit fault was not reached';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'contract audit failure' THEN RAISE; END IF; END;
 PERFORM pg_temp.check_lease((SELECT state='pending' AND metadata->'tenant_cancellation' IS NULL FROM public."HomeLease" WHERE id=l),
   'Cancellation audit failure must restore the pending request without a completed receipt');
 PERFORM pg_temp.check_lease(before_occ=after_occ AND (SELECT state='pending' FROM public."HomeLease" WHERE id=l)
   AND NOT EXISTS(SELECT FROM public."HomeLeaseResident" WHERE lease_id=l),'Final-write failure must roll back all mutations');
 INSERT INTO public."HomeLeaseInvite"(home_id,landlord_subject_type,landlord_subject_id,token_hash,expires_at)
 VALUES('f3190000-0000-4000-8000-000000000010','user','f3190000-0000-4000-8000-000000000001',repeat('f',64),now()+interval '1 day');
 BEGIN
   PERFORM public.decide_home_lease('accept','f3190000-0000-4000-8000-000000000002',p_token_hash:=repeat('f',64));
   RAISE EXCEPTION 'Expected invite audit fault was not reached';
 EXCEPTION WHEN raise_exception THEN
   IF SQLERRM<>'contract audit failure' THEN RAISE; END IF;
 END;
 PERFORM pg_temp.check_lease((SELECT status='pending' AND invitee_user_id IS NULL FROM public."HomeLeaseInvite" WHERE token_hash=repeat('f',64))
   AND NOT EXISTS(SELECT FROM public."HomeLease" WHERE metadata->>'invite_id'=(SELECT id::text FROM public."HomeLeaseInvite" WHERE token_hash=repeat('f',64)))
   AND before_occ=(SELECT to_jsonb(o) FROM public."HomeOccupancy" o WHERE home_id='f3190000-0000-4000-8000-000000000010'),
   'Invite failure must roll back consumption, inserted lease and membership');

END $$;
RESET ROLE;
DROP TRIGGER contract_lease_audit_failure ON public."HomeAuditLog";
SET LOCAL ROLE service_role;
DO $$ DECLARE l uuid; r jsonb;
BEGIN
 SELECT id INTO l FROM public."HomeLease" WHERE home_id='f3190000-0000-4000-8000-000000000010' AND state='pending' ORDER BY created_at DESC LIMIT 1;
 r:=public.decide_home_lease('approve','f3190000-0000-4000-8000-000000000001',l,'f3190000-0000-4000-8000-000000000020');
 PERFORM pg_temp.check_lease(r->>'success'='true','Rolled-back approval must remain retryable');
 r:=public.decide_home_lease('invite','f3190000-0000-4000-8000-000000000001',p_authority_id:='f3190000-0000-4000-8000-000000000029',p_home_id:='f3190000-0000-4000-8000-000000000019',p_token_hash:=md5('rollback-create')||md5('rollback-create'),p_user_email:='rollback@example.invalid',p_dates:=jsonb_build_object('start_at',now()+interval '1 day'),p_validity_days:=14);
 PERFORM pg_temp.check_lease(r->>'success'='true' AND r->>'replayed'='false'
   AND (SELECT count(*)=1 FROM public."HomeLeaseInvite" WHERE token_hash=md5('rollback-create')||md5('rollback-create')),
   'Rolled-back invitation must remain retryable with its original proof');
 RAISE NOTICE 'Lease decision rollback and retry assertions passed';
END $$;
RESET ROLE;

$contract$, 'home-lease-decisions.sql');
SELECT * FROM finish();
ROLLBACK;
