-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-postcard-current-recovery.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Current postal policy uses the same locked authority as residency review.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
INSERT INTO auth.users(id,email) VALUES
 ('ddc24700-0000-4000-8000-000000000001','postal-policy-owner@example.invalid'),
 ('ddc24700-0000-4000-8000-000000000002','postal-policy-applicant@example.invalid'),
 ('ddc24700-0000-4000-8000-000000000003','postal-policy-outsider@example.invalid');
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'postal_policy_'||right(id::text,2),'Postal policy fixture'
 FROM auth.users WHERE id IN ('ddc24700-0000-4000-8000-000000000001','ddc24700-0000-4000-8000-000000000002','ddc24700-0000-4000-8000-000000000003');
INSERT INTO public."Home"(id,created_by_user_id,address,address2,city,state,zipcode) VALUES
 ('ddc24700-0000-4000-8000-000000000100','ddc24700-0000-4000-8000-000000000001','Postal policy fixture','602','Test','WA','98607');
INSERT INTO public."HomeOwner"(home_id,subject_id,owner_status,is_primary_owner) VALUES
 ('ddc24700-0000-4000-8000-000000000100','ddc24700-0000-4000-8000-000000000001','verified',true);
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,verification_status,age_band) VALUES
 ('ddc24700-0000-4000-8000-000000000100','ddc24700-0000-4000-8000-000000000002','member','restricted_member','pending_postcard','teen');
INSERT INTO public."HomeResidencyClaim"(home_id,user_id,claimed_address,claimed_role) VALUES
 ('ddc24700-0000-4000-8000-000000000100','ddc24700-0000-4000-8000-000000000002','Postal policy fixture, 602','renter');
DO $$ BEGIN
 IF has_function_privilege('authenticated','public.home_postcard_current_context(uuid,uuid,boolean)','execute')
 OR has_function_privilege('anon','public.lock_home_postcard_current_scope(uuid,uuid)','execute')
 OR NOT has_function_privilege('service_role','public.home_postcard_current_context(uuid,uuid,boolean)','execute') THEN
 RAISE EXCEPTION 'Postal policy must be service-only'; END IF;
END $$;
SET LOCAL ROLE service_role;
DO $$
DECLARE
 h uuid:='ddc24700-0000-4000-8000-000000000100'; a uuid:='ddc24700-0000-4000-8000-000000000002';
 owner_id uuid:='ddc24700-0000-4000-8000-000000000001'; r jsonb; setting text;
BEGIN
 IF NOT public.lock_home_postcard_current_scope(h,a) THEN RAISE EXCEPTION 'Fixture did not lock'; END IF;
 r:=public.home_postcard_current_context(h,a,false);
 IF r->>'ok' IS DISTINCT FROM 'true' OR r->>'has_authorities' IS DISTINCT FROM 'true'
 OR r->>'age_band' IS DISTINCT FROM 'teen' THEN RAISE EXCEPTION 'Current owner without occupancy or saved age ceiling was lost'; END IF;
 UPDATE public."HomeOwner" SET owner_status='revoked' WHERE home_id=h AND subject_id=owner_id;
 IF public.home_postcard_current_context(h,a,false)->>'has_authorities' IS DISTINCT FROM 'false' THEN
 RAISE EXCEPTION 'Revoked owner became a postal reviewer'; END IF;
 UPDATE public."HomeOwner" SET owner_status='verified' WHERE home_id=h AND subject_id=owner_id;
 UPDATE public."User" SET date_of_birth='2020-01-01' WHERE id=a;
 IF public.home_postcard_current_context(h,a,false)->>'age_band' IS DISTINCT FROM 'child' THEN
 RAISE EXCEPTION 'Known child ceiling was not applied'; END IF;
 UPDATE public."User" SET date_of_birth=NULL WHERE id=a;
 FOREACH setting IN ARRAY ARRAY['frozen','frozen_silent','disputed'] LOOP
   UPDATE public."Home" SET security_state=setting::public.home_security_state WHERE id=h;
   IF public.home_postcard_current_context(h,a,false)->>'code' IS DISTINCT FROM 'POSTCARD_HOME_UNAVAILABLE' THEN
     RAISE EXCEPTION 'Restricted Home reached postal policy'; END IF;
 END LOOP;
 UPDATE public."Home" SET security_state='normal' WHERE id=h;
 FOREACH setting IN ARRAY ARRAY['archived','merged'] LOOP
   UPDATE public."Home" SET home_status=setting WHERE id=h;
   IF public.home_postcard_current_context(h,a,true)->>'code' IS DISTINCT FROM 'POSTCARD_HOME_UNAVAILABLE' THEN
     RAISE EXCEPTION 'Archived or merged Home reached confirmation policy'; END IF;
 END LOOP;
 UPDATE public."Home" SET home_status='active' WHERE id=h;
 UPDATE public."HomeOccupancy" SET start_at=clock_timestamp()+interval '1 day' WHERE home_id=h AND user_id=a;
 IF public.home_postcard_current_context(h,a,true)->>'code' IS DISTINCT FROM 'POSTCARD_ACCESS_REVIEW_REQUIRED' THEN
 RAISE EXCEPTION 'Future occupancy reached confirmation'; END IF;
 UPDATE public."HomeOccupancy" SET start_at=NULL,access_end_at=clock_timestamp()-interval '1 second' WHERE home_id=h AND user_id=a;
 IF public.home_postcard_current_context(h,a,false)->>'code' IS DISTINCT FROM 'POSTCARD_ACCESS_REVIEW_REQUIRED' THEN
 RAISE EXCEPTION 'Expired occupancy reached postal admission'; END IF;
 UPDATE public."HomeOccupancy" SET access_end_at=NULL,verification_status='verified',verified_at=clock_timestamp() WHERE home_id=h AND user_id=a;
 IF public.home_postcard_current_context(h,a,false)->>'code' IS DISTINCT FROM 'POSTCARD_REVIEW_ALREADY_RECORDED'
 OR public.home_postcard_current_context(h,a,true)->>'already_verified' IS DISTINCT FROM 'true' THEN
 RAISE EXCEPTION 'Recorded verification did not preserve separate request/confirmation decisions'; END IF;
 UPDATE public."HomeOccupancy" SET verification_status='pending_postcard' WHERE home_id=h AND user_id=a;
 IF public.home_postcard_current_context(h,a,false)->>'code' IS DISTINCT FROM 'POSTCARD_ACCESS_REVIEW_REQUIRED' THEN
 RAISE EXCEPTION 'Pending state revived previously verified access'; END IF;
 UPDATE public."HomeOccupancy" SET verified_at=NULL WHERE home_id=h AND user_id=a;
 UPDATE public."HomeResidencyClaim" SET status='rejected' WHERE home_id=h AND user_id=a;
 IF public.home_postcard_current_context(h,a,true)->>'code' IS DISTINCT FROM 'POSTCARD_ACCESS_REVIEW_REQUIRED' THEN
 RAISE EXCEPTION 'Postcard revived a rejected request'; END IF;
 UPDATE public."HomeResidencyClaim" SET status='pending' WHERE home_id=h AND user_id=a;
 UPDATE public."Home" SET owner_id=a WHERE id=h;
 IF public.home_postcard_current_context(h,a,true)->>'code' IS DISTINCT FROM 'OWNERSHIP_FLOW_REQUIRED' THEN
 RAISE EXCEPTION 'Postal proof could activate a legacy ownership pointer'; END IF;
 UPDATE public."Home" SET owner_id=NULL WHERE id=h;
 IF public.home_postcard_current_context(h,'ddc24700-0000-4000-8000-000000000003',false)->>'code'
   IS DISTINCT FROM 'POSTCARD_RESIDENCY_REQUEST_REQUIRED' THEN RAISE EXCEPTION 'Outsider reached postal admission'; END IF;
 IF public.home_postcard_current_context(h,a,false)->>'ok' IS DISTINCT FROM 'true' THEN
 RAISE EXCEPTION 'Ordinary pending applicant did not recover'; END IF;
END;
$$;
DO $$
DECLARE
 h uuid:='ddc24700-0000-4000-8000-000000000100'; a uuid:='ddc24700-0000-4000-8000-000000000002';
 address jsonb:=jsonb_build_object('line1','Postal policy fixture','line2','602','city','Test','state','WA','postal_code','98607','country','US');
 r jsonb; first_card uuid; old_values jsonb;
BEGIN
 IF public.valid_home_postcard_address('[]') OR public.valid_home_postcard_address('{}')
 OR public.valid_home_postcard_address(address||'{"line2":4}'::jsonb)
 OR NOT public.valid_home_postcard_address(address) THEN RAISE EXCEPTION 'Postal address shape validation failed'; END IF;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001001',address,
   'ddc24700-0000-4000-8000-000000002001',repeat('a',64),'fixture');
 IF r->>'state' IS DISTINCT FROM 'completed' OR r->>'code_key_id' IS DISTINCT FROM 'fixture'
 OR r->'postcard'->'destination'->>'address2' IS DISTINCT FROM '602' THEN RAISE EXCEPTION 'Postal command did not admit its selected unit'; END IF;
 first_card:=(r->>'postcard_id')::uuid;
 SELECT to_jsonb(p) INTO old_values FROM public."HomePostcardCode" p WHERE id=first_card;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001001',address,
   'ddc24700-0000-4000-8000-000000002002',repeat('b',64),'rotated');
 IF r->>'replayed' IS DISTINCT FROM 'true' OR r->>'postcard_id' IS DISTINCT FROM first_card::text
 OR r->>'code_key_id' IS DISTINCT FROM 'fixture' OR r->'postcard'->>'code_hash' IS DISTINCT FROM repeat('a',64) THEN
 RAISE EXCEPTION 'Original postal command changed its proof or key version'; END IF;
 r:=public.get_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001001');
 IF r::text ~ '(code_hash|destination|code_key_id)' THEN RAISE EXCEPTION 'Postal command projection exposed private worker material'; END IF;
 IF public.get_home_postcard_request(h,'ddc24700-0000-4000-8000-000000000003','ddc24700-0000-4000-8000-000000001001')->>'code'
 IS DISTINCT FROM 'POSTCARD_REQUEST_NOT_FOUND' THEN RAISE EXCEPTION 'Postal command crossed actors'; END IF;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001002',address,
   'ddc24700-0000-4000-8000-000000002003',repeat('c',64),'rotated');
 IF r->>'postcard_id' IS DISTINCT FROM first_card::text OR r->>'code_key_id' IS DISTINCT FROM 'fixture'
 OR (SELECT count(*) FROM public."HomePostcardCode" WHERE home_id=h AND user_id=a)<>1 THEN
 RAISE EXCEPTION 'Concurrent-equivalent personal request rotated or duplicated a pending proof'; END IF;
 r:=public.cancel_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001003');
 IF r->>'state' IS DISTINCT FROM 'cancelled' THEN RAISE EXCEPTION 'Postal cancellation did not fence first'; END IF;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001003',address,
   'ddc24700-0000-4000-8000-000000002004',repeat('d',64),'fixture');
 IF r->>'state' IS DISTINCT FROM 'cancelled' THEN RAISE EXCEPTION 'Delayed postal admission survived cancellation'; END IF;
 UPDATE public."Home" SET address2='999' WHERE id=h;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001004',address,
   'ddc24700-0000-4000-8000-000000002005',repeat('e',64),'fixture');
 IF r->>'state' IS DISTINCT FROM 'rejected' OR r->>'code' IS DISTINCT FROM 'POSTCARD_ADDRESS_CHANGED'
 OR (SELECT to_jsonb(p) FROM public."HomePostcardCode" p WHERE id=first_card) IS DISTINCT FROM old_values THEN
 RAISE EXCEPTION 'Changed-unit refusal altered a prior proof'; END IF;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001001',address||'{"line2":"999"}'::jsonb,
   'ddc24700-0000-4000-8000-000000002006',repeat('e',64),'fixture');
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_REQUEST_CONFLICT' THEN RAISE EXCEPTION 'Postal command accepted a changed intent'; END IF;
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001005',address||'{"line2":"999"}'::jsonb,
   'ddc24700-0000-4000-8000-000000002007',repeat('e',64),'fixture');
 IF r->>'state' IS DISTINCT FROM 'completed' OR r->'postcard'->'destination'->>'address2' IS DISTINCT FROM '999'
 OR NOT EXISTS(SELECT FROM public."HomePostcardCode" WHERE id=first_card AND status='cancelled'
   AND code_hash=old_values->>'code_hash' AND destination=old_values->'destination') THEN
 RAISE EXCEPTION 'Explicit new destination did not preserve and retire the incompatible proof'; END IF;
 r:=public.cancel_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001005');
 IF r->>'state' IS DISTINCT FROM 'completed' THEN RAISE EXCEPTION 'Cancellation pretended an admitted postcard was recalled'; END IF;
END;
$$;
DO $$
DECLARE
 h uuid:='ddc24700-0000-4000-8000-000000000100'; a uuid:='ddc24700-0000-4000-8000-000000000002';
 command_id uuid:='ddc24700-0000-4000-8000-000000001005'; card_id uuid:='ddc24700-0000-4000-8000-000000002007';
 r jsonb; before_card jsonb;
BEGIN
 r:=public.get_home_postcard_current_status(h,a);
 IF r->>'can_resume' IS DISTINCT FROM 'true' OR r->>'can_verify' IS DISTINCT FROM 'false'
 OR r->>'can_request' IS DISTINCT FROM 'false' OR r->'request'->'address'->>'line2' IS DISTINCT FROM '999'
 OR r->'postcard'->>'delivery' IS DISTINCT FROM 'not_started'
 OR r::text ~ '(code_hash|destination|code_key_id|vendor_job_id)' THEN RAISE EXCEPTION 'Postal current status was unsafe or could not recover before dispatch'; END IF;
 IF public.get_home_postcard_current_status(h,'ddc24700-0000-4000-8000-000000000003')->>'ok' IS DISTINCT FROM 'false' THEN
 RAISE EXCEPTION 'Postal current status crossed actors'; END IF;
 SELECT to_jsonb(p) INTO before_card FROM public."HomePostcardCode" p WHERE id=card_id;
 UPDATE public."Home" SET address2='PRIVATE-CHANGED' WHERE id=h;
 r:=public.get_home_postcard_current_status(h,a);
 IF r->'request'->'address'->>'line2' IS DISTINCT FROM '999' OR r::text LIKE '%PRIVATE-CHANGED%'
 OR r->>'can_resume' IS DISTINCT FROM 'false' OR r->>'can_verify' IS DISTINCT FROM 'false' THEN
 RAISE EXCEPTION 'Changed current Home address leaked or remained eligible'; END IF;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('e',64));
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_ADDRESS_CHANGED' THEN RAISE EXCEPTION 'Dispatch ignored selected address'; END IF;
 UPDATE public."Home" SET address2='999',home_status='archived' WHERE id=h;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('e',64));
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_HOME_UNAVAILABLE' THEN RAISE EXCEPTION 'Archived Home reached dispatch'; END IF;
 UPDATE public."Home" SET home_status='active' WHERE id=h;
 UPDATE public."HomeOccupancy" SET start_at=clock_timestamp()+interval '1 day' WHERE home_id=h AND user_id=a;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('e',64));
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_ACCESS_REVIEW_REQUIRED' THEN RAISE EXCEPTION 'Future occupancy reached dispatch'; END IF;
 UPDATE public."HomeOccupancy" SET start_at=NULL WHERE home_id=h AND user_id=a;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('f',64));
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_CODE_KEY_UNAVAILABLE'
 OR (SELECT to_jsonb(p) FROM public."HomePostcardCode" p WHERE id=card_id) IS DISTINCT FROM before_card THEN
 RAISE EXCEPTION 'Refused dispatch changed proof or accepted mismatched code'; END IF;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('e',64));
 IF r->>'claimed' IS DISTINCT FROM 'true' OR r->'postcard'->'destination'->>'address2' IS DISTINCT FROM '999' THEN
 RAISE EXCEPTION 'Dispatch did not claim the exact confirmed card'; END IF;
 r:=public.claim_home_postcard_current_dispatch(h,a,command_id,card_id,repeat('e',64));
 IF r->>'claimed' IS DISTINCT FROM 'false' OR r ? 'postcard' THEN RAISE EXCEPTION 'Dispatch retry recovered send permission'; END IF;
 r:=public.get_home_postcard_current_status(h,a);
 IF r->'postcard'->>'delivery' IS DISTINCT FROM 'unknown' OR r->>'can_resume' IS DISTINCT FROM 'false' THEN
 RAISE EXCEPTION 'Dispatch crash status pretended it could resend'; END IF;
 UPDATE public."HomePostcardCode" SET dispatch_status='accepted',vendor_job_id='psc_fixture_contract' WHERE id=card_id;
 r:=public.get_home_postcard_current_status(h,a);
 IF r->'postcard'->>'delivery' IS DISTINCT FROM 'accepted' OR r::text LIKE '%psc_fixture_contract%' THEN
 RAISE EXCEPTION 'Provider acceptance was misrepresented or exposed'; END IF;
 UPDATE public."HomePostcardRequestCommand" SET intent_hash=repeat('f',64) WHERE postcard_id=card_id;
 r:=public.get_home_postcard_current_status(h,a);
 IF r->'request' IS DISTINCT FROM 'null'::jsonb THEN RAISE EXCEPTION 'Unbound destination was exposed as confirmed'; END IF;
END;
$$;
DO $$
DECLARE
 h uuid:='ddc24700-0000-4000-8000-000000000100'; a uuid:='ddc24700-0000-4000-8000-000000000002';
 card_id uuid:='ddc24700-0000-4000-8000-000000002007'; r jsonb;
 address jsonb:=jsonb_build_object('line1','Postal policy fixture','line2','999','city','Test','state','WA','postal_code','98607','country','US');
BEGIN
 r:=public.record_home_postcard_current_dispatch(h,a,card_id,'rejected',NULL);
 IF r->>'ok' IS DISTINCT FROM 'true' OR (SELECT dispatch_status FROM public."HomePostcardCode" WHERE id=card_id)<>'accepted' THEN
 RAISE EXCEPTION 'Late receipt overwrote a known webhook acceptance'; END IF;
 UPDATE public."HomePostcardCode" SET dispatch_status='dispatching',vendor_job_id=NULL,status='verified' WHERE id=card_id;
 PERFORM public.record_home_postcard_current_dispatch(h,a,card_id,'rejected',NULL);
 IF NOT EXISTS(SELECT FROM public."HomePostcardCode" WHERE id=card_id AND status='verified' AND dispatch_status='rejected') THEN
 RAISE EXCEPTION 'Transport refusal undid a recorded verification'; END IF;
 INSERT INTO public."HomePostcardCode"(id,home_id,user_id,code_hash,dispatch_status,destination) VALUES
 ('ddc24700-0000-4000-8000-000000003001',h,'ddc24700-0000-4000-8000-000000000001',repeat('f',64),'delivery_unknown','{}'),
 ('ddc24700-0000-4000-8000-000000003002',h,'ddc24700-0000-4000-8000-000000000003',repeat('f',64),'delivery_unknown','{}');
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001010',address,
   'ddc24700-0000-4000-8000-000000002010',repeat('f',64),'fixture');
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_ADDRESS_LIMIT' OR r->>'state' IS DISTINCT FROM 'rejected' THEN
 RAISE EXCEPTION 'Concurrent Home mail budget was not enforced'; END IF;
 UPDATE public."HomePostcardCode" SET status='expired' WHERE home_id=h AND user_id<>a;
 INSERT INTO public."HomePostcardCode"(id,home_id,user_id,code_hash,status,dispatch_status,destination) VALUES
 ('ddc24700-0000-4000-8000-000000003003',h,a,repeat('f',64),'expired','delivery_unknown','{}');
 r:=public.begin_home_postcard_request(h,a,'ddc24700-0000-4000-8000-000000001011',address,
   'ddc24700-0000-4000-8000-000000002011',repeat('f',64),'fixture');
 IF r->>'code' IS DISTINCT FROM 'POSTCARD_USER_LIMIT' OR r->>'state' IS DISTINCT FROM 'rejected' THEN
 RAISE EXCEPTION 'Concurrent personal mail budget was not enforced'; END IF;
 IF EXISTS(SELECT FROM public."HomePostcardCode" WHERE id IN ('ddc24700-0000-4000-8000-000000002010','ddc24700-0000-4000-8000-000000002011')) THEN
 RAISE EXCEPTION 'Refused budget left a partial proof'; END IF;
END;
$$;
RESET ROLE;
DO $$ DECLARE fn record; BEGIN
 IF has_table_privilege('authenticated','public."HomePostcardRequestCommand"','SELECT')
 OR has_table_privilege('anon','public."HomePostcardRequestCommand"','INSERT') THEN RAISE EXCEPTION 'Postal command table is exposed'; END IF;
 FOR fn IN SELECT oid FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN
 ('get_home_postcard_request','cancel_home_postcard_request','get_home_postcard_current_status','claim_home_postcard_current_dispatch','record_home_postcard_current_dispatch','begin_home_postcard_request','home_postcard_request_work','home_postcard_confirmed_address') LOOP
 IF has_function_privilege('authenticated',fn.oid,'EXECUTE') OR has_function_privilege('anon',fn.oid,'EXECUTE')
 OR NOT has_function_privilege('service_role',fn.oid,'EXECUTE') THEN RAISE EXCEPTION 'Postal worker function is exposed'; END IF;
 END LOOP;
END $$;

$contract$, 'home-postcard-current-recovery.sql');
SELECT * FROM finish();
ROLLBACK;
