-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-task-collection-capabilities.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Collection capability is the current transaction's creation authorization,
-- including empty collections and the exact private-creator exception.
-- Test-only grants and every synthetic row are rolled back.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
CREATE TEMP TABLE collection_roles_before AS
 SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) rows FROM public."HomeRolePermission" r;
INSERT INTO auth.users(id,email) SELECT ('ddf15000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
 'collection-'||n||'@example.invalid' FROM generate_series(1,8)n;
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'collection_fixture_'||right(id::text,1),'Collection fixture'
 FROM auth.users WHERE id::text LIKE 'ddf15000-0000-4000-8000-%';
INSERT INTO public."Home"(id,owner_id,created_by_user_id,address,city,state,zipcode) VALUES
 ('ddf15000-0000-4000-8000-000000000100','ddf15000-0000-4000-8000-000000000001','ddf15000-0000-4000-8000-000000000001','Collection 100','Test','WA','98607'),
 ('ddf15000-0000-4000-8000-000000000200',NULL,'ddf15000-0000-4000-8000-000000000008','Collection 200','Test','WA','98607');
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status)
 SELECT 'ddf15000-0000-4000-8000-000000000100',('ddf15000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
 role,role::public.home_role_base,age::public.home_age_band,status FROM
 (VALUES(1,'owner','adult','verified'),(2,'member','adult','verified'),(3,'member',NULL,'verified'),
   (4,'member','adult','pending_doc'),(5,'restricted_member','child','verified'),(6,NULL,'adult','verified'),(7,'member','teen','verified'))f(n,role,age,status);
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,verification_status) VALUES
 ('ddf15000-0000-4000-8000-000000000200','ddf15000-0000-4000-8000-000000000008','admin','admin','pending_doc');
INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed)
 SELECT 'ddf15000-0000-4000-8000-000000000100',('ddf15000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,p::public.home_permission,true
 FROM generate_series(2,7)n CROSS JOIN unnest(ARRAY['tasks.view','tasks.edit','tasks.manage'])p
 WHERE n<>2 OR p='tasks.view';
CREATE FUNCTION pg_temp.collection_ok(r jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Expected success, got %',r; END IF; RETURN r; END $$;
CREATE FUNCTION pg_temp.collection_code(r jsonb,c text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'false' OR r->>'code' IS DISTINCT FROM c THEN RAISE EXCEPTION 'Expected %, got %',c,r; END IF; END $$;
CREATE FUNCTION pg_temp.collection_capability(h uuid,u uuid,want boolean) RETURNS jsonb LANGUAGE plpgsql AS $$ DECLARE r jsonb; BEGIN
 r:=pg_temp.collection_ok(public.get_home_records(h,u,'task'));
 IF r->'can_create' IS DISTINCT FROM to_jsonb(want) THEN RAISE EXCEPTION 'Expected creation %, got %',want,r; END IF;
 RETURN r; END $$;
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf15000-0000-4000-8000-000000000100'; ph uuid:='ddf15000-0000-4000-8000-000000000200';
 o uuid:='ddf15000-0000-4000-8000-000000000001'; viewer uuid:='ddf15000-0000-4000-8000-000000000002';
 historical uuid:='ddf15000-0000-4000-8000-000000000003'; minor uuid:='ddf15000-0000-4000-8000-000000000005';
 teen uuid:='ddf15000-0000-4000-8000-000000000007'; priv uuid:='ddf15000-0000-4000-8000-000000000008';
 r jsonb; t uuid; state text; k text; n integer;
BEGIN
 -- Empty collections must not infer creation from the presence of an item.
 r:=pg_temp.collection_capability(h,o,true);
 IF jsonb_array_length(r->'records')<>0 THEN RAISE EXCEPTION 'Fixture collection is not empty'; END IF;
 PERFORM pg_temp.collection_capability(h,viewer,false);
 PERFORM pg_temp.collection_code(public.mutate_home_record(h,viewer,'task','create',NULL,'{"title":"Read-only write"}'),'HOME_RECORD_WRITE_DENIED');
 PERFORM pg_temp.collection_ok(public.mutate_home_record(h,o,'task','create',NULL,'{"title":"Owner task"}'));
 PERFORM pg_temp.collection_capability(h,viewer,false);
 -- Exact explicit denial also constrains a verified owner.
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,o,'tasks.edit',false),(h,o,'tasks.manage',false);
 PERFORM pg_temp.collection_capability(h,o,false);
 PERFORM pg_temp.collection_code(public.mutate_home_record(h,o,'task','create',NULL,'{"title":"Denied owner write"}'),'HOME_RECORD_WRITE_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=o;
 -- Child hard ceilings survive both manage grants and owner status.
 PERFORM pg_temp.collection_capability(h,minor,false);
 PERFORM pg_temp.collection_code(public.mutate_home_record(h,minor,'task','create',NULL,'{"title":"Child write"}'),'HOME_RECORD_WRITE_DENIED');
 UPDATE public."HomeOccupancy" SET age_band='child' WHERE home_id=h AND user_id=o;
 PERFORM pg_temp.collection_capability(h,o,false);
 PERFORM pg_temp.collection_code(public.mutate_home_record(h,o,'task','create',NULL,'{"title":"Child owner write"}'),'HOME_RECORD_WRITE_DENIED');
 UPDATE public."HomeOccupancy" SET age_band='adult' WHERE home_id=h AND user_id=o;
 -- Explicit teen and historical unknown-age rights retain shipped behavior.
 PERFORM pg_temp.collection_capability(h,teen,true);
 PERFORM pg_temp.collection_ok(public.mutate_home_record(h,teen,'task','create',NULL,'{"title":"Teen task"}'));
 PERFORM pg_temp.collection_capability(h,historical,true);
 PERFORM pg_temp.collection_ok(public.mutate_home_record(h,historical,'task','create',NULL,'{"title":"Historical task"}'));
 -- An editor or manager grant independently matches the existing create rule.
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,viewer,'tasks.edit',true);
 PERFORM pg_temp.collection_capability(h,viewer,true);
 PERFORM pg_temp.collection_ok(public.mutate_home_record(h,viewer,'task','create',NULL,'{"title":"Editor task"}'));
 UPDATE public."HomePermissionOverride" SET allowed=false WHERE home_id=h AND user_id=viewer AND permission='tasks.edit';
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,viewer,'tasks.manage',true);
 PERFORM pg_temp.collection_capability(h,viewer,true);
 PERFORM pg_temp.collection_ok(public.mutate_home_record(h,viewer,'task','create',NULL,'{"title":"Manager task"}'));
 UPDATE public."HomePermissionOverride" SET allowed=false WHERE home_id=h AND user_id=viewer AND permission='tasks.view';
 PERFORM pg_temp.collection_code(public.get_home_records(h,viewer,'task'),'HOME_RECORD_DENIED');
 PERFORM pg_temp.collection_code(public.mutate_home_record(h,viewer,'task','create',NULL,'{"title":"No view write"}'),'HOME_RECORD_DENIED');
 -- Revocation, unknown roles, and elapsed/future windows deny the entire read.
 PERFORM pg_temp.collection_code(public.get_home_records(h,'ddf15000-0000-4000-8000-000000000004','task'),'HOME_RECORD_DENIED');
 PERFORM pg_temp.collection_code(public.get_home_records(h,'ddf15000-0000-4000-8000-000000000006','task'),'HOME_RECORD_DENIED');
 FOREACH state IN ARRAY ARRAY['pending_doc','revoked','suspended',NULL] LOOP
  UPDATE public."HomeOccupancy" SET verification_status=state WHERE home_id=h AND user_id=historical;
  PERFORM pg_temp.collection_code(public.get_home_records(h,historical,'task'),'HOME_RECORD_DENIED');
 END LOOP;
 UPDATE public."HomeOccupancy" SET verification_status='verified' WHERE home_id=h AND user_id=historical;
 FOREACH k IN ARRAY ARRAY['start_at','access_start_at','end_at','access_end_at'] LOOP
  EXECUTE format('UPDATE public."HomeOccupancy" SET %I=clock_timestamp()+$3 WHERE home_id=$1 AND user_id=$2',k)
    USING h,historical,CASE WHEN k IN ('start_at','access_start_at') THEN interval '1 hour' ELSE interval '-1 hour' END;
  PERFORM pg_temp.collection_code(public.get_home_records(h,historical,'task'),'HOME_RECORD_DENIED');
  EXECUTE format('UPDATE public."HomeOccupancy" SET %I=NULL WHERE home_id=$1 AND user_id=$2',k) USING h,historical;
 END LOOP;
 -- The sole private creator still gets their own first-use tasks despite /me.
 IF public.home_effective_access(ph,priv)->>'has_access'='true' THEN RAISE EXCEPTION 'Private fixture unexpectedly has household access'; END IF;
 r:=pg_temp.collection_capability(ph,priv,true);
 IF jsonb_array_length(r->'records')<>0 THEN RAISE EXCEPTION 'Private empty collection was not empty'; END IF;
 r:=pg_temp.collection_ok(public.mutate_home_record(ph,priv,'task','create',NULL,'{"title":"Private own task"}')); t:=(r->'record'->>'id')::uuid;
 r:=pg_temp.collection_capability(ph,priv,true);
 IF r->'records'->0->>'id'<>t::text OR public.home_record_context(ph,priv)->>'private'<>'true' THEN RAISE EXCEPTION 'Private task identity lost'; END IF;
 PERFORM pg_temp.collection_code(public.get_home_records(ph,o,'task'),'HOME_RECORD_DENIED');
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed,created_by) VALUES(ph,priv,'tasks.edit',false,priv),(ph,priv,'tasks.manage',false,priv);
 PERFORM pg_temp.collection_capability(ph,priv,false);
 PERFORM pg_temp.collection_code(public.mutate_home_record(ph,priv,'task','create',NULL,'{"title":"Private denied task"}'),'HOME_RECORD_WRITE_DENIED');
END $$;
RESET ROLE;
DO $$ BEGIN
 IF has_function_privilege('authenticated','public.get_home_records(uuid,uuid,text,uuid,timestamptz,timestamptz,boolean)','EXECUTE')
  OR has_function_privilege('anon','public.get_home_records(uuid,uuid,text,uuid,timestamptz,timestamptz,boolean)','EXECUTE')
  OR NOT has_function_privilege('service_role','public.get_home_records(uuid,uuid,text,uuid,timestamptz,timestamptz,boolean)','EXECUTE') THEN RAISE EXCEPTION 'Unsafe collection RPC grant'; END IF;
 IF (SELECT rows FROM collection_roles_before) IS DISTINCT FROM (SELECT jsonb_agg(to_jsonb(r) ORDER BY role_base,permission) FROM public."HomeRolePermission" r) THEN RAISE EXCEPTION 'Role defaults changed'; END IF;
END $$;

$contract$, 'home-task-collection-capabilities.sql');
SELECT * FROM finish();
ROLLBACK;
