-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-policy-boundary.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Preserve production's stricter Home boundary during baseline reconciliation.
-- The backend owns creator onboarding and verified-primary-owner deletion.
-- Direct Home DML goes through the authenticated backend transaction; neither
-- an editor nor an owner may forge pointer/provenance or bypass deletion guards.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
SET LOCAL search_path = public, extensions, pg_catalog;

INSERT INTO auth.users (id, email)
SELECT id, 'home-policy-' || n || '@example.invalid'
FROM (VALUES
  ('ddd00000-0000-4000-8000-000000000001'::uuid, 1),
  ('ddd00000-0000-4000-8000-000000000002'::uuid, 2),
  ('ddd00000-0000-4000-8000-000000000003'::uuid, 3)
) users(id, n);
INSERT INTO public."User" (id, email, username, name)
SELECT id, email, 'home_policy_' || right(id::text, 1), 'Home policy fixture'
FROM auth.users WHERE id IN (
  'ddd00000-0000-4000-8000-000000000001', 'ddd00000-0000-4000-8000-000000000002',
  'ddd00000-0000-4000-8000-000000000003');
INSERT INTO public."Home" (id, owner_id, created_by_user_id, address, city, state, zipcode)
VALUES ('ddd00000-0000-4000-8000-000000000010', 'ddd00000-0000-4000-8000-000000000001',
        'ddd00000-0000-4000-8000-000000000003', '100 Synthetic Street', 'Test City', 'WA', '98607');
INSERT INTO public."HomeOccupancy" (home_id, user_id, role, role_base, is_active, verification_status)
VALUES ('ddd00000-0000-4000-8000-000000000010', 'ddd00000-0000-4000-8000-000000000002',
        'admin', 'admin', true, 'verified');
-- Isolate the policy behavior from the incomplete historical reference matrix.
INSERT INTO public."HomeRolePermission" (role_base, permission, allowed)
VALUES ('admin', 'home.edit', true)
ON CONFLICT (role_base, permission) DO UPDATE SET allowed = true;

SET LOCAL ROLE anon;
-- Since 20260930181000 anon holds no privilege on public tables, so the grant
-- refuses the read before row-level security is consulted.
DO $$ BEGIN
  BEGIN
    PERFORM 1 FROM public."Home" WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'Anonymous role can read a private home';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;

SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub', 'ddd00000-0000-4000-8000-000000000003', true);
-- Since 20260930182000 authenticated holds no privilege on public tables, so the grant refuses
-- every direct read. The read policy (home_is_active_member(id) OR owner) is kept as defense in
-- depth, and its predicate is asserted through the same helper for each person.
DO $$ BEGIN
  BEGIN
    PERFORM 1 FROM public."Home" WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'Nonmember creator can read an established private home directly';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  IF public.home_is_active_member('ddd00000-0000-4000-8000-000000000010') THEN
    RAISE EXCEPTION 'Nonmember creator counts as an active member of an established private home';
  END IF;
END $$;

SELECT set_config('request.jwt.claim.sub', 'ddd00000-0000-4000-8000-000000000002', true);
DO $$
DECLARE affected integer;
BEGIN
  BEGIN
    PERFORM 1 FROM public."Home" WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'Active member read their home directly';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  IF NOT public.home_is_active_member('ddd00000-0000-4000-8000-000000000010') THEN
    RAISE EXCEPTION 'Active member lost the membership the Home read policy admits';
  END IF;
  BEGIN
    UPDATE public."Home" SET name = 'Edited by fixture'
      WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'Editor bypassed API Home update boundary';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
  BEGIN
    DELETE FROM public."Home" WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'home.edit allowed direct deletion';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;

SELECT set_config('request.jwt.claim.sub', 'ddd00000-0000-4000-8000-000000000001', true);
DO $$
DECLARE affected integer;
BEGIN
  BEGIN
    DELETE FROM public."Home" WHERE id = 'ddd00000-0000-4000-8000-000000000010';
    RAISE EXCEPTION 'Primary legacy owner bypassed atomic deletion guards';
  EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SELECT 'PASS: direct Home reads refused, the read policy''s member predicate kept, API-only Home authority/deletion mutations' AS result;

$contract$, 'home-policy-boundary.sql');
SELECT * FROM finish();
ROLLBACK;
