-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/home-task-media-transactions.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Local synthetic metadata only; provider bytes are exercised separately.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
INSERT INTO auth.users(id,email) SELECT ('ddf10001-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
 'task-media-'||n||'@example.invalid' FROM generate_series(1,4)n;
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'task_media_'||right(id::text,1),'Task media fixture'
 FROM auth.users WHERE id::text LIKE 'ddf10001-0000-4000-8000-%';
INSERT INTO public."Home"(id,owner_id,created_by_user_id,address,city,state,zipcode)
 VALUES('ddf10001-0000-4000-8000-000000000100','ddf10001-0000-4000-8000-000000000001','ddf10001-0000-4000-8000-000000000001','Media home','Test','WA','98607');
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status)
 SELECT 'ddf10001-0000-4000-8000-000000000100',('ddf10001-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,
 role,role::public.home_role_base,'adult','verified' FROM (VALUES(1,'owner'),(2,'member'),(3,'member'),(4,NULL))f(n,role);
INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed)
 SELECT 'ddf10001-0000-4000-8000-000000000100',('ddf10001-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,p::public.home_permission,true
 FROM generate_series(2,4)n CROSS JOIN unnest(ARRAY['tasks.view','tasks.edit'])p;
INSERT INTO public."HomeTask"(id,home_id,created_by,title,task_type,assigned_to) VALUES
 ('ddf10001-0000-4000-8000-000000000200','ddf10001-0000-4000-8000-000000000100','ddf10001-0000-4000-8000-000000000001',
 'Private attachment fixture','chore','ddf10001-0000-4000-8000-000000000002');
CREATE FUNCTION pg_temp.media_ok(r jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'true' THEN RAISE EXCEPTION 'Expected success, got %',r; END IF; RETURN r; END $$;
CREATE FUNCTION pg_temp.media_code(r jsonb,c text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF r->>'ok' IS DISTINCT FROM 'false' OR r->>'code' IS DISTINCT FROM c THEN RAISE EXCEPTION 'Expected %, got %',c,r; END IF; END $$;
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf10001-0000-4000-8000-000000000100'; t uuid:='ddf10001-0000-4000-8000-000000000200';
 o uuid:='ddf10001-0000-4000-8000-000000000001'; a uuid:='ddf10001-0000-4000-8000-000000000002';
 u uuid:='ddf10001-0000-4000-8000-000000000300'; v uuid:='ddf10001-0000-4000-8000-000000000301';
 p jsonb:='{"bucket":"private-task-fixture","sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","file_name":"exact.txt","mime_type":"text/plain","file_size":4}';
 r jsonb; before_quota jsonb; oldclaim uuid; attempt uuid; state text;
BEGIN
 PERFORM pg_temp.media_code(public.authorize_home_task_media(h,t,a,true),'HOME_RECORD_WRITE_DENIED');
 PERFORM pg_temp.media_ok(public.authorize_home_task_media(h,t,a,false));
 PERFORM pg_temp.media_code(public.authorize_home_task_media(h,t,'ddf10001-0000-4000-8000-000000000004',false),'HOME_RECORD_DENIED');
 PERFORM pg_temp.media_code(public.authorize_home_task_media(gen_random_uuid(),t,o,false),'HOME_NOT_FOUND');
 PERFORM pg_temp.media_code(public.authorize_home_task_media(h,gen_random_uuid(),o,false),'HOME_RECORD_NOT_FOUND');
 r:=pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'reserve',u,p));
 IF r->'record'->>'state'<>'reserved' OR (SELECT storage_used FROM public."FileQuota" WHERE user_id=o)<>4
  OR (SELECT file_count FROM public."FileQuota" WHERE user_id=o)<>1 THEN RAISE EXCEPTION 'Reservation did not charge exact quota'; END IF;
 SELECT to_jsonb(q) INTO before_quota FROM public."FileQuota" q WHERE user_id=o;
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'reserve',u,p));
 IF before_quota IS DISTINCT FROM (SELECT to_jsonb(q) FROM public."FileQuota" q WHERE user_id=o) THEN RAISE EXCEPTION 'Retry charged quota twice'; END IF;
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'reserve',u,p||'{"file_name":"changed.txt"}'),'HOME_TASK_UPLOAD_CONFLICT');
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'reserve',v,p||'{"file_size":0}'),'HOME_RECORD_INVALID');
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'finalize',u),'HOME_TASK_UPLOAD_CONFLICT');
 r:=pg_temp.media_ok(public.get_home_task_media(h,t,a));
 IF jsonb_array_length(r->'records')<>0 THEN RAISE EXCEPTION 'Pending upload visible to another reader'; END IF;
 -- Generic own-file removal cannot bypass the task retirement transaction.
 IF public.soft_delete_file(u,o)->>'success' IS DISTINCT FROM 'false' THEN RAISE EXCEPTION 'Generic deletion bypassed task authority'; END IF;
 IF before_quota IS DISTINCT FROM (SELECT to_jsonb(q) FROM public."FileQuota" q WHERE user_id=o) THEN RAISE EXCEPTION 'Failed generic delete changed quota'; END IF;
 r:=pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'begin_upload',u)); attempt:=(r->'storage'->>'upload_attempt')::uuid;
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'finalize',u));
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'finalize',u));
 IF (SELECT count(*) FROM public."HomeTaskMedia" WHERE private_upload_id=u)<>1 THEN RAISE EXCEPTION 'Duplicate publish'; END IF;
 r:=pg_temp.media_ok(public.get_home_task_media(h,t,a,u));
 IF r->'records'->0->>'available'<>'true' OR r->'records'->0 ?| ARRAY['file_url','file_key','storage_bucket','sha256'] THEN RAISE EXCEPTION 'Unsafe metadata DTO'; END IF;
 IF EXISTS(SELECT FROM public."HomeTaskMedia" WHERE id=u AND (file_url<>'' OR file_key<>'' OR thumbnail_url IS NOT NULL)) THEN RAISE EXCEPTION 'Public URL retained for new attachment'; END IF;
 UPDATE public."HomePermissionOverride" SET allowed=false WHERE home_id=h AND user_id=a AND permission='tasks.view';
 PERFORM pg_temp.media_code(public.get_home_task_media(h,t,a,u),'HOME_RECORD_DENIED');
 UPDATE public."HomePermissionOverride" SET allowed=true WHERE home_id=h AND user_id=a AND permission='tasks.view';
 FOREACH state IN ARRAY ARRAY['pending_doc','revoked','suspended',NULL] LOOP
  UPDATE public."HomeOccupancy" SET verification_status=state WHERE home_id=h AND user_id=a;
  PERFORM pg_temp.media_code(public.get_home_task_media(h,t,a,u),'HOME_RECORD_DENIED');
 END LOOP;
 UPDATE public."HomeOccupancy" SET verification_status='verified' WHERE home_id=h AND user_id=a;
 UPDATE public."HomeTask" SET visibility='sensitive' WHERE id=t;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed) VALUES(h,o,'sensitive.view',false);
 PERFORM pg_temp.media_code(public.get_home_task_media(h,t,o,u),'HOME_RECORD_DENIED');
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'retire',u),'HOME_RECORD_DENIED');
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=o AND permission='sensitive.view';
 UPDATE public."HomeTask" SET visibility='members' WHERE id=t;
 r:=pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'retire',u)); oldclaim:=(r->'storage'->>'cleanup_claim')::uuid;
 IF EXISTS(SELECT FROM public."HomeTaskMedia" WHERE id=u) OR (SELECT storage_used FROM public."FileQuota" WHERE user_id=o)<>0 THEN RAISE EXCEPTION 'Retirement did not hide/release once'; END IF;
 PERFORM pg_temp.media_code(public.get_home_task_media(h,t,o,u),'HOME_TASK_MEDIA_NOT_FOUND');
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'reserve',u,p),'HOME_TASK_UPLOAD_RETIRED');
 PERFORM pg_temp.media_code(public.mutate_home_task_media(h,t,o,'finalize',u),'HOME_TASK_UPLOAD_RETIRED');
 PERFORM public.note_home_task_media_upload_finished(u,attempt);
 PERFORM pg_temp.media_code(public.delete_home_task_after_media(h,t,o),'HOME_TASK_MEDIA_CLEANUP_REQUIRED');
 IF public.finish_home_task_media_cleanup(u,oldclaim,true) THEN RAISE EXCEPTION 'Late upload accepted stale cleanup ack'; END IF;
 r:=pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'retire',u));
 IF NOT public.finish_home_task_media_cleanup(u,(r->'storage'->>'cleanup_claim')::uuid,true) THEN RAISE EXCEPTION 'Exact cleanup ack failed'; END IF;
 IF (SELECT file_count FROM public."FileQuota" WHERE user_id=o)<>0 THEN RAISE EXCEPTION 'Retirement retry changed quota'; END IF;
 -- Actual reservation failure rolls back both intent and File.
 UPDATE public."FileQuota" SET storage_limit=0 WHERE user_id=o;
 BEGIN PERFORM public.mutate_home_task_media(h,t,o,'reserve',v,p); RAISE EXCEPTION 'Quota limit bypass';
 EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'FILE_QUOTA_EXCEEDED' THEN RAISE; END IF; END;
 IF EXISTS(SELECT FROM public."File" WHERE id=v) OR EXISTS(SELECT FROM public."HomeTaskMediaIntent" WHERE id=v) THEN RAISE EXCEPTION 'Failed quota left reservation'; END IF;
 UPDATE public."FileQuota" SET storage_limit=1073741824 WHERE user_id=o;
 -- Task deletion preserves original receipt identity and nullable live links.
 PERFORM pg_temp.media_ok(public.delete_home_task_after_media(h,t,o));
 IF NOT EXISTS(SELECT FROM public."HomeTaskMediaIntent" WHERE id=u AND task_id IS NULL AND original_task_id=t) THEN RAISE EXCEPTION 'Deleted task lost cleanup identity'; END IF;
 BEGIN UPDATE public."HomeTaskMediaIntent" SET original_task_id=gen_random_uuid() WHERE id=u;
  RAISE EXCEPTION 'Upload identity changed'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN DELETE FROM public."File" WHERE id=u; RAISE EXCEPTION 'Task File tombstone deleted'; EXCEPTION WHEN check_violation THEN NULL; END;
 BEGIN DELETE FROM public."HomeTaskMediaIntent" WHERE id=u; RAISE EXCEPTION 'Task intent tombstone deleted'; EXCEPTION WHEN check_violation THEN NULL; END;
END $$;
RESET ROLE;
-- Exact creator first-use survives its protected upload lifecycle. A task-only
-- Home can retire bytes, but legacy/evidence/document history is never detached.
INSERT INTO public."Home"(id,owner_id,created_by_user_id,address,city,state,zipcode)
 VALUES('ddf10001-0000-4000-8000-000000000110','ddf10001-0000-4000-8000-000000000001','ddf10001-0000-4000-8000-000000000001','Private media setup','Test','WA','98607');
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,age_band,verification_status)
 VALUES('ddf10001-0000-4000-8000-000000000110','ddf10001-0000-4000-8000-000000000001','owner','owner','adult','provisional_bootstrap');
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf10001-0000-4000-8000-000000000110'; o uuid:='ddf10001-0000-4000-8000-000000000001';
 t uuid; u uuid:='ddf10001-0000-4000-8000-000000000310'; legacy uuid:='ddf10001-0000-4000-8000-000000000311'; r jsonb;
 p jsonb:='{"bucket":"private-task-fixture","sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","file_name":"own.txt","mime_type":"text/plain","file_size":4}';
BEGIN
 r:=pg_temp.media_ok(public.mutate_home_record(h,o,'task','create',NULL,'{"title":"Own first-use task","task_type":"chore"}'));
 t:=(r->'record'->>'id')::uuid;
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'reserve',u,p));
 IF NOT (SELECT private_setup FROM public."HomeTaskMediaIntent" WHERE id=u)
  OR public.home_secret_context(h,o)->>'allowed'<>'true' THEN RAISE EXCEPTION 'Own reservation lost private setup'; END IF;
 BEGIN UPDATE public."HomeTaskMediaIntent" SET private_setup=false WHERE id=u;
  RAISE EXCEPTION 'Private upload provenance changed'; EXCEPTION WHEN check_violation THEN NULL; END;
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'begin_upload',u));
 PERFORM pg_temp.media_ok(public.mutate_home_task_media(h,t,o,'finalize',u));
 r:=pg_temp.media_ok(public.get_home_records(h,o,'task',t));
 IF r->'records'->0->'media'->0->>'available'<>'true'
  OR r->'records'->0->'capabilities'->>'can_upload'<>'true'
  OR r->'records'->0->'capabilities'->>'can_delete'<>'true'
  OR r->'records'->0->'media'->0 ?| ARRAY['file_url','file_key','file_path','sha256'] THEN RAISE EXCEPTION 'Dashboard media projection incomplete/unsafe'; END IF;
 INSERT INTO public."HomePermissionOverride"(home_id,user_id,permission,allowed,created_by) VALUES(h,o,'tasks.view',false,o);
 IF public.prepare_home_task_media_home_delete(h,o)->>'allowed'<>'false'
  OR (SELECT state FROM public."HomeTaskMediaIntent" WHERE id=u)<>'ready' THEN RAISE EXCEPTION 'Home delete bypassed task deny'; END IF;
 DELETE FROM public."HomePermissionOverride" WHERE home_id=h AND user_id=o AND permission='tasks.view';
 INSERT INTO public."File"(id,user_id,home_id,filename,original_filename,file_path,file_url,file_size,mime_type,file_extension,file_type,visibility)
  VALUES(legacy,o,h,'legacy','legacy','legacy/private-test','https://invalid.example/legacy',1,'text/plain','txt','other','private');
 r:=public.prepare_home_task_media_home_delete(h,o);
 IF r->>'code'<>'HOME_DELETE_STORAGE_CLEANUP_REQUIRED' OR (SELECT state FROM public."HomeTaskMediaIntent" WHERE id=u)<>'ready'
  THEN RAISE EXCEPTION 'Legacy storage was detached or task retired before full eligibility'; END IF;
 PERFORM public.soft_delete_file(legacy,o); DELETE FROM public."File" WHERE id=legacy;
 IF public.delete_home_authorized(h,o)->>'code'<>'HOME_DELETE_TASK_MEDIA_CLEANUP_REQUIRED' THEN RAISE EXCEPTION 'Home deleted before real retirement'; END IF;
 r:=public.prepare_home_task_media_home_delete(h,o);
 IF r->>'allowed'<>'true' OR jsonb_array_length(r->'cleanup')<>1 THEN RAISE EXCEPTION 'Private Home retirement unavailable: %',r; END IF;
 IF public.delete_home_authorized(h,o)->>'code'<>'HOME_DELETE_TASK_MEDIA_CLEANUP_REQUIRED' THEN RAISE EXCEPTION 'Home deleted before cleanup acknowledgement'; END IF;
 IF NOT public.finish_home_task_media_cleanup(u,(r->'cleanup'->0->>'cleanup_claim')::uuid,true) THEN RAISE EXCEPTION 'Private cleanup ack failed'; END IF;
 IF public.home_secret_context(h,o)->>'allowed'<>'true' THEN RAISE EXCEPTION 'Own retirement lost private setup'; END IF;
END $$;
RESET ROLE;
CREATE FUNCTION pg_temp.task_home_delete_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic Home deletion rollback'; END $$;
CREATE TRIGGER task_home_delete_failure BEFORE DELETE ON public."Home" FOR EACH ROW
 WHEN (OLD.id='ddf10001-0000-4000-8000-000000000110') EXECUTE FUNCTION pg_temp.task_home_delete_failure();
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf10001-0000-4000-8000-000000000110'; o uuid:='ddf10001-0000-4000-8000-000000000001';
BEGIN
 IF public.delete_home_authorized(h,o)->>'code'<>'HOME_DELETE_FAILED' THEN RAISE EXCEPTION 'Downstream delete did not fail'; END IF;
 IF NOT EXISTS(SELECT FROM public."File" WHERE id='ddf10001-0000-4000-8000-000000000310' AND home_id=h)
  OR NOT EXISTS(SELECT FROM public."HomeTaskMediaIntent" WHERE id='ddf10001-0000-4000-8000-000000000310' AND home_id=h)
  THEN RAISE EXCEPTION 'Failed Home delete left detached storage provenance'; END IF;
END $$;
RESET ROLE;
DROP TRIGGER task_home_delete_failure ON public."Home";
SET LOCAL ROLE service_role;
DO $$ DECLARE h uuid:='ddf10001-0000-4000-8000-000000000110'; o uuid:='ddf10001-0000-4000-8000-000000000001';
BEGIN
 IF public.delete_home_authorized(h,o)->>'deleted'<>'true' THEN RAISE EXCEPTION 'Retired private Home could not delete'; END IF;
 IF NOT EXISTS(SELECT FROM public."HomeTaskMediaIntent" WHERE id='ddf10001-0000-4000-8000-000000000310'
  AND original_home_id=h AND home_id IS NULL AND task_id IS NULL AND state='retired' AND NOT cleanup_pending)
  OR NOT EXISTS(SELECT FROM public."File" WHERE id='ddf10001-0000-4000-8000-000000000310' AND home_id IS NULL AND is_deleted)
  THEN RAISE EXCEPTION 'Home cascade destroyed exact cleanup tombstones'; END IF;
END $$;
RESET ROLE;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','ddf10001-0000-4000-8000-000000000001',true);
DO $$ BEGIN
 IF EXISTS(SELECT FROM public."File" WHERE id='ddf10001-0000-4000-8000-000000000300') THEN RAISE EXCEPTION 'Direct own File SELECT leaked private attachment'; END IF;
END $$;
RESET ROLE;
DO $$ BEGIN
 IF has_table_privilege('authenticated','public."HomeTaskMediaIntent"','SELECT,INSERT,UPDATE,DELETE')
 OR has_table_privilege('anon','public."HomeTaskMediaIntent"','SELECT,INSERT,UPDATE,DELETE')
 OR has_function_privilege('authenticated','public.get_home_task_media(uuid,uuid,uuid,uuid)','EXECUTE')
 OR has_function_privilege('anon','public.mutate_home_task_media(uuid,uuid,uuid,text,uuid,jsonb)','EXECUTE')
 OR has_function_privilege('authenticated','public.prepare_home_task_media_home_delete(uuid,uuid)','EXECUTE')
 OR NOT has_function_privilege('service_role','public.mutate_home_task_media(uuid,uuid,uuid,text,uuid,jsonb)','EXECUTE') THEN
 RAISE EXCEPTION 'Unsafe direct API grants'; END IF;
END $$;
-- Protected private proof cannot be inferred merely from current authorship:
-- a formerly verified upload remains shared history after a status downgrade.
DELETE FROM public."HomeOccupancy" WHERE home_id='ddf10001-0000-4000-8000-000000000100'
 AND user_id<>'ddf10001-0000-4000-8000-000000000001';
DELETE FROM public."HomePermissionOverride" WHERE home_id='ddf10001-0000-4000-8000-000000000100';
DELETE FROM public."HomeAuditLog" WHERE home_id='ddf10001-0000-4000-8000-000000000100';
UPDATE public."HomeOccupancy" SET verification_status='pending_doc',verified_at=NULL
 WHERE home_id='ddf10001-0000-4000-8000-000000000100';
DO $$ DECLARE h uuid:='ddf10001-0000-4000-8000-000000000100'; o uuid:='ddf10001-0000-4000-8000-000000000001'; BEGIN
 IF public.home_secret_context(h,o)->>'allowed'<>'false'
  OR public.home_delete_eligibility(h,o)->>'code'<>'HOME_DELETE_ESTABLISHED_HOUSEHOLD' THEN
  RAISE EXCEPTION 'Formerly shared upload history became private setup'; END IF;
 UPDATE public."File" SET deleted_at=clock_timestamp()-interval '1 day' WHERE id IN
  ('ddf10001-0000-4000-8000-000000000300','ddf10001-0000-4000-8000-000000000310');
 PERFORM public.cleanup_old_deleted_files(0);
 IF (SELECT count(*) FROM public."File" WHERE id IN
  ('ddf10001-0000-4000-8000-000000000300','ddf10001-0000-4000-8000-000000000310'))<>2 THEN
  RAISE EXCEPTION 'Generic retention destroyed task recovery tombstones'; END IF;
END $$;
SELECT 'home-task-media-transactions PASS';

$contract$, 'home-task-media-transactions.sql');
SELECT * FROM finish();
ROLLBACK;
