-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/mail-verification-confirmation.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Actual PostgreSQL proof/unit/role transaction and rollback contract.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='30s';
INSERT INTO auth.users(id,email) VALUES
 ('eed00000-0000-4000-8000-000000000001','mail-unit-one@example.invalid'),
 ('eed00000-0000-4000-8000-000000000002','mail-unit-two@example.invalid');
INSERT INTO public."User"(id,email,username,name) SELECT id,email,'mail_unit_'||right(id::text,2),'Mail unit contract'
 FROM auth.users WHERE id IN ('eed00000-0000-4000-8000-000000000001','eed00000-0000-4000-8000-000000000002');
INSERT INTO public."HomeAddress"(id,address_line1_norm,city_norm,state,postal_code,address_hash,building_type,missing_secondary_flag)
 VALUES('eed00000-0000-4000-8000-000000000003','100 Synthetic St','Test','CA','00000','mail-unit-contract','multi_unit',true);
INSERT INTO public."Home"(id,address_id,address,address2,city,state,zipcode) VALUES
 ('eed00000-0000-4000-8000-000000000004','eed00000-0000-4000-8000-000000000003','100 Synthetic St','Apt 4','Test','CA','00000'),
 ('eed00000-0000-4000-8000-000000000005','eed00000-0000-4000-8000-000000000003','100 Synthetic St','Apt 5','Test','CA','00000');
INSERT INTO public."HomeOccupancy"(home_id,user_id,role,role_base,is_active,verification_status) VALUES
 ('eed00000-0000-4000-8000-000000000005','eed00000-0000-4000-8000-000000000002','member','member',true,'verified');
INSERT INTO public."AddressVerificationAttempt"(id,user_id,address_id,expires_at,status) VALUES
 ('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001','eed00000-0000-4000-8000-000000000003',now()+interval '1 day','sent');
INSERT INTO public."AddressVerificationToken"(attempt_id,code_hash) VALUES ('eed00000-0000-4000-8000-000000000006',repeat('a',64));
INSERT INTO public."MailVerificationJob"(attempt_id,vendor,vendor_status,metadata) VALUES
 ('eed00000-0000-4000-8000-000000000006','lob','sent',jsonb_build_object('unit','Unit 4','destination',
 jsonb_build_object('line1','100 Synthetic St','line2','Unit 4','city','Test','state','CA','zip','00000')));
INSERT INTO public."AddressClaim"(user_id,address_id,unit_number) VALUES
 ('eed00000-0000-4000-8000-000000000001','eed00000-0000-4000-8000-000000000003','4'),
 ('eed00000-0000-4000-8000-000000000001','eed00000-0000-4000-8000-000000000003','5');
CREATE FUNCTION pg_temp.mail_templates() RETURNS jsonb LANGUAGE sql AS $$ SELECT jsonb_build_object(
 'adult',jsonb_build_object('role_base','member','can_manage_home',false,'can_manage_access',false,'can_manage_finance',false,'can_manage_tasks',true,'can_view_sensitive',true),
 'child',jsonb_build_object('role_base','member','can_manage_home',false,'can_manage_access',false,'can_manage_finance',false,'can_manage_tasks',false,'can_view_sensitive',false),
 'teen',jsonb_build_object('role_base','member','can_manage_home',false,'can_manage_access',false,'can_manage_finance',false,'can_manage_tasks',true,'can_view_sensitive',false)); $$;
DO $$ BEGIN
 IF has_function_privilege('authenticated','public.confirm_mail_verification(uuid,uuid,text,jsonb,integer)','execute')
 OR has_function_privilege('anon','public.confirm_mail_verification(uuid,uuid,text,jsonb,integer)','execute')
 OR NOT has_function_privilege('service_role','public.confirm_mail_verification(uuid,uuid,text,jsonb,integer)','execute') THEN
  RAISE EXCEPTION 'Wrong modern confirmation grants'; END IF;
 IF public.mail_address_unit_key(' Apt. 4a ')<>'4A' OR public.mail_address_unit_key('Suite 4')=public.mail_address_unit_key('4')
 OR public.mail_address_unit_key('04')=public.mail_address_unit_key('4') THEN RAISE EXCEPTION 'Unsafe unit normalization'; END IF;
END $$;
SET LOCAL ROLE service_role;
DO $$ DECLARE r jsonb; BEGIN
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000002',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'NOT_FOUND' THEN RAISE EXCEPTION 'Foreign proof accepted'; END IF;
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('b',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'WRONG_CODE' OR r->>'attempts_remaining' IS DISTINCT FROM '4' THEN RAISE EXCEPTION 'Wrong guess did not count'; END IF;
END $$;
RESET ROLE;
CREATE FUNCTION pg_temp.reject_mail_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Mail contract audit failure'; END $$;
CREATE TRIGGER mail_contract_audit_failure BEFORE INSERT ON public."HomeAuditLog" FOR EACH ROW
 WHEN (NEW.action='MAIL_CODE_VERIFIED') EXECUTE FUNCTION pg_temp.reject_mail_audit();
SET LOCAL ROLE service_role;
DO $$ BEGIN
 BEGIN
  PERFORM public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
  RAISE EXCEPTION 'Missing expected rollback';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Mail contract audit failure' THEN RAISE; END IF; END;
 IF EXISTS(SELECT FROM public."HomeOccupancy" WHERE user_id='eed00000-0000-4000-8000-000000000001')
 OR EXISTS(SELECT FROM public."AddressVerificationToken" WHERE attempt_id='eed00000-0000-4000-8000-000000000006' AND (used_at IS NOT NULL OR attempt_count<>1))
 OR EXISTS(SELECT FROM public."AddressVerificationAttempt" WHERE id='eed00000-0000-4000-8000-000000000006' AND status<>'sent')
 OR EXISTS(SELECT FROM public."AddressClaim" WHERE user_id='eed00000-0000-4000-8000-000000000001' AND claim_status<>'pending') THEN
  RAISE EXCEPTION 'Partial state survived transaction failure'; END IF;
END $$;
RESET ROLE;
DROP TRIGGER mail_contract_audit_failure ON public."HomeAuditLog";
SET LOCAL ROLE service_role;
DO $$ DECLARE r jsonb; original jsonb; BEGIN
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 original:=r->'occupancy';
 IF original->>'home_id' IS DISTINCT FROM 'eed00000-0000-4000-8000-000000000004'
 OR original->>'role_base' IS DISTINCT FROM 'member' OR original->>'verification_status' IS DISTINCT FROM 'verified'
 OR (original->>'can_manage_home')::boolean OR (original->>'can_manage_access')::boolean OR (original->>'can_manage_finance')::boolean THEN
  RAISE EXCEPTION 'Wrong Home or excessive membership'; END IF;
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'reused' IS DISTINCT FROM 'true' OR r->'occupancy' IS DISTINCT FROM original THEN RAISE EXCEPTION 'Retry changed membership'; END IF;
 IF (SELECT attempt_count FROM public."AddressVerificationToken" WHERE attempt_id='eed00000-0000-4000-8000-000000000006')<>2
 OR (SELECT claim_status FROM public."AddressClaim" WHERE user_id='eed00000-0000-4000-8000-000000000001' AND unit_number='4')<>'verified'
 OR (SELECT claim_status FROM public."AddressClaim" WHERE user_id='eed00000-0000-4000-8000-000000000001' AND unit_number='5')<>'pending' THEN
  RAISE EXCEPTION 'Wrong attempt count or another apartment claim stamped'; END IF;
 UPDATE public."Home" SET address2='6' WHERE id='eed00000-0000-4000-8000-000000000004';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->'occupancy' IS NOT NULL THEN RAISE EXCEPTION 'Moved unit accepted old proof'; END IF;
 UPDATE public."Home" SET address2='4',security_state='frozen' WHERE id='eed00000-0000-4000-8000-000000000004';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'ACCESS_REVOKED' THEN RAISE EXCEPTION 'Frozen Home accepted'; END IF;
 UPDATE public."Home" SET security_state='normal' WHERE id='eed00000-0000-4000-8000-000000000004';
 UPDATE public."HomeOccupancy" SET is_active=false WHERE user_id='eed00000-0000-4000-8000-000000000001';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'ACCESS_REVOKED' OR EXISTS(SELECT FROM public."HomeOccupancy" WHERE user_id='eed00000-0000-4000-8000-000000000001' AND is_active) THEN
  RAISE EXCEPTION 'Retry revived removed membership'; END IF;
END $$;
-- Reuse only disposable rows to cover minor permissions, later household
-- authority, rejected claims and expiry without spending or consuming proof.
DO $$ DECLARE r jsonb; BEGIN
 UPDATE public."AddressVerificationAttempt" SET status='sent',expires_at=now()+interval '1 day' WHERE id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."AddressVerificationToken" SET used_at=NULL,attempt_count=0 WHERE attempt_id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."MailVerificationJob" SET metadata=metadata-'confirmed_home_id'-'confirmed_occupancy_id' WHERE attempt_id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."HomeOccupancy" SET is_active=true,verification_status='pending_postcard',role_base='restricted_member',age_band='child'
 WHERE user_id='eed00000-0000-4000-8000-000000000001';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->'occupancy'->>'role_base' IS DISTINCT FROM 'member' OR (r->'occupancy'->>'can_view_sensitive')::boolean
 OR (r->'occupancy'->>'can_manage_tasks')::boolean THEN RAISE EXCEPTION 'Child permissions expanded'; END IF;
 UPDATE public."AddressVerificationAttempt" SET status='sent' WHERE id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."AddressVerificationToken" SET used_at=NULL,attempt_count=0 WHERE attempt_id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."MailVerificationJob" SET metadata=metadata-'confirmed_home_id'-'confirmed_occupancy_id' WHERE attempt_id='eed00000-0000-4000-8000-000000000006';
 UPDATE public."HomeOccupancy" SET verification_status='pending_postcard' WHERE user_id='eed00000-0000-4000-8000-000000000001';
 UPDATE public."Home" SET owner_id='eed00000-0000-4000-8000-000000000002' WHERE id='eed00000-0000-4000-8000-000000000004';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'HOME_OCCUPIED' THEN RAISE EXCEPTION 'Later owner was bypassed'; END IF;
 UPDATE public."Home" SET owner_id=NULL WHERE id='eed00000-0000-4000-8000-000000000004';
 UPDATE public."AddressClaim" SET claim_status='rejected' WHERE user_id='eed00000-0000-4000-8000-000000000001' AND unit_number='4';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'ACCESS_REVOKED' THEN RAISE EXCEPTION 'Rejected unit claim accepted'; END IF;
 UPDATE public."AddressVerificationAttempt" SET expires_at=now()-interval '1 second' WHERE id='eed00000-0000-4000-8000-000000000006';
 r:=public.confirm_mail_verification('eed00000-0000-4000-8000-000000000006','eed00000-0000-4000-8000-000000000001',repeat('a',64),pg_temp.mail_templates(),730);
 IF r->>'error' IS DISTINCT FROM 'EXPIRED' THEN RAISE EXCEPTION 'Expired proof accepted'; END IF;
 IF EXISTS(SELECT FROM public."AddressVerificationToken" WHERE attempt_id='eed00000-0000-4000-8000-000000000006' AND (used_at IS NOT NULL OR attempt_count<>0)) THEN
  RAISE EXCEPTION 'Denied confirmation consumed proof'; END IF;
END $$;
RESET ROLE;

$contract$, 'mail-verification-confirmation.sql');
SELECT * FROM finish();
ROLLBACK;
