-- Generated by scripts/db/sync-sql-contracts.cjs; edit the source contract.
-- Source: scripts/db/contracts/reference-defaults.sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions, pg_catalog;
SELECT plan(1);
SELECT lives_ok($contract$
-- Required static rows and safe defaults for a newly installed baseline.
SET LOCAL statement_timeout = '30s';
SET LOCAL ROLE service_role;
DO $$ BEGIN
  IF (SELECT count(*) FROM public."HomeRolePermission") <> 24
    OR (SELECT count(*) FROM public."PostCategoryTTL") <> 18
    OR (SELECT count(*) FROM public."AddressCalendarRule") <> 74
    OR (SELECT count(*) FROM public."CountyRadonZone") <> 3128
    OR (SELECT count(*) FROM public."HudFmr") <> 3223 THEN
    RAISE EXCEPTION 'Required static references were not installed';
  END IF;
  IF NOT EXISTS (SELECT FROM public."HomeRolePermission"
    WHERE role_base = 'owner' AND permission = 'ownership.manage' AND allowed) THEN
    RAISE EXCEPTION 'Existing owner permission was lost';
  END IF;
  IF EXISTS (SELECT FROM public."HomeRolePermission"
    WHERE role_base = 'admin' AND permission = 'ownership.manage' AND allowed)
    OR EXISTS (SELECT FROM public."BusinessRolePermission") THEN
    RAISE EXCEPTION 'Baseline introduced new permission grants';
  END IF;
  IF NOT EXISTS (SELECT FROM public."PostCategoryTTL" WHERE post_type = 'personal_update' AND ttl_days = 7) THEN
    RAISE EXCEPTION 'Post expiry reference changed';
  END IF;
  IF NOT EXISTS (SELECT FROM public."FeatureFlag" WHERE flag_name = 'audience_profile'
    AND enabled_globally = false AND enabled_for_internal_team = false
    AND cardinality(beta_user_ids) = 0) THEN
    RAISE EXCEPTION 'A fresh install must require explicit Beacon activation';
  END IF;
END $$;
RESET ROLE;
SELECT 'PASS: required references, preserved permissions and disabled fresh Beacon flag' AS result;

$contract$, 'reference-defaults.sql');
SELECT * FROM finish();
ROLLBACK;
