# Stream 2: Posts, Hub and payments — its own U02–U04 checklist rows (split from the former Stream 1 on 2026-09-30).
# Only this stream edits this file. Chips: c(kind, text, ref); kinds done/confirm/todo/block/decide/na.
from data_common import c, ALL4

U03 = [
    ("Posts and Pulse", [
        ("Pulse feed, My posts, counts", "", {"iOS": [c("done", "My posts: archived posts stay after a reload (vanished from both tabs before)", "#1016, Stream 1 bundle 9d03a647"), c("done", "Lost & Found: contact line (selectable) and FOUND chip", "#1005, Stream 1 bundle e95f5d0f"), c("done", "Comment counts", "C-18"), c("done", "R1 R2", "Sep26 native Pulse reads")], "Android": [c("done", "My posts: archived posts stay after a reload (vanished from both tabs before)", "#1016, seal b74e23c0"), c("done", "Lost & Found: post page shows how to reach the owner; found posts no longer labelled LOST", "#1005 (merged), seal 903a2201"), c("done", "Comment counts", "C-18"), c("done", "R1 R2", "Sep26 native Pulse reads")], "Web": [c("done", "Comment counts", "C-18"), c("done", "R1 R2 on My Pulse", "Sep25"), c("done", "R1 R2 on the main feed; failed area read and false Pulse zeros fixed", "#850")]}),
        ("Create a post", "Text, photo, audience, place", {"iOS": [c("done", "E2 E3", "#718"), c("done", "E1 photo upload failure", "#718"), c("todo", "E6: Stream 1 iOS, queued")], "Android": [c("done", "E1 E2 E3", "#657, #718"), c("done", "E6 on device: typed (555) 555-0123 accepted, stored as digits", "seal ee9a6767")], "Web": [c("done", "E2 E3", "#718"), c("done", "E1 photo upload failure", "#718"), c("done", "E6: Lost & Found contact fixed; four tags reported truthfully", "#862")]}),
        ("Edit a post", "", {"iOS": [c("todo", "E1 E2 E5: Stream 1 iOS, queued")], "Android": [c("done", "E1, audience kept", "#657, #659"), c("done", "E2 lost reply kept + safe retry; E5 deleted meanwhile says so", "seal 04b91511")], "Web": [c("na", "Web has no post edit action (Delete, Hide, Report, Mark Resolved only); the API exists")]}),
        ("Delete a post", "", {"iOS": [c("done", "E2", "#709"), c("done", "E1 My posts says when a delete, archive or restore fails; Delete really deletes (it sent nothing before)", "#980, Stream 1 bundle d172244f")], "Android": [c("done", "E2", "#709"), c("done", "E1 post page: keeps the post and says \"Couldn't delete the post\"; retry deletes (no change)", "seal 569a60a4"), c("done", "E1 My posts: says when a delete, archive or restore fails", "#980, seal 54995229")], "Web": [c("done", "E2", "#709"), c("done", "E1: feed card, post page and My Pulse keep the post and say so; retry deletes (no change)", "bundle 32dfeb43")]}),
        ("Comments", "Add, reply, delete, pages, photos, drafts", {"iOS": [c("done", "E1 E2, delete, pages", "#671, #699, Sep27"), c("todo", "Photo attachment failure: Stream 1 iOS, queued")], "Android": [c("done", "E1 E2, delete, pages", "#671, #699, Sep27"), c("na", "Photo attachment failure: not offered (the Android comment composer is text-only)")], "Web": [c("done", "E1 E2, delete, pages, photos", "#671, #699, Sep27")]}),
        ("Report a post", "", {"iOS": [c("done", "E1 E2 E3", "#642 server dedupe")], "Android": [c("done", "E1 E2 E3", "#642")], "Web": [c("done", "E1 E2 E3", "#642 server dedupe")]}),
        ("Post links", "", {"iOS": [c("done", "Links open the right post", "#472")], "Android": [c("done", "Links open the right post", "#472")], "Web": [c("done", "Public post page: E4 private post kept; R1 now \"Couldn't load\" with Try Again", "#851")]}),
    ]),
    ("Start and Hub", [
        ("Start funnel and Place preview", "", {"iOS": [c("done", "R1", "#635")], "Android": [c("done", "R1", "#635")], "Web": [c("done", "R1", "#607"), c("done", "R1 address lookup failures say so (suggestions, geocoder outage)", "#873")]}),
        ("Hub cards and status pills", "Stream 1 parts only", {"iOS": [c("done", "Pills open real screens", "C-02"), c("todo", "R1: Stream 1 iOS, queued")], "Android": [c("done", "Pills open real screens", "C-02"), c("done", "R1: every failed read is shown as a failure, with Try again", "seal b716c9ce")], "Web": [c("done", "Hub posts", "Sep25"), c("done", "R1: Hub payload, Today card and detail, Action Queue fail truthfully (no change)", "bundle 890d21cb")]}),
    ]),
]

U04 = [
    ("Posts and comments", "", {"iOS": [c("done", "L1 L2 L3", "Sep27-28"), c("todo", "L4: Stream 1 iOS, queued")], "Android": [c("done", "L1 L2 L3", "#667, Sep27"), c("done", "L4: comment and edit replay once after a session refresh", "seal d875dafb")], "Web": [c("done", "L2 L3 L4", "Sep27, #785"), c("done", "L1 post and comment drafts kept while another tab refreshes the session (no change)", "bundle d0895b51")]}),
    ("Start and Place preview", "", {"iOS": [c("todo", "L2 L3: Stream 1 iOS, queued")], "Android": [c("done", "L2: the preview survives a cold restart and is offered after sign-in", "seal 433cf635"), c("done", "L3: the next person on the device no longer sees or is offered the previous address", "#989, seal 433cf635")], "Web": [c("done", "L2 L3: the previewed address survives a browser restart and never moves to another account (no change)", "bundle e2c35ebc")]}),
    ("Hub (the former Stream 1 cards)", "", {"iOS": [c("todo", "L2 L3: Stream 1 iOS, queued")], "Android": [c("done", "L3: account switch shows only the new account", "seal ea85ae47"), c("done", "L2: cold restart reads fresh data", "seal ea85ae47")], "Web": [c("done", "L3", "Sep27 late Hub reply"), c("done", "L3 Today no longer reused across accounts; area change and Refresh re-read", "#856"), c("done", "L2 cold start shows current state (no change)", "bundle 42571869")]}),
]

U02 = [
    ("Posts and Pulse", [
        ("Pulse feed", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A4 selected states + heart names, A1 chips no longer clipped at font 2.0: fixed and verified in #1027 (seal a966aa19), waiting to merge"), c("done", "A2: stays light and readable in system dark mode", "#1013 + seal a966aa19"), c("decide", "A3: brand blue #0284C7 is 4.10:1 on white; Stream 1's accents PR moves it to #0369A1 (5.93:1)")], "Web": [c("done", "A1 A2 A4 A5; post-type text, map markers and menus fixed", "#829"), c("decide", "A3 brand-blue token"), c("done", "A4 the active chip's mute control is its own button (user approved); toast names the topic", "#919")]}),
        ("Post detail and comments", {"iOS": [c("done", "A1 kept as is", "your decision"), c("todo", "A2 A3 A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("done", "A1 A2 comments", "#667"), c("todo", "A4: chip tone no longer read (#1027, waiting to merge); share posts' chip to read \"Post type: Share\" (follow-up)"), c("decide", "A3: brand blue 4.10:1; Stream 1's accents PR (#0369A1, 5.93:1)")], "Web": [c("done", "A5 comments", "Sep27"), c("done", "A1 A2 A4; type chip and dark header fixed", "#829"), c("decide", "A3 brand-blue token")]}),
        ("Post composer", {"iOS": [c("done", "A1 kept as is", "your decision"), c("todo", "A2 A3 A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A4 states and names, A1 contact choices (\"Phone\" was zero-width at font 2.0): fixed and verified in #1027, waiting to merge"), c("done", "A2: readable in system dark mode", "#1013"), c("decide", "A3: brand blue 4.10:1; Stream 1's accents PR (#0369A1, 5.93:1)")], "Web": [c("done", "A1 A2 A4 A5; intent text and AI button fixed", "#829"), c("decide", "A3 brand-blue token")]}),
        ("My posts", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A4 row names + tab states: fixed and verified in #1027, waiting to merge"), c("done", "A1: readable at font 2.0 (no change needed)", "seal a966aa19"), c("done", "A2: delete dialog and options sheet readable in dark mode (luminance 43 → 225/240)", "#1013, seal a966aa19"), c("decide", "A3: brand blue 4.10:1; Stream 1's accents PR (#0369A1, 5.93:1)")], "Web": [c("done", "A1 A2 A4 A5; the closed post panel is inert (was focusable off-screen)", "#879"), c("decide", "A3 brand-blue token")]}),
        ("Report a post", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A1 A2 A3 A4")], "Web": [c("done", "A1 A2 A3 A4 A5; close button named", "#829")]}),
    ]),
    ("Start and Hub", [
        ("Start funnel and Place preview", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A1 \"Sign in\" wraps letter by letter at font 2.0 and A4 unnamed address field: fix c84be82ce building"), c("done", "A4 other controls named", "seal a966aa19"), c("todo", "A2"), c("decide", "A3: brand blue 4.10:1; Stream 1's accents PR (#0369A1, 5.93:1)")], "Web": [c("done", "A1 A2 A3 A4 A5 on /start", "U02 web bundle ddbfe77a")]}),
        ("Hub (the former Stream 1 cards)", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A4 filter state, A1 tile captions losing words: fixed and verified in #1027, waiting to merge"), c("done", "A2: stays light and readable in dark mode", "#1013"), c("decide", "A3: brand blue 4.10:1; Stream 1's accents PR (#0369A1, 5.93:1)")], "Web": [c("done", "A1 A2 A4 A5; You badge fixed", "#829"), c("decide", "A3 brand-blue token")]}),
        ("Today detail", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("todo", "A1 A2 A3 A4")], "Web": [c("done", "A1 A2 A4 A5", "U02 web bundle ddbfe77a"), c("decide", "A3 brand-blue token")]}),
    ]),
    ("Money screens (viewing only, no payments)", [
        ("Tip sheet", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("done", "A1 A2, dark title fixed", "PR198"), c("todo", "A3 A4")], "Web": [c("done", "A1 A3 A4 A5; the sheet is a named modal dialog that keeps focus, Escape closes it, errors are announced", "#884"), c("decide", "A2 dark: the sunken surface token equals the card surface, so the $5/$10/$20 presets lose their fill")]}),
        ("Payment card and refund sheet", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("done", "A1 A2", "Sep22"), c("todo", "A3 A4")], "Web": [c("done", "A1 A2 A3 A4 A5; refund form keeps keyboard focus, dark progress labels readable", "#889")]}),
        ("Payments and wallet settings", {"iOS": [c("todo", "A1–A4: Stream 1 iOS, queued (after #1027)")], "Android": [c("done", "A1 A2 by accessibility tree", "Sep27"), c("block", "Screenshots blocked (secure screen)"), c("todo", "A3 A4")], "Web": [c("done", "A1 A2 A4 A5; filter and back-button names", "#829"), c("decide", "A3 emerald token")]}),
    ]),
]
