# Stream 2: Posts, Hub and payments — its own U02–U04 checklist rows (split from the former Stream 1 on 2026-09-30).
# Only this stream edits this file. Chips: c(kind, text, ref); kinds done/confirm/todo/block/decide/na.
from data_common import c, ALL4

U03 = [
    ("Posts and Pulse", [
        ("Pulse feed, My posts, counts", "", {"iOS": [c("done", "Cold-start Pantopus tips (seeded facts) opened \"We couldn't find this post\" (Stream 1): info cards with a dismiss", "#1047 merged (batch 211), Stream 1 iOS seal 47c730f8"), c("done", "My posts: archived posts stay after a reload (vanished from both tabs before)", "#1016, Stream 1 bundle 9d03a647"), c("done", "Lost & Found: contact line (selectable) and FOUND chip", "#1005, Stream 1 bundle e95f5d0f"), c("done", "Comment counts", "C-18"), c("done", "R1 R2", "Sep26 native Pulse reads")], "Android": [c("done", "Cold-start tips opened a post that doesn't exist (reproduced, 404): info cards with a working dismiss", "#1047 merged (batch 211), seal a67de577"), c("done", "My posts: archived posts stay after a reload (vanished from both tabs before)", "#1016, seal b74e23c0"), c("done", "Lost & Found: post page shows how to reach the owner; found posts no longer labelled LOST", "#1005 (merged), seal 903a2201"), c("done", "Comment counts", "C-18"), c("done", "R1 R2", "Sep26 native Pulse reads")], "Web": [c("done", "Cold-start tips rendered as full posts with no dismiss: info cards with a dismiss X", "#1047 merged (batch 211), seal a67de577"), c("done", "Comment counts", "C-18"), c("done", "R1 R2 on My Pulse", "Sep25"), c("done", "R1 R2 on the main feed; failed area read and false Pulse zeros fixed", "#850")]}),
        ("Create a post", "Text, photo, audience, place", {"iOS": [c("done", "E2 E3", "#718"), c("done", "E1 photo upload failure", "#718"), c("done", "E6: typed (555) 555-0123 stored as digits; the post page shows the contact line (Stream 1 iOS run, no change)", "Stream 1 bundle 3ee82fc9"), c("done", "My posts → Write a post always made an Ask post: the purpose picker shows", "#1047 merged (batch 211), Stream 1 iOS seal 47c730f8")], "Android": [c("done", "E1 E2 E3", "#657, #718"), c("done", "E6 on device: typed (555) 555-0123 accepted, stored as digits", "seal ee9a6767")], "Web": [c("done", "E2 E3", "#718"), c("done", "E1 photo upload failure", "#718"), c("done", "E6: Lost & Found contact fixed; four tags reported truthfully", "#862")]}),
        ("Edit a post", "", {"iOS": [c("done", "E1 a failed save keeps the edit; E2 a lost reply is retried once; E5 deleted elsewhere says so (Stream 1 iOS run, no change)", "Stream 1 bundle 4b8ed58a"), c("done", "A post saved without a title (web's general posts) couldn't be edited: the Headline stays empty, Save sends PATCH 200", "#1047 merged (batch 211), Stream 1 iOS seal 47c730f8")], "Android": [c("done", "E1, audience kept", "#657, #659"), c("done", "E2 lost reply kept + safe retry; E5 deleted meanwhile says so", "seal 04b91511"), c("done", "A post saved without a title couldn't be edited (reproduced, 0 writes): the title stays null", "#1047 merged (batch 211), seal 176cd103")], "Web": [c("na", "Web has no post edit action (Delete, Hide, Report, Mark Resolved only); the API exists")]}),
        ("Delete a post", "", {"iOS": [c("done", "E2", "#709"), c("done", "E1 My posts says when a delete, archive or restore fails; Delete really deletes (it sent nothing before)", "#980, Stream 1 bundle d172244f")], "Android": [c("done", "E2", "#709"), c("done", "E1 post page: keeps the post and says \"Couldn't delete the post\"; retry deletes (no change)", "seal 569a60a4"), c("done", "E1 My posts: says when a delete, archive or restore fails", "#980, seal 54995229")], "Web": [c("done", "E2", "#709"), c("done", "E1: feed card, post page and My Pulse keep the post and say so; retry deletes (no change)", "bundle 32dfeb43")]}),
        ("Comments", "Add, reply, delete, pages, photos, drafts", {"iOS": [c("done", "E1 E2, delete, pages", "#671, #699, Sep27"), c("na", "Photo attachment failure: not offered (the iOS comment composer is text-only; web comment photos still display)", "Stream 1 bundle e4825b97")], "Android": [c("done", "E1 E2, delete, pages", "#671, #699, Sep27"), c("na", "Photo attachment failure: not offered (the Android comment composer is text-only)")], "Web": [c("done", "E1 E2, delete, pages, photos", "#671, #699, Sep27")]}),
        ("Report a post", "", {"iOS": [c("done", "E1 E2 E3", "#642 server dedupe")], "Android": [c("done", "E1 E2 E3", "#642")], "Web": [c("done", "E1 E2 E3", "#642 server dedupe")]}),
        ("Post links", "", {"iOS": [c("done", "Links open the right post", "#472")], "Android": [c("done", "Links open the right post", "#472")], "Web": [c("done", "Public post page: E4 private post kept; R1 now \"Couldn't load\" with Try Again", "#851")]}),
    ]),
    ("Start and Hub", [
        ("Start funnel and Place preview", "", {"iOS": [c("done", "R1", "#635")], "Android": [c("done", "R1", "#635")], "Web": [c("done", "R1", "#607"), c("done", "R1 address lookup failures say so (suggestions, geocoder outage)", "#873")]}),
        ("Hub cards and status pills", "Stream 1 parts only", {"iOS": [c("done", "Pills open real screens", "C-02"), c("done", "R1: every failed read is shown as a failure, with Try again (Stream 1 iOS run, no change)", "Stream 1 bundle 7a50ea0a")], "Android": [c("done", "Pills open real screens", "C-02"), c("done", "R1: every failed read is shown as a failure, with Try again", "seal b716c9ce")], "Web": [c("done", "Hub posts", "Sep25"), c("done", "R1: Hub payload, Today card and detail, Action Queue fail truthfully (no change)", "bundle 890d21cb")]}),
    ]),
]

U04 = [
    ("Posts and comments", "", {"iOS": [c("done", "L1 L2 L3", "Sep27-28"), c("done", "L4: comment and edit replay once after a session refresh (Stream 1 iOS run, no change)", "Stream 1 bundle dd4939ee")], "Android": [c("done", "L1 L2 L3", "#667, Sep27"), c("done", "L4: comment and edit replay once after a session refresh", "seal d875dafb")], "Web": [c("done", "L2 L3 L4", "Sep27, #785"), c("done", "L1 post and comment drafts kept while another tab refreshes the session (no change)", "bundle d0895b51")]}),
    ("Start and Place preview", "", {"iOS": [c("done", "L2: the preview survives a restart and is offered after sign-in; L3: the next person sees no offer or address (Stream 1 iOS run, no change; sign-out also clears a pending preview)", "Stream 1 bundle be19dced")], "Android": [c("done", "L2: the preview survives a cold restart and is offered after sign-in", "seal 433cf635"), c("done", "L3: the next person on the device no longer sees or is offered the previous address", "#989, seal 433cf635")], "Web": [c("done", "L2 L3: the previewed address survives a browser restart and never moves to another account (no change)", "bundle e2c35ebc")]}),
    ("Hub (the former Stream 1 cards)", "", {"iOS": [c("done", "L3: account switch shows only the new account; L2: cold restart reads fresh data (Stream 1 iOS run, no change)", "Stream 1 bundle 3280a64f")], "Android": [c("done", "L3: account switch shows only the new account", "seal ea85ae47"), c("done", "L2: cold restart reads fresh data", "seal ea85ae47")], "Web": [c("done", "L3", "Sep27 late Hub reply"), c("done", "L3 Today no longer reused across accounts; area change and Refresh re-read", "#856"), c("done", "L2 cold start shows current state (no change)", "bundle 42571869")]}),
]

U02 = [
    ("Posts and Pulse", [
        ("Pulse feed", {"iOS": [c("done", "A1–A4: fixed text, nothing clips at AX5; dark readable; contrast passes; named", "Stream 1 bundle 3df1ecfb")], "Android": [c("done", "A4 selected states + heart names; A1 chips no longer clipped at font 2.0", "#1027, seal a966aa19"), c("done", "A2: stays light and readable in system dark mode", "#1013 + seal a966aa19"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5; post-type text, map markers and menus fixed", "#829"), c("done", "A3: no contrast failure in light or dark after #1052 (brand blue, emerald)", "axe on master 2693fcbcf, seal daf7aa08"), c("done", "A4 the active chip's mute control is its own button (user approved); toast names the topic", "#919")]}),
        ("Post detail and comments", {"iOS": [c("done", "A1 kept as is", "your decision"), c("done", "A2 A3 A4: dark readable; the Share chip is 4.57:1; named, and the comment field is labelled", "Stream 1 bundle 3df1ecfb")], "Android": [c("done", "A1 A2 comments", "#667"), c("done", "A4: chip tone no longer read", "#1027, seal a966aa19"), c("done", "A4: a Share post's chip read \"Share post\", like the Share button; it reads \"Post type: Share\"", "#1038 merged (batch 211)"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A5 comments", "Sep27"), c("done", "A1 A2 A4; type chip and dark header fixed", "#829"), c("done", "A3: brand blue passes after #1052; the Recommendation chip went from 4.33:1 to 6.12:1 (#92400E; map chips 4.29/4.46 → 6.06/6.29)", "#1073 merged (batch 214), seals daf7aa08, a0260faa")]}),
        ("Post composer", {"iOS": [c("done", "A1 kept as is", "your decision"), c("done", "A2 A3 A4: dark readable; contrast passes; named", "Stream 1 bundle 3df1ecfb")], "Android": [c("done", "A4 states and names; A1 contact choices (\"Phone\" was zero-width at font 2.0)", "#1027, seal a966aa19"), c("done", "A2: readable in system dark mode", "#1013"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5; intent text and AI button fixed", "#829"), c("todo", "A3: re-measure the New Post dialog (the master capture did not open it); the composer palette computes 4.63:1 or more")]}),
        ("My posts", {"iOS": [c("done", "A1 A2 A4: no clipping; dark readable; named, with the Selected trait on the active tab", "Stream 1 bundle 3df1ecfb"), c("todo", "A3: the dark selected tab \"Active\" is 4.22:1; Stream 1's #1061")], "Android": [c("done", "A4 row names + tab states", "#1027, seal a966aa19"), c("done", "A1: readable at font 2.0 (no change needed)", "seal a966aa19"), c("done", "A2: delete dialog and options sheet readable in dark mode (luminance 43 → 225/240)", "#1013, seal a966aa19"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5; the closed post panel is inert (was focusable off-screen)", "#879"), c("done", "A3: no contrast failure in light or dark after #1052 (brand blue, emerald)", "axe on master 2693fcbcf, seal daf7aa08")]}),
        ("Report a post", {"iOS": [c("done", "A1–A4: the system dialog scales; dark reasons 5.25–5.39:1 after #1056 (merged); named", "Stream 1 bundle 3df1ecfb")], "Android": [c("done", "A1 readable at font 2.0; A4 reasons and Cancel named (no change)", "seal a966aa19"), c("done", "A2: stays light and readable in dark mode", "seal 607283e7"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A3 A4 A5; close button named", "#829")]}),
    ]),
    ("Start and Hub", [
        ("Start funnel and Place preview", {"iOS": [c("done", "A1 A2: fixed text, the arrival offer scales; dark readable", "Stream 1 bundle 3df1ecfb"), c("todo", "A4: the preview Back, the address clear ✕ and the address field were unnamed or placeholder-only (F1–F3): named on branch claude/stream2-ios-u02-fixes (build queued; Stream 1 iOS run next)"), c("todo", "A3: dark \"Sign in\" and \"Save it to get updates.\" under 4.5:1 (F4); Stream 1's #1061")], "Android": [c("done", "A1 \"Sign in\" stays on one line at font 2.0; A4 the address field is named", "#1034 merged (batch 201), seal 607283e7"), c("done", "A4 other controls named", "seal a966aa19"), c("done", "A2: stays light and readable in dark mode", "seal 607283e7"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A3 A4 A5 on /start", "U02 web bundle ddbfe77a")]}),
        ("Hub (the former Stream 1 cards)", {"iOS": [c("done", "A1–A4: no clipping; dark readable; \"Explore Map\" 4.62:1; named", "Stream 1 bundle 3df1ecfb")], "Android": [c("done", "A4 filter state; A1 tile captions no longer lose words", "#1027, seal a966aa19"), c("done", "A2: stays light and readable in dark mode", "#1013"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5; You badge fixed", "#829"), c("done", "A3: no contrast failure in light or dark after #1052 (brand blue, emerald)", "axe on master 2693fcbcf, seal daf7aa08")]}),
        ("Today detail", {"iOS": [c("done", "Truth: real sun times, a true share line, no private signal or summary in Share, loads with action signals, Back from a briefing push, chip \"Post type: Share\" (Stream 1 iOS run on #1038)", "Stream 1 bundle aeb2d308"), c("done", "A1 A2 A4: no clipping; dark readable; named", "Stream 1 bundle 3df1ecfb"), c("todo", "A3: the dark hero label is 4.22:1; Stream 1's #1061"), c("todo", "More and Manage did nothing on the briefing push: shown only where they lead, in #1075 (seal 42bb8b0b); iOS run by Stream 1 next")], "Android": [c("done", "A4 controls named (no change)", "today bundle before/"), c("done", "Truth, share privacy and the action-signal decode", "#1038 merged (batch 211), seals 44bc9f8b, 88bd4642"), c("done", "A2: stays light and readable in dark mode", "seal 44bc9f8b"), c("todo", "A1: at font 2.0 the Sun & sky captions touched: an 8 dp gap in #1075 (seal 42bb8b0b), waiting to merge"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5", "U02 web bundle ddbfe77a"), c("done", "A3: no contrast failure in light or dark after #1052 (brand blue, emerald)", "axe on master 2693fcbcf, seal daf7aa08")]}),
    ]),
    ("Money screens (viewing only, no payments)", [
        ("Tip sheet", {"iOS": [c("done", "A1: no clipping; the disabled amounts are exempt (the helper has no payouts, and the sheet says so)", "Stream 1 bundle 3df1ecfb"), c("todo", "A2/A3 dark: system glass put \"Custom amount\" at 4.01 and \"Not now\" at 2.32 (F6: opaque app surface, agreed with Stream 1); A4 the custom amount was placeholder-only (F3): fixed on branch claude/stream2-ios-u02-fixes (build queued; Stream 1 iOS run next)")], "Android": [c("done", "A1 A2, dark title fixed", "PR198"), c("done", "A4: amounts, custom field, send and Not now named; disabled state announced with its reason", "seal 1e9293bd"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A3 A4 A5; the sheet is a named modal dialog that keeps focus, Escape closes it, errors are announced", "#884"), c("todo", "A2 dark: the sunken surface token still equals the card surface on master 2693fcbcf, so the $5/$10/$20 presets lose their fill; Stream 1 token change (you decided 09-30)")]}),
        ("Payment card and refund sheet", {"iOS": [c("done", "A2: dark readable", "Stream 1 bundle 3df1ecfb"), c("todo", "A1 reason cut at AX5 (F8), A4 refund amount placeholder-only (F3), no feedback from Check status (F7): fixed on branch claude/stream2-ios-u02-fixes (build queued; Stream 1 iOS run next); F7 also on Android and web"), c("todo", "A3: dock buttons (F4) and counterparty initials 2.77:1 (F5); Stream 1's #1061")], "Android": [c("done", "A1 A2", "Sep22"), c("done", "A4: task-progress steps read done / current step / not yet; refund reasons named; other controls named", "#1034 merged (batch 201), seals 1e9293bd, 607283e7"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A3 A4 A5; refund form keeps keyboard focus, dark progress labels readable", "#889")]}),
        ("Payments and wallet settings", {"iOS": [c("block", "Behind the OS device-passcode prompt on the simulator; Stream 1 doesn't type into it (boundary)")], "Android": [c("done", "A1 A2 by accessibility tree", "Sep27"), c("block", "Screenshots blocked (secure screen)"), c("done", "A4: controls named; balance reads \"Available to withdraw: 0.00 USD\"", "seal a966aa19"), c("done", "A3: brand blue is now #0369A1: 5.93:1 on white, 5.54:1 on the page background, white on it 5.93:1; status colours 5.1–7.4:1", "#1029, token check on master 1e1b6bacc")], "Web": [c("done", "A1 A2 A4 A5; filter and back-button names", "#829"), c("done", "A3: wallet and payment settings have no contrast failure in light or dark after #1052 (emerald, brand blue)", "axe on master 2693fcbcf, seal daf7aa08")]}),
    ]),
]
