# Stream 1: Support Trains and coordination — its own U02–U04 checklist rows (split from the former Stream 1 on 2026-09-30).
# Only this stream edits this file. Chips: c(kind, text, ref); kinds done/confirm/todo/block/decide/na.
from data_common import c, ALL4

U03 = [
    ("Support Trains", [
        ("Train lists and search", "My trains, Nearby, Invitations, search", {"iOS": [c("done", "E5", "#789"), c("todo", "R1 R2")], "Android": [c("done", "E5", "#789"), c("todo", "R1 R2")], "Web": [c("done", "R1", "#662"), c("done", "E5", "#783"), c("done", "R2", "#662")]}),
        ("Start a train", "Wizard: create and publish", {"iOS": [c("done", "E6 recipient search and no match", "Sep23 Train UX"), c("todo", "E1 E2 E3: fix in PR #841; E1 E2 verified, the final-build run (E3 included) and the seal are pending")], "Android": [c("done", "E6 recipient search and no match", "Sep23 Train UX"), c("todo", "E1 E2 E3: fix in PR #841, verified (publish 503 retry, lost create reply and double tap each end with one train); seal pending")], "Web": [c("done", "E1 failed publish removes its draft", "#817"), c("done", "E3 double-click publish; E6 missing fields", "U03 web bundle bbdbf2d2"), c("done", "E6 Edit Manually selects the preset's days", "#890"), c("done", "E2 lost create reply reaches the same draft", "#836")]}),
        ("Train detail and share link", "", {"iOS": [c("done", "E4 share link and privacy", "Sep24"), c("done", "E5", "#789"), c("todo", "R1")], "Android": [c("done", "R1 E4", "Sep24"), c("done", "E5", "#789")], "Web": [c("done", "R1 E5 on Manage", "Sep28"), c("done", "E4 public page privacy", "Sep24, PR402"), c("done", "E4 a draft or back-to-draft train is closed to its link", "#883"), c("done", "R1 on detail", "U03 web bundle bbdbf2d2")]}),
        ("Helper: sign up, cancel, leave", "", {"iOS": [c("done", "E1 E2 sign up and cancel", "#720"), c("done", "Leave", "#747"), c("todo", "E3"), c("done", "E4 greyed button with the reason on non-live trains", "#811")], "Android": [c("done", "E1 E2 sign up and cancel", "#720"), c("done", "Leave", "#747"), c("todo", "E3"), c("done", "E4 greyed button with the reason on non-live trains", "#811")], "Web": [c("done", "E1 E2 sign up", "#720"), c("na", "Cancel and leave not offered"), c("done", "E3 double-click sign-up", "U03 web bundle bbdbf2d2"), c("done", "E4 greyed button with the reason on non-live trains", "#811")]}),
        ("Delivery and organizer confirmation", "", {"iOS": [c("done", "E1 E2 E5", "#733, Sep28"), c("todo", "E3")], "Android": [c("done", "E1 E2 E5", "#733, Sep28"), c("todo", "E3")], "Web": [c("na", "Read-only on web")]}),
        ("Organizer dates: add, edit, remove", "", {"iOS": [c("done", "Add and edit: E1 E2 E3 E6", "#759"), c("todo", "Remove: E1 E2")], "Android": [c("done", "Add and edit: E1 E2 E3 E6", "#759"), c("done", "Remove: E1", "#759"), c("todo", "Remove: E2")], "Web": [c("na", "Calendar is read-only on web")]}),
        ("Send update and push choice", "", {"iOS": [c("done", "E1 E2 E3", "#762"), c("done", "Push choice", "#778")], "Android": [c("done", "E1 E2 E3", "#762"), c("done", "Push choice", "#778")], "Web": [c("na", "Updates are read-only on web")]}),
        ("Signups: edit, remove helper, share address", "", {"iOS": [c("done", "Edit: E1-E6", "#741"), c("done", "Remove: E1 E2 E3", "Sep28"), c("done", "Address: E1 E2 E3 E4", "#747")], "Android": [c("done", "Remove: E1 E2 E3", "Sep28"), c("done", "Address: E1 E2 E3 E4", "#747"), c("na", "Edit not offered")], "Web": [c("done", "Roster and per-helper privacy", "#747"), c("na", "Edit, remove, address are app-only")]}),
        ("Pause, resume, back to draft, archive, delete, close", "", {"iOS": [c("done", "E2 pause and delete", "#783"), c("done", "E5 after delete", "#789"), c("done", "Close: E1 E2 E3", "#765"), c("todo", "E1 E3 all; E2 resume, back to draft, archive")], "Android": [c("done", "E2 all five", "#783"), c("done", "E5 after delete", "#789"), c("done", "Close: E1 E2 E3", "#765"), c("todo", "E1 E3")], "Web": [c("done", "Delete: E2 E5", "#783"), c("done", "Delete: E1 E3", "U03 web bundle bbdbf2d2"), c("na", "Close, pause, resume, back to draft, archive not offered")]}),
        ("Co-organizers", "People picker (approved)", {"iOS": [c("done", "Picker add, remove, empty state, invite share", "#812"), c("todo", "E1 E2 E3 E4 E5")], "Android": [c("done", "Picker add, remove, empty state, invite share", "#812"), c("done", "Remove no longer crashes the app", "#813"), c("todo", "E1 E2 E3 E4 E5")], "Web": [c("na", "No co-organizer editor on web")]}),
        ("Remind helpers", "Nudge draft and send", {"iOS": [c("block", "Needs an AI provider")], "Android": [c("block", "Needs an AI provider")], "Web": [c("block", "Needs an AI provider")]}),
        ("Gift fund: turn on, turn off", "", {"iOS": [c("todo", "E1 E2 E3"), c("block", "Contributions move money")], "Android": [c("todo", "E1 E2 E3"), c("block", "Contributions move money")], "Web": [c("done", "Turn on from Start a train; the pages follow on/off; a failed fund step removes the draft", "#877"), c("na", "Turning it off or on later is app-only"), c("block", "Contributions move money")]}),
    ]),
]

U04 = [
    ("Support Trains", "Lists, detail, Manage, signups", {"iOS": [c("done", "L2", "#733-#778"), c("todo", "L1 typed text survives"), c("todo", "L3"), c("todo", "L4")], "Android": [c("done", "L2", "#733-#778"), c("todo", "L1 typed text survives"), c("todo", "L3"), c("todo", "L4")], "Web": [c("done", "L2 reload", "Sep28"), c("done", "L4", "#785"), c("done", "L3 switch account: nothing from the previous account shows", "20260930 web switch 73f2bc13")]}),
]

U02 = [
    ("Support Trains", [
        ("My trains, Nearby, Invitations", {"iOS": [c("done", "A1 A2 A4; A3 selected tab and FAB fixed in dark (#1061)", "#1061, #1093, 054245b5")], "Android": [c("done", "A1 A2 A3; A4 tabs say selected, rows read once", "#1211, ac43ecdb"), c("todo", "A4 shared ListOfRows repeats its tab, FAB and Nearby button labels (app-wide)")], "Web": [c("done", "A1 A2 A4 A5; chip contrast fixed", "#814"), c("decide", "A3 brand-blue token")]}),
        ("Train search", {"iOS": [c("done", "A1 A2 A3; A4 search field named", "#1093, 054245b5")], "Android": [c("done", "A1 A2 A3 A4: field named, results read once", "#1211, ac43ecdb")], "Web": [c("na", "No Train search on web")]}),
        ("Train detail and sign-up sheet", {"iOS": [c("done", "A1 A2; A3 Hosted by at full strength; A4 sheet fields named; signup strip truthful", "#1093, 054245b5"), c("done", "A3 covered slot date tiles (T7) and A4 card status (T8) fixed", "#1099, 087226fa")], "Android": [c("done", "Detail: A1 legend wraps, times and end date kept, pills grow, names ellipsize; A2; A3 (HOME 4.57, the 4.42 was the scanner); A4 day states, one-stop cards, no repeats", "#1211, ac43ecdb"), c("todo", "Sign-up sheet A1 A2 A3 A4")], "Web": [c("done", "A1 A2 A4 A5; dark selection fixed", "#814"), c("decide", "A3 brand-blue token")]}),
        ("Start a train", {"iOS": [c("done", "A1 A2 A3; A4 recipient and short note named", "#1093, 054245b5")], "Android": [c("done", "Step 1: A1 A2 A3; A4 reason tiles selected, fields named", "#1211, ac43ecdb"), c("todo", "Steps 2-5; shared WizardShell repeats Continue and its title meets the step count at 2.0")], "Web": [c("done", "Step 1: A1 A2 A3 A4 A5; dark selection fixed", "#814"), c("done", "Later steps: A1 A2 A4 A5; field and weekday names added", "#829"), c("done", "Schedule shortcuts expose their chosen state (A2)", "#892"), c("decide", "A3 brand-blue token")]}),
        ("Manage train", {"iOS": [c("done", "A1 A4; A2 A3 chip and date line fixed in dark; times formatted", "#1093, 054245b5")], "Android": [c("done", "A1 stat labels whole (default-size clipping fixed), pills grow; A2; A3; A4 Back, tiles, field, switch and chips named with state", "#1211, ac43ecdb")], "Web": [c("done", "A1 A2 A4 A5; share-link label added", "#814"), c("decide", "A3 brand-blue token")]}),
        ("Review signups, edit signup", {"iOS": [c("na", "Not reachable on iOS since 70d2a8822: organizers manage signups in Manage (covered there)")], "Android": [c("todo", "A1 A2 A3 A4")], "Web": [c("done", "Signups tab: A1 A2 A4 A5", "20260930 web a11y 73f2bc13"), c("decide", "Signups tab A3 brand-blue token")]}),
        ("Updates and details tabs, calendar", {"iOS": [c("na", "Web-only screens")], "Android": [c("na", "Web-only screens")], "Web": [c("done", "A1 A2 A4 A5; calendar button names added", "#814"), c("decide", "A3 brand-blue token")]}),
    ]),
]
