//
//  LegalDocuments.swift
//  Pantopus
//
//  A19.1 / A19.2 — structured, in-source copy for the long-form legal viewer
//  (`LegalContentView`). Kept as data so Privacy + Terms stay byte-identical
//  with Android (`settings/legal/LegalScreens.kt`) and word-for-word with the
//  design (`docs/designs/A19/legal-frames.jsx`). No CMS yet — see the B6.1
//  prompt's out-of-scope note.
//

import Foundation

// MARK: - Structured content model

/// A single legal document, fully data-driven so Privacy + Terms (and Android)
/// stay byte-identical. `sectionTitles` doubles as the `LegalTOCCard` items and
/// the `LegalSection` headings.
struct LegalDocModel {
    let lastUpdated: String
    let version: String
    let sections: [LegalDocSection]
    let contactEmail: String
    let contactLabel: String

    var sectionTitles: [String] {
        sections.map(\.title)
    }
}

struct LegalDocSection {
    let title: String
    let blocks: [LegalBlock]
}

enum LegalBlock {
    /// Plain running paragraph.
    case paragraph(String)
    /// Paragraph with inline bold defined terms (`<DT>`).
    case rich([LegalRun])
    /// Bold sub-heading (`<H3>`).
    case subheading(String)
    /// Dotted bullet list.
    case bullets([String])
}

/// One inline run of paragraph text. `bold` marks a defined term (`<DT>`).
struct LegalRun {
    let text: String
    let bold: Bool

    /// Plain run.
    static func t(_ text: String) -> LegalRun {
        LegalRun(text: text, bold: false)
    }

    /// Bold defined-term run.
    static func b(_ text: String) -> LegalRun {
        LegalRun(text: text, bold: true)
    }
}

// MARK: - Verbatim copy (mirrors docs/designs/A19/legal-frames.jsx)

enum LegalDocs {
    static func model(for document: LegalDocument) -> LegalDocModel {
        switch document {
        case .terms: terms
        default: privacy
        }
    }

    // MARK: Privacy (10 sections)

    static let privacy = LegalDocModel(
        lastUpdated: "October 1, 2025",
        version: "3.2",
        sections: [
            LegalDocSection(title: "Overview", blocks: [
                .rich([
                    .t("Pantopus is a neighborhood platform that lets you keep separate "),
                    .b("Personal"),
                    .t(", "),
                    .b("Home"),
                    .t(", and "),
                    .b("Business"),
                    .t(
                        " identities. This policy explains what data we collect for each " +
                            "pillar, why we collect it, and the controls you have over it."
                    )
                ]),
                .paragraph(
                    "We wrote this in plain language. Defined terms appear in the Glossary " +
                        "at the end of the document."
                )
            ]),
            LegalDocSection(title: "Information we collect", blocks: [
                .paragraph(
                    "We collect three categories of information: information you give us " +
                        "directly, information generated by your use of Pantopus, and " +
                        "information from third parties (such as identity verification " +
                        "partners)."
                ),
                .subheading("Information you provide"),
                .paragraph(
                    "This includes account details, profile fields, content you post, and " +
                        "documents you upload to verify a claim:"
                ),
                .bullets([
                    "Your name, email address, and phone number",
                    "Profile photos and avatars for each identity pillar",
                    "Address and deed documents when claiming a Home identity",
                    "Business filings, EIN, and storefront photos for a Business identity",
                    "Messages you send through member chat and Ceremonial Mail"
                ]),
                .subheading("Information generated by your use"),
                .paragraph(
                    "We log device type, app version, approximate location (derived from " +
                        "IP), and which features you interact with. This helps us debug issues " +
                        "and tell you how busy your neighborhood is, without ever attaching " +
                        "precise GPS to your account."
                )
            ]),
            LegalDocSection(title: "How we use it", blocks: [
                .rich([
                    .t(
                        "We use the information above to operate Pantopus — for example, to " +
                            "deliver chat messages, route a package notification to the right "
                    ),
                    .b("Home"),
                    .t(
                        ", or surface a relevant local gig. We also use it for safety, fraud " +
                            "prevention, and to improve the product."
                    )
                ]),
                .bullets([
                    "To operate and maintain core features (chat, mail, claims)",
                    "To verify identity claims and prevent impersonation",
                    "To send transactional notifications you can control in Settings",
                    "To improve and debug the product through aggregated analytics"
                ])
            ]),
            LegalDocSection(title: "Identity pillars & privacy", blocks: [
                .rich([
                    .t("The three pillars are walled off from each other by default. Your "),
                    .b("Business"),
                    .t(" identity does not show your home address; your "),
                    .b("Home"),
                    .t(
                        " identity does not reveal your personal phone number to neighbors " +
                            "unless you explicitly opt in."
                    )
                ]),
                .rich([
                    .t("When someone sends you a "),
                    .b("Token"),
                    .t(
                        " (an invite to a Home, Business, or guest pass), the recipient sees " +
                            "only the fields you've published on that pillar — never the other " +
                            "two."
                    )
                ])
            ]),
            LegalDocSection(title: "Sharing & disclosure", blocks: [
                .paragraph(
                    "We do not sell your personal information. We share data only with " +
                        "service providers under contract (hosting, payments, identity " +
                        "verification), with parties you direct us to share with, and when " +
                        "required by law."
                )
            ]),
            LegalDocSection(title: "Your rights & controls", blocks: [
                .paragraph("You can, at any time:"),
                .bullets([
                    "Download a copy of your data from Settings → Privacy → Export",
                    "Delete a single identity pillar or your entire account",
                    "Revoke any Token you previously accepted",
                    "Object to a specific use of your data by contacting privacy@pantopus.com"
                ])
            ]),
            LegalDocSection(title: "Data retention", blocks: [
                .paragraph(
                    "We retain your data for as long as your account is active. When you " +
                        "delete an identity pillar, associated content is removed within 30 " +
                        "days. Some records (financial, safety) may be retained longer where " +
                        "legally required."
                )
            ]),
            LegalDocSection(title: "Children & teens", blocks: [
                .paragraph(
                    "Pantopus is intended for users 13 and older. We do not knowingly " +
                        "collect personal information from children under 13. If you believe a " +
                        "child has provided us with personal information, please contact us so " +
                        "we can remove it."
                )
            ]),
            LegalDocSection(title: "International transfers", blocks: [
                .paragraph(
                    "We are based in the United States. If you use Pantopus from outside " +
                        "the U.S., your information will be transferred to, stored, and " +
                        "processed in the U.S. under appropriate safeguards."
                )
            ]),
            LegalDocSection(title: "Changes to this policy", blocks: [
                .paragraph(
                    "We may update this policy from time to time. When we do, we'll change " +
                        "the \"Last updated\" date at the top and — for material changes — send " +
                        "an in-app notice at least 14 days before the changes take effect."
                )
            ])
        ],
        contactEmail: "privacy@pantopus.com",
        contactLabel: "Questions about this policy?"
    )

    // MARK: Terms (12 sections)

    static let terms = LegalDocModel(
        lastUpdated: "February 14, 2026",
        version: "5.0",
        sections: [
            LegalDocSection(title: "Acceptance of these terms", blocks: [
                .paragraph(
                    "These Terms of Service (\"Terms\") are a binding agreement between you " +
                        "and Pantopus, Inc. By creating an account, claiming an identity, or " +
                        "otherwise using Pantopus, you agree to these Terms and to our Privacy " +
                        "Policy."
                ),
                .paragraph(
                    "If you are using Pantopus on behalf of a business, you represent that " +
                        "you have authority to bind that business to these Terms."
                )
            ]),
            LegalDocSection(title: "Eligibility & accounts", blocks: [
                .paragraph(
                    "You must be at least 13 years old to use Pantopus. You are responsible " +
                        "for the activity on your account and for keeping your credentials " +
                        "secure."
                ),
                .bullets([
                    "Provide accurate information when you register",
                    "Keep your password and device secure",
                    "Notify us promptly of any unauthorized use",
                    "One person may hold only one Personal identity"
                ])
            ]),
            LegalDocSection(title: "Identity pillars", blocks: [
                .rich([
                    .t("Pantopus lets you operate up to three identity pillars — "),
                    .b("Personal"),
                    .t(", "),
                    .b("Home"),
                    .t(", and "),
                    .b("Business"),
                    .t(
                        ". Claiming a Home or Business pillar may require verification " +
                            "documents. You agree not to claim an identity you are not entitled " +
                            "to represent."
                    )
                ]),
                .paragraph(
                    "We may revoke a pillar if a claim is found to be false, disputed by a " +
                        "rightful owner, or used to impersonate another party."
                )
            ]),
            LegalDocSection(title: "Acceptable use", blocks: [
                .paragraph("You agree not to use Pantopus to:"),
                .bullets([
                    "Harass, threaten, or impersonate other members",
                    "Post unlawful, fraudulent, or misleading content",
                    "Scrape, reverse-engineer, or overload the service",
                    "Circumvent the walls between identity pillars",
                    "Resell access or Tokens without our written consent"
                ])
            ]),
            LegalDocSection(title: "Content & licenses", blocks: [
                .paragraph(
                    "You retain ownership of the content you post. By posting, you grant " +
                        "Pantopus a non-exclusive, worldwide license to host, display, and " +
                        "distribute that content as needed to operate the service."
                ),
                .subheading("Feedback"),
                .paragraph(
                    "If you send us ideas or suggestions, you grant us a perpetual, " +
                        "royalty-free license to use them without obligation to you."
                )
            ]),
            LegalDocSection(title: "Tokens, invites & access", blocks: [
                .rich([
                    .t("A "),
                    .b("Token"),
                    .t(
                        " grants limited, revocable access to a Home, Business, or guest " +
                            "context. Tokens are personal to the recipient and may not be " +
                            "transferred. Either party may revoke a Token at any time from " +
                            "Settings."
                    )
                ])
            ]),
            LegalDocSection(title: "Payments & gigs", blocks: [
                .paragraph(
                    "Some features — local gigs, marketplace listings, and premium pillars " +
                        "— involve payments processed by our third-party providers. You agree " +
                        "to their terms in addition to ours. Fees are disclosed before you " +
                        "confirm a transaction."
                ),
                .bullets([
                    "Gig payments are released on completion or per the listing terms",
                    "Refunds follow the policy shown at checkout",
                    "You are responsible for any taxes on income you earn"
                ])
            ]),
            LegalDocSection(title: "Termination", blocks: [
                .paragraph(
                    "You may delete a pillar or your entire account at any time. We may " +
                        "suspend or terminate access if you violate these Terms, create risk " +
                        "for other members, or as required by law. Sections that by their " +
                        "nature should survive termination will survive."
                )
            ]),
            LegalDocSection(title: "Disclaimers", blocks: [
                .paragraph(
                    "Pantopus is provided \"as is\" and \"as available.\" We do not warrant " +
                        "that the service will be uninterrupted, error-free, or that any member " +
                        "is who they claim to be beyond the verification we describe."
                )
            ]),
            LegalDocSection(title: "Limitation of liability", blocks: [
                .paragraph(
                    "To the maximum extent permitted by law, Pantopus will not be liable " +
                        "for indirect, incidental, or consequential damages, or for any amount " +
                        "exceeding the greater of the fees you paid us in the past 12 months or " +
                        "one hundred U.S. dollars."
                )
            ]),
            LegalDocSection(title: "Governing law & disputes", blocks: [
                .paragraph(
                    "These Terms are governed by the laws of the State of Delaware, without " +
                        "regard to its conflict-of-laws rules. Disputes will be resolved in the " +
                        "state or federal courts located in Delaware, unless applicable law " +
                        "requires otherwise."
                )
            ]),
            LegalDocSection(title: "Changes to these terms", blocks: [
                .paragraph(
                    "We may update these Terms from time to time. For material changes " +
                        "we'll update the \"Last updated\" date and give in-app notice at least " +
                        "14 days before they take effect. Continued use after that date means " +
                        "you accept the revised Terms."
                )
            ])
        ],
        contactEmail: "legal@pantopus.com",
        contactLabel: "Questions about these terms?"
    )
}
