//
//  UploadDocumentSnapshotTests.swift
//  PantopusTests
//
//  P2.10 — Design-reference baseline tripwire for the Upload Document
//  form and the Document Detail screen. Same shape as
//  `BroadcastDetailSnapshotTests`: asserts the baseline PNGs exist at
//
//    `PantopusTests/__Snapshots__/p2-10-documents/<slug>-ios.png`
//
//  and are valid PNGs. Tests `XCTSkip` when a baseline is missing so
//  the gate exists from day one; the follow-up commits the renders
//  generated by the `make snapshots` target.
//
//  States covered:
//    • upload-empty      → fresh form, no file picked
//    • upload-filled     → file picked, title + category + tags + visibility set
//    • detail-pdf        → PDF preview pane
//    • detail-image      → AsyncImage preview pane
//    • detail-unsupported → DOCX/XLSX/ZIP preview fallback
//

import XCTest

final class UploadDocumentSnapshotTests: XCTestCase {
    private var baselineURL: URL {
        let here = URL(fileURLWithPath: #filePath)
        return here
            .deletingLastPathComponent() // Homes
            .deletingLastPathComponent() // Features
            .deletingLastPathComponent() // PantopusTests
            .appendingPathComponent("__Snapshots__")
            .appendingPathComponent("p2-10-documents")
    }

    func test_upload_document_empty_ios_baseline_is_present() throws {
        try assertBaselineOrSkip("upload-empty")
    }

    func test_upload_document_filled_ios_baseline_is_present() throws {
        try assertBaselineOrSkip("upload-filled")
    }

    func test_document_detail_pdf_ios_baseline_is_present() throws {
        try assertBaselineOrSkip("detail-pdf")
    }

    func test_document_detail_image_ios_baseline_is_present() throws {
        try assertBaselineOrSkip("detail-image")
    }

    func test_document_detail_unsupported_ios_baseline_is_present() throws {
        try assertBaselineOrSkip("detail-unsupported")
    }

    private func assertBaselineOrSkip(_ slug: String) throws {
        let url = baselineURL.appendingPathComponent("\(slug)-ios.png")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw XCTSkip("Baseline pending follow-up commit: \(url.path)")
        }
        let data = try Data(contentsOf: url)
        XCTAssertGreaterThan(data.count, 8 * 1024, "Baseline too small (\(data.count) bytes): \(url.path)")
        XCTAssertTrue(
            data.count > 4 &&
                data[0] == 0x89 &&
                data[1] == 0x50 &&
                data[2] == 0x4E &&
                data[3] == 0x47,
            "Not a PNG: \(url.path)"
        )
    }
}
