// components/index.d.ts, derived from the bundle entry: for every component
// src/entry.tsx re-exports, its props interfaces and types are copied
// verbatim from the web source (plus any types they import from sibling
// modules or @pantopus/types). A component re-exported under a new name
// (SectionCard → PlaceSectionCard) gets its Props type renamed to match.

import { readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { PACKAGES, WEB_SRC, read, webRequire } from './repo.mjs';

const GROUPS = [
  ['components/brand/', 'Brand'],
  ['components/archetypes/primitives/', 'Archetype primitives'],
  ['components/archetypes/place/', 'Place archetype'],
  ['components/', 'Shared UI'],
];

const EXTENSIONS = ['.tsx', '.ts'];
const resolveModule = (base) => {
  for (const ext of ['', ...EXTENSIONS]) {
    try {
      const file = base + ext;
      read(file);
      return file;
    } catch {
      // try the next extension
    }
  }
  throw new Error(`Cannot resolve ${base}`);
};

export function buildTypes({ entry, components }) {
  const ts = webRequire('typescript');
  const parsed = new Map();
  const parse = (file) => {
    if (!parsed.has(file)) parsed.set(file, ts.createSourceFile(file, read(file), ts.ScriptTarget.Latest, true, file.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS));
    return parsed.get(file);
  };
  const warnings = [];

  /** name → { text, deps } for every interface / type alias in a module. */
  const typeDecls = (file) => {
    const sf = parse(file);
    const out = new Map();
    for (const st of sf.statements) {
      if (!ts.isInterfaceDeclaration(st) && !ts.isTypeAliasDeclaration(st)) continue;
      const doc = (ts.getJSDocCommentsAndTags(st) ?? []).map((d) => d.getText(sf)).join('\n');
      out.set(st.name.text, (doc ? `${doc}\n` : '') + `export ${st.getText(sf).replace(/^export\s+/, '')}`);
    }
    return out;
  };

  /** Imported name → module file (relative or @pantopus/*), for type lookups. */
  const importsOf = (file) => {
    const sf = parse(file);
    const out = new Map();
    for (const st of sf.statements) {
      if (!ts.isImportDeclaration(st) || !st.importClause) continue;
      const spec = st.moduleSpecifier.text;
      let target = null;
      if (spec.startsWith('.')) target = resolveModule(resolve(dirname(file), spec));
      else if (spec.startsWith('@pantopus/')) target = `workspace:${spec.slice('@pantopus/'.length)}`;
      if (!target) continue;
      const bindings = st.importClause.namedBindings;
      if (bindings && ts.isNamedImports(bindings)) for (const el of bindings.elements) out.set(el.name.text, target);
    }
    return out;
  };

  const workspaceDecls = (pkg) => {
    const dir = join(PACKAGES, pkg, 'src');
    const out = new Map();
    for (const name of readdirSync(dir).filter((f) => f.endsWith('.ts'))) for (const [k, v] of typeDecls(join(dir, name))) out.set(k, v);
    return out;
  };

  const capitalized = (text) => new Set(text.match(/\b[A-Z][A-Za-z0-9]*\b/g) ?? []);
  const declared = new Map(); // type name → source file

  // ── The entry's exports, in order ─────────────────────────────
  const entrySf = parse(resolve(entry));
  const specs = [];
  const registries = [];
  for (const st of entrySf.statements) {
    if (!ts.isExportDeclaration(st) || !st.moduleSpecifier || !st.exportClause) continue;
    const spec = st.moduleSpecifier.text;
    for (const el of st.exportClause.elements) {
      if (spec === '@/lib/icons') registries.push(el.name.text);
      else if (spec.startsWith('@/components/')) {
        specs.push({ exportName: el.name.text, local: (el.propertyName ?? el.name).text, file: resolveModule(join(WEB_SRC, spec.slice(2))) });
      }
    }
  }

  const out = [
    `// Pantopus component types (documentation; the page never type-checks them).
// Generated by tools/design-system from frontend/apps/web/src/components.
// Every component is window.Pantopus.<Name> at runtime.
import type * as React from 'react';
import type { ReactNode, ButtonHTMLAttributes } from 'react';
import type { LucideIcon } from 'lucide-react';`,
  ];

  const typed = [];
  let group = null;
  for (const file of [...new Set(specs.map((s) => s.file))]) {
    const rel = relative(WEB_SRC, file);
    const label = GROUPS.find(([prefix]) => rel.startsWith(prefix))[1];
    if (label !== group) {
      out.push(`\n// ════ ${label} ════`);
      group = label;
    }
    out.push(`\n// ── ${rel.replace(/^components\//, '')} ──`);

    const sf = parse(file);
    const own = typeDecls(file);
    const fileSpecs = specs.filter((s) => s.file === file);
    const renames = new Map();
    const functions = new Map();
    let defaultName = null;
    for (const st of sf.statements) {
      if (ts.isFunctionDeclaration(st) && st.name) {
        if (st.modifiers?.some((m) => m.kind === ts.SyntaxKind.DefaultKeyword)) defaultName = st.name.text;
        const param = st.parameters[0];
        functions.set(st.name.text, { props: param?.type ? param.type.getText(sf).replace(/\s*\n\s*/g, ' ') : '{}' });
      }
      if (ts.isVariableStatement(st)) {
        for (const d of st.declarationList.declarations) {
          if (d.initializer && ts.isCallExpression(d.initializer) && /forwardRef/.test(d.initializer.expression.getText(sf))) {
            const [ref, props] = d.initializer.typeArguments.map((a) => a.getText(sf));
            functions.set(d.name.getText(sf), { ref, props });
          }
        }
      }
      if (ts.isExportAssignment(st)) defaultName = st.expression.getText(sf);
    }
    for (const s of fileSpecs) {
      s.fn = s.local === 'default' ? defaultName : s.local;
      if (s.fn !== s.exportName && own.has(`${s.fn}Props`)) renames.set(`${s.fn}Props`, `${s.exportName}Props`);
    }
    const rename = (text) => [...renames].reduce((acc, [a, b]) => acc.replace(new RegExp(`\\b${a}\\b`, 'g'), b), text);

    const emit = (name, text, from) => {
      const finalName = renames.get(name) ?? name;
      if (declared.has(finalName)) {
        if (declared.get(finalName) === from) return;
        throw new Error(`Type ${finalName} is declared in both ${relative(WEB_SRC, declared.get(finalName))} and ${relative(WEB_SRC, from)}; rename one export in src/entry.tsx`);
      }
      declared.set(finalName, from);
      out.push(rename(text));
    };
    for (const [name, text] of own) emit(name, text, file);

    // Types the props lean on that live in another module; a pulled type's
    // own dependencies resolve inside that module.
    const imports = importsOf(file);
    const pull = (name, from, decls, label) => {
      const text = decls.get(name);
      if (!text || declared.has(renames.get(name) ?? name)) return;
      out.push(`// from ${label}`);
      emit(name, text, from);
      for (const dep of capitalized(text)) if (dep !== name) pull(dep, from, decls, label);
    };
    const used = capitalized([...own.values(), ...fileSpecs.map((s) => functions.get(s.fn)?.props ?? '')].join('\n'));
    for (const name of used) {
      const from = imports.get(name);
      if (!from || own.has(name)) continue;
      const workspace = from.startsWith('workspace:') ? from.slice('workspace:'.length) : null;
      pull(name, from, workspace ? workspaceDecls(workspace) : typeDecls(from), workspace ? `@pantopus/${workspace}` : relative(WEB_SRC, from).replace(/^components\//, ''));
    }

    for (const s of fileSpecs) {
      const fn = functions.get(s.fn);
      if (!fn) throw new Error(`${rel} has no component ${s.fn}`);
      typed.push(s.exportName);
      out.push(
        fn.ref
          ? `export declare const ${s.exportName}: React.ForwardRefExoticComponent<${rename(fn.props)} & React.RefAttributes<${fn.ref}>>;`
          : `export declare function ${s.exportName}(props: ${rename(fn.props)}): React.ReactElement | null;`,
      );
    }
  }

  // ── Declarations written in the entry itself (Button) ──────────
  out.push('\n// ════ Intentional addition (not a web component) ════');
  const localDecls = typeDecls(resolve(entry));
  for (const text of localDecls.values()) out.push(text);
  for (const st of entrySf.statements) {
    if (ts.isFunctionDeclaration(st) && st.name && st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) {
      const param = st.parameters[0];
      typed.push(st.name.text);
      out.push(`/** The web's repeated button recipe (ArchetypePageHeader, StickyFooter, ArchetypeEmptyState) as one component. */`);
      out.push(`export declare function ${st.name.text}(props: ${param.type.getText(entrySf)}): React.ReactElement;`);
    }
  }

  const iconConsts = entrySf.statements
    .filter((st) => ts.isVariableStatement(st) && st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword))
    .flatMap((st) => st.declarationList.declarations.map((d) => d.name.getText(entrySf)));
  const iconNames = [...registries, ...iconConsts];
  out.push(`
// ════ Icons ════
type IconMap = Record<string, LucideIcon>;
/** The web icon registries from src/lib/icons.ts, plus the glyphs the previews use. Never emoji. */
${iconNames.map((n) => `export declare const ${n}: IconMap;`).join('\n')}

declare global {
  interface Window {
    Pantopus: {
${components.map((n) => `      ${n}: typeof ${n};`).join('\n')}
${iconNames.map((n) => `      ${n}: IconMap;`).join('\n')}
    };
  }
}
`);

  for (const n of components) if (!typed.includes(n)) warnings.push(`catalogue component ${n} has no type declaration (is it exported from src/entry.tsx?)`);
  for (const n of typed) if (!components.includes(n)) warnings.push(`${n} is exported but has no preview in content/previews.mjs`);
  return { text: out.join('\n'), warnings };
}
