-- Add media_thumbnails column to Post table for feed image optimization.
-- Stores thumb-variant URLs generated by imageResizeService (same pipeline
-- already used for Listing).

ALTER TABLE "public"."Post"
  ADD COLUMN IF NOT EXISTS "media_thumbnails" text[];
