-- ============================================================
-- 197 — Address calendar: statewide property-tax dates (national footing)
--
-- The registry shipped seeded for Washington only. This adds the
-- property-tax due dates for every state whose schedule is set STATEWIDE
-- by statute (36 states + DC). States where counties, towns or school
-- districts set their own dates are deliberately absent — silence beats
-- a wrong date: AK GA IL ME NE NH NY OH PA RI VT VA. Those arrive as
-- county rules.
--
-- Every row is 'unverified' on purpose: seeded from published state
-- schedules, not yet confirmed against the statute by a person, and the
-- card says so. Flip a row to 'official' with a statute citation in
-- `source_url` once checked. Washington (migration 195) stays official.
-- Dates are the last day to pay without penalty; where a state bills
-- earlier with a discount, the detail says so.
-- ============================================================

INSERT INTO "public"."AddressCalendarRule"
    ("scope_type", "scope_key", "kind", "title", "detail", "rrule", "dtstart", "lead_days", "source", "source_url", "confidence")
VALUES
    ('state', 'AL', 'property_tax', 'Property tax due',
     'Alabama property taxes are due October 1 and become delinquent after December 31. Pay by December 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Alabama Department of Revenue', NULL, 'unverified'),
    ('state', 'AZ', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due October 1 and delinquent after November 1. Pay by November 1.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=1', '2026-11-01', 14, 'Arizona Department of Revenue (A.R.S. 42-18052)', NULL, 'unverified'),
    ('state', 'AZ', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due March 1 and delinquent after May 1. Pay by May 1.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=1', '2026-05-01', 14, 'Arizona Department of Revenue (A.R.S. 42-18052)', NULL, 'unverified'),
    ('state', 'AR', 'property_tax', 'Property tax due',
     'Arkansas property taxes are due by October 15.',
     'FREQ=YEARLY;BYMONTH=10;BYMONTHDAY=15', '2026-10-15', 14, 'Arkansas Department of Finance and Administration', NULL, 'unverified'),
    ('state', 'CA', 'property_tax', 'Property tax — first installment due',
     'The first installment is due November 1 and delinquent after December 10. Pay by December 10.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=10', '2026-12-10', 14, 'California State Board of Equalization', NULL, 'unverified'),
    ('state', 'CA', 'property_tax', 'Property tax — second installment due',
     'The second installment is due February 1 and delinquent after April 10. Pay by April 10.',
     'FREQ=YEARLY;BYMONTH=4;BYMONTHDAY=10', '2026-04-10', 14, 'California State Board of Equalization', NULL, 'unverified'),
    ('state', 'CO', 'property_tax', 'Property tax — first half due',
     'Pay the first half by February 28, or the full amount by April 30.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=28', '2026-02-28', 14, 'Colorado Department of Local Affairs, Division of Property Taxation', NULL, 'unverified'),
    ('state', 'CO', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due June 15.',
     'FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=15', '2026-06-15', 14, 'Colorado Department of Local Affairs, Division of Property Taxation', NULL, 'unverified'),
    ('state', 'CT', 'property_tax', 'Property tax — first installment due',
     'Most Connecticut towns bill in two installments due July 1 and January 1; some bill annually. Your town sets the schedule.',
     'FREQ=YEARLY;BYMONTH=7;BYMONTHDAY=1', '2026-07-01', 14, 'Connecticut Office of Policy and Management', NULL, 'unverified'),
    ('state', 'CT', 'property_tax', 'Property tax — second installment due',
     'Most Connecticut towns bill in two installments due July 1 and January 1. Your town sets the schedule.',
     'FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=1', '2026-01-01', 14, 'Connecticut Office of Policy and Management', NULL, 'unverified'),
    ('state', 'DE', 'property_tax', 'Property tax due',
     'Delaware county property taxes are due September 30.',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=30', '2026-09-30', 14, 'Delaware county tax offices', NULL, 'unverified'),
    ('state', 'DC', 'property_tax', 'Property tax — first half due',
     'First-half real property taxes are due March 31.',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31', '2026-03-31', 14, 'DC Office of Tax and Revenue', NULL, 'unverified'),
    ('state', 'DC', 'property_tax', 'Property tax — second half due',
     'Second-half real property taxes are due September 15.',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=15', '2026-09-15', 14, 'DC Office of Tax and Revenue', NULL, 'unverified'),
    ('state', 'FL', 'property_tax', 'Property tax due',
     'Florida taxes are billed November 1 with early-payment discounts (4% in November); they become delinquent April 1. Pay by March 31.',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31', '2026-03-31', 14, 'Florida Department of Revenue', NULL, 'unverified'),
    ('state', 'HI', 'property_tax', 'Property tax — first half due',
     'Hawaii counties bill in two installments due August 20 and February 20.',
     'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=20', '2026-08-20', 14, 'Hawaii county real property tax offices', NULL, 'unverified'),
    ('state', 'HI', 'property_tax', 'Property tax — second half due',
     'Hawaii counties bill in two installments due August 20 and February 20.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=20', '2026-02-20', 14, 'Hawaii county real property tax offices', NULL, 'unverified'),
    ('state', 'ID', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due December 20.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=20', '2026-12-20', 14, 'Idaho State Tax Commission', NULL, 'unverified'),
    ('state', 'ID', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due June 20.',
     'FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=20', '2026-06-20', 14, 'Idaho State Tax Commission', NULL, 'unverified'),
    ('state', 'IN', 'property_tax', 'Property tax — spring installment due',
     'The spring installment is due May 10.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=10', '2026-05-10', 14, 'Indiana Department of Local Government Finance', NULL, 'unverified'),
    ('state', 'IN', 'property_tax', 'Property tax — fall installment due',
     'The fall installment is due November 10.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=10', '2026-11-10', 14, 'Indiana Department of Local Government Finance', NULL, 'unverified'),
    ('state', 'IA', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due September 30 (delinquent October 1).',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=30', '2026-09-30', 14, 'Iowa Department of Revenue', NULL, 'unverified'),
    ('state', 'IA', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due March 31 (delinquent April 1).',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31', '2026-03-31', 14, 'Iowa Department of Revenue', NULL, 'unverified'),
    ('state', 'KS', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due December 20.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=20', '2026-12-20', 14, 'Kansas Department of Revenue', NULL, 'unverified'),
    ('state', 'KS', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due May 10.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=10', '2026-05-10', 14, 'Kansas Department of Revenue', NULL, 'unverified'),
    ('state', 'KY', 'property_tax', 'Property tax due',
     'Kentucky property taxes carry a discount if paid in November and a penalty after December 31. Pay by December 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Kentucky Department of Revenue', NULL, 'unverified'),
    ('state', 'LA', 'property_tax', 'Property tax due',
     'Louisiana parish property taxes are due December 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Louisiana Tax Commission', NULL, 'unverified'),
    ('state', 'MD', 'property_tax', 'Property tax — first half due',
     'Owner-occupied homes may pay in two installments: September 30 and December 31. Annual bills are due September 30.',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=30', '2026-09-30', 14, 'Maryland Department of Assessments and Taxation', NULL, 'unverified'),
    ('state', 'MD', 'property_tax', 'Property tax — second half due',
     'The second semiannual installment is due December 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Maryland Department of Assessments and Taxation', NULL, 'unverified'),
    ('state', 'MA', 'property_tax', 'Property tax — quarterly installment due',
     'Most Massachusetts municipalities bill quarterly: August 1, November 1, February 1, and May 1. Your city or town sets the schedule.',
     'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=1', '2026-08-01', 14, 'Massachusetts Department of Revenue, Division of Local Services', NULL, 'unverified'),
    ('state', 'MA', 'property_tax', 'Property tax — quarterly installment due',
     'Most Massachusetts municipalities bill quarterly: August 1, November 1, February 1, and May 1.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=1', '2026-11-01', 14, 'Massachusetts Department of Revenue, Division of Local Services', NULL, 'unverified'),
    ('state', 'MA', 'property_tax', 'Property tax — quarterly installment due',
     'Most Massachusetts municipalities bill quarterly: August 1, November 1, February 1, and May 1.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=1', '2026-02-01', 14, 'Massachusetts Department of Revenue, Division of Local Services', NULL, 'unverified'),
    ('state', 'MA', 'property_tax', 'Property tax — quarterly installment due',
     'Most Massachusetts municipalities bill quarterly: August 1, November 1, February 1, and May 1.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=1', '2026-05-01', 14, 'Massachusetts Department of Revenue, Division of Local Services', NULL, 'unverified'),
    ('state', 'MI', 'property_tax', 'Property tax — summer taxes due',
     'Summer taxes are billed July 1 and due September 14.',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=14', '2026-09-14', 14, 'Michigan Department of Treasury', NULL, 'unverified'),
    ('state', 'MI', 'property_tax', 'Property tax — winter taxes due',
     'Winter taxes are billed December 1 and due February 14.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=14', '2026-02-14', 14, 'Michigan Department of Treasury', NULL, 'unverified'),
    ('state', 'MN', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due May 15.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=15', '2026-05-15', 14, 'Minnesota Department of Revenue', NULL, 'unverified'),
    ('state', 'MN', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due October 15.',
     'FREQ=YEARLY;BYMONTH=10;BYMONTHDAY=15', '2026-10-15', 14, 'Minnesota Department of Revenue', NULL, 'unverified'),
    ('state', 'MS', 'property_tax', 'Property tax due',
     'Mississippi property taxes are due February 1.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=1', '2026-02-01', 14, 'Mississippi Department of Revenue', NULL, 'unverified'),
    ('state', 'MO', 'property_tax', 'Property tax due',
     'Missouri property taxes are due December 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Missouri State Tax Commission', NULL, 'unverified'),
    ('state', 'MT', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due November 30.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=30', '2026-11-30', 14, 'Montana Department of Revenue', NULL, 'unverified'),
    ('state', 'MT', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due May 31.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=31', '2026-05-31', 14, 'Montana Department of Revenue', NULL, 'unverified'),
    ('state', 'NV', 'property_tax', 'Property tax — first installment due',
     'Nevada bills quarterly; the first installment is due the third Monday of August.',
     'FREQ=YEARLY;BYMONTH=8;BYDAY=3MO', '2026-08-17', 14, 'Nevada Department of Taxation', NULL, 'unverified'),
    ('state', 'NV', 'property_tax', 'Property tax — second installment due',
     'The second installment is due the first Monday of October.',
     'FREQ=YEARLY;BYMONTH=10;BYDAY=1MO', '2026-10-05', 14, 'Nevada Department of Taxation', NULL, 'unverified'),
    ('state', 'NV', 'property_tax', 'Property tax — third installment due',
     'The third installment is due the first Monday of January.',
     'FREQ=YEARLY;BYMONTH=1;BYDAY=1MO', '2026-01-05', 14, 'Nevada Department of Taxation', NULL, 'unverified'),
    ('state', 'NV', 'property_tax', 'Property tax — fourth installment due',
     'The fourth installment is due the first Monday of March.',
     'FREQ=YEARLY;BYMONTH=3;BYDAY=1MO', '2026-03-02', 14, 'Nevada Department of Taxation', NULL, 'unverified'),
    ('state', 'NJ', 'property_tax', 'Property tax — quarterly installment due',
     'New Jersey property taxes are due quarterly: February 1, May 1, August 1, and November 1.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=1', '2026-02-01', 14, 'New Jersey Division of Taxation', NULL, 'unverified'),
    ('state', 'NJ', 'property_tax', 'Property tax — quarterly installment due',
     'New Jersey property taxes are due quarterly: February 1, May 1, August 1, and November 1.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=1', '2026-05-01', 14, 'New Jersey Division of Taxation', NULL, 'unverified'),
    ('state', 'NJ', 'property_tax', 'Property tax — quarterly installment due',
     'New Jersey property taxes are due quarterly: February 1, May 1, August 1, and November 1.',
     'FREQ=YEARLY;BYMONTH=8;BYMONTHDAY=1', '2026-08-01', 14, 'New Jersey Division of Taxation', NULL, 'unverified'),
    ('state', 'NJ', 'property_tax', 'Property tax — quarterly installment due',
     'New Jersey property taxes are due quarterly: February 1, May 1, August 1, and November 1.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=1', '2026-11-01', 14, 'New Jersey Division of Taxation', NULL, 'unverified'),
    ('state', 'NM', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due November 10 (delinquent after December 10).',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=10', '2026-11-10', 14, 'New Mexico Taxation and Revenue Department', NULL, 'unverified'),
    ('state', 'NM', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due April 10 (delinquent after May 10).',
     'FREQ=YEARLY;BYMONTH=4;BYMONTHDAY=10', '2026-04-10', 14, 'New Mexico Taxation and Revenue Department', NULL, 'unverified'),
    ('state', 'NC', 'property_tax', 'Property tax due',
     'North Carolina taxes are due September 1 and delinquent after January 5. Pay by January 5.',
     'FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=5', '2026-01-05', 14, 'North Carolina Department of Revenue', NULL, 'unverified'),
    ('state', 'ND', 'property_tax', 'Property tax due',
     'North Dakota taxes carry a 5% discount if paid by February 15 and become delinquent March 1. Pay by February 15.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=15', '2026-02-15', 14, 'North Dakota Office of State Tax Commissioner', NULL, 'unverified'),
    ('state', 'OK', 'property_tax', 'Property tax due',
     'Oklahoma taxes are due December 31, or in halves by December 31 and March 31.',
     'FREQ=YEARLY;BYMONTH=12;BYMONTHDAY=31', '2026-12-31', 14, 'Oklahoma Tax Commission', NULL, 'unverified'),
    ('state', 'OK', 'property_tax', 'Property tax — second half due',
     'If paying in halves, the second half is due March 31.',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31', '2026-03-31', 14, 'Oklahoma Tax Commission', NULL, 'unverified'),
    ('state', 'OR', 'property_tax', 'Property tax due',
     'Oregon taxes are due November 15; pay in full for a 3% discount, or the first of three installments.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=15', '2026-11-15', 14, 'Oregon Department of Revenue', NULL, 'unverified'),
    ('state', 'OR', 'property_tax', 'Property tax — second installment due',
     'The second trimester installment is due February 15.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=15', '2026-02-15', 14, 'Oregon Department of Revenue', NULL, 'unverified'),
    ('state', 'OR', 'property_tax', 'Property tax — third installment due',
     'The third trimester installment is due May 15.',
     'FREQ=YEARLY;BYMONTH=5;BYMONTHDAY=15', '2026-05-15', 14, 'Oregon Department of Revenue', NULL, 'unverified'),
    ('state', 'SC', 'property_tax', 'Property tax due',
     'South Carolina property taxes are due January 15.',
     'FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=15', '2026-01-15', 14, 'South Carolina Department of Revenue', NULL, 'unverified'),
    ('state', 'SD', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due April 30.',
     'FREQ=YEARLY;BYMONTH=4;BYMONTHDAY=30', '2026-04-30', 14, 'South Dakota Department of Revenue', NULL, 'unverified'),
    ('state', 'SD', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due October 31.',
     'FREQ=YEARLY;BYMONTH=10;BYMONTHDAY=31', '2026-10-31', 14, 'South Dakota Department of Revenue', NULL, 'unverified'),
    ('state', 'TN', 'property_tax', 'Property tax due',
     'Tennessee county taxes are due October 1 and delinquent March 1. Pay by the end of February.',
     'FREQ=YEARLY;BYMONTH=2;BYMONTHDAY=28', '2026-02-28', 14, 'Tennessee Comptroller of the Treasury', NULL, 'unverified'),
    ('state', 'TX', 'property_tax', 'Property tax due',
     'Texas property taxes are due January 31.',
     'FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=31', '2026-01-31', 14, 'Texas Comptroller of Public Accounts', NULL, 'unverified'),
    ('state', 'UT', 'property_tax', 'Property tax due',
     'Utah property taxes are due November 30.',
     'FREQ=YEARLY;BYMONTH=11;BYMONTHDAY=30', '2026-11-30', 14, 'Utah State Tax Commission', NULL, 'unverified'),
    ('state', 'WV', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due September 1 (discount if paid by then).',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=1', '2026-09-01', 14, 'West Virginia State Tax Department', NULL, 'unverified'),
    ('state', 'WV', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due March 1.',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=1', '2026-03-01', 14, 'West Virginia State Tax Department', NULL, 'unverified'),
    ('state', 'WI', 'property_tax', 'Property tax — first installment due',
     'Pay in full or the first installment by January 31.',
     'FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=31', '2026-01-31', 14, 'Wisconsin Department of Revenue', NULL, 'unverified'),
    ('state', 'WI', 'property_tax', 'Property tax — second installment due',
     'The second installment is due July 31.',
     'FREQ=YEARLY;BYMONTH=7;BYMONTHDAY=31', '2026-07-31', 14, 'Wisconsin Department of Revenue', NULL, 'unverified'),
    ('state', 'WY', 'property_tax', 'Property tax — first half due',
     'First-half taxes are due September 1 (delinquent after November 10).',
     'FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=1', '2026-09-01', 14, 'Wyoming Department of Revenue', NULL, 'unverified'),
    ('state', 'WY', 'property_tax', 'Property tax — second half due',
     'Second-half taxes are due March 1 (delinquent after May 10).',
     'FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=1', '2026-03-01', 14, 'Wyoming Department of Revenue', NULL, 'unverified')
ON CONFLICT DO NOTHING;
